### ISSUE TITLE
유튜브 다운이 안되네요

### ISSUE THREAD

**Issue by hegoog** [KurtBestor/Hitomi-Downloader-issues#10]
정말 유용한 프로그램 잘쓰고있습니다

다른건 다 잘되고 지인은 유튜브도 잘된다는

 저는 유튜브 주소치면 Fail 뜨면서 안되네요

아래는 로그입니다

Traceback (most recent call last):
  File "customWidget.pyo", line 380, in showMenu
RuntimeError: wrapped C/C++ object of type QToolButton has been deleted

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭 후 [정보...]를 눌러보시면 정보창이 나옵니다.

내용 보내주시면 감사하겠습니다.

**Comment by hegoog** [comment]
Fail: youtube_https://youtu.be / JdwH5P3rQzs

gal_num: https://youtu.be/JdwH5P3rQzs
dir: 
zip: 
type: youtube
artist: None
url: https://youtu.be/JdwH5P3rQzs
valid: False
done: False


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 2383, in download_hitomi
File "hitomi_downloader", line 1811, in download_youtube
File "youtube_downloader", line 62, in get_video
File "FUUUUCK\__main__", line 81, in __init__
File "FUUUUCK\__main__", line 89, in prefetch_init
File "FUUUUCK\__main__", line 142, in prefetch
File "FUUUUCK\request", line 21, in get
File "urllib2", line 154, in urlopen
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1241, in https_open
File "urllib2", line 1198, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Fail: youtube

done : https://youtu.be/JdwH5P3rQzs

이렇게뜹니당

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
의심가는 부분 고쳐봤습니다. 이걸로 한번 되는지 확인 부탁드려요!

**Comment by hegoog** [comment]
잘됩니다!

**Comment by KurtBestor** [comment]
v2.0에서 해결됨
