### ISSUE TITLE
마나모이 어떤 만화는 다운이 안되네요 ㅜㅜ

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#1013]
Invalid : [manamoa] https://manamoa8.net / bbs / page.php?hid=manga_detail&manga_id=1173

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=1173
dir: 
zip: 
type: manamoa
artist: Koi
url: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=1173
valid: False
done: False
range: None
range_p: None
single: False
time: 1563670800.02 (Jul 21)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 272, in get_imgs_page
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 322, in get_imgs_page_legacy
File "manamoa_downloader", line 61, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

stop
Traceback (most recent call last):
File "utils", line 535, in start
File "utils", line 579, in start_
File "manamoa_downloader", line 128, in read
File "manamoa_downloader", line 257, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 272, in get_imgs_page
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 322, in get_imgs_page_legacy
File "manamoa_downloader", line 61, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

Fail: manamoa

done : https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=1173

다른 만화는 괜찮은데 이 만화만 오류가 나옵니다. 무슨 문제일까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kikinet88** [comment]
마나모아 링크가 현제 사망한게 꽤 됩니다
최신작 링크도 사망 또는 완전 외부 링크로 운영되어서
해당 링크는 다운로드를 막아두는 상황이라 인식이 안될수도 있습니다
제가 외부링크 타고 강제로 받기 할려니 잘 안되더군요
일단 마나모아 측에서 3~6일 지나면 풀어주니 그때 다시 해보시는걸 추천드립니다
