### ISSUE TITLE
마나모아 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by cancerogenic** [KurtBestor/Hitomi-Downloader-issues#1016]
Invalid : [manamoa] https://manamoa8.net / bbs / board.php?bo_table=manga&wr_id=1569072

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=1569072
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=4171
valid: False
done: False
range: None
range_p: None
single: False
time: 1563966572.32 (Jul 24)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=4171
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 144, in get_soup
File "utils", line 1296, in Soup
File "bs4\__init__", line 121, in __init__
File "bs4\__init__", line 162, in _feed
File "bs4\builder\_htmlparser", line 247, in feed
File "HTMLParser", line 54, in feed
File "HTMLParser", line 126, in goahead
File "bs4\builder\_htmlparser", line 155, in handle_charref
File "encodings\__init__", line 43, in search_function
File "zipextimporter", line 46, in load_module
IOError: [Errno 2] No such file or directory: 'E:\\Downloads\\hitomi_downloader_GUI\\hitomi_downloader_GUI.exe'

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "manamoa_downloader", line 125, in read
File "manamoa_downloader", line 111, in name
File "manamoa_downloader", line 97, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 144, in get_soup
File "utils", line 1296, in Soup
File "bs4\__init__", line 121, in __init__
File "bs4\__init__", line 162, in _feed
File "bs4\builder\_htmlparser", line 247, in feed
File "HTMLParser", line 54, in feed
File "HTMLParser", line 126, in goahead
File "bs4\builder\_htmlparser", line 155, in handle_charref
File "encodings\__init__", line 43, in search_function
File "zipextimporter", line 46, in load_module
IOError: [Errno 2] No such file or directory: 'E:\\Downloads\\hitomi_downloader_GUI\\hitomi_downloader_GUI.exe'

Fail: manamoa

done : https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=1569072

invalid가 뜹니다

**Comment by KurtBestor** [comment]
C 드라이브로 옮겨서 실행해도 그런가요?

**Comment by kikinet88** [comment]
해당링크는 현제 외부 웹을 이용중이라 마나모아 자체 링크와 다릅니다
그래서 페이지 5~8까지만 읽어들이고 그외 외부 링크라 인식을 못하는겁니다
제가 받아보니 그렇게 나오네요 히토미다운로더 문제는 아닙니다
