### ISSUE TITLE
마나모아 다운로드 오류

### ISSUE THREAD

**Issue by meloncafe** [KurtBestor/Hitomi-Downloader-issues#1084]
오류나는 주소들
---
- https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=695515
- https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=723605
- https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=815414
- https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=862600
- https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=755166
---

실제로 들어가보면 표시는 정상적으로 되는데 다운로드시에 오류가 발생합니다
확인 부탁드립니다

---
Invalid : [manamoa] https://manamoa8.net / bbs / board.php?bo_table=manga&wr_id=695515

version: 2.6d
platform: Windows-10-10.0.17763
gal_num: https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=695515
dir: 
zip: 
type: manamoa
artist: 오카모토 린
url: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=4969
valid: False
done: False
range: None
range_p: None
single: False
time: 1564995431.48 (Aug 5)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=4969
dirFormat: [artist] title
[seed] 패러렐 파라다이스 74화 344660
[seed] 패러렐 파라다이스 74화 344660
[seed] 패러렐 파라다이스 74화 344660
[seed] 패러렐 파라다이스 74화 344660
[seed] 패러렐 파라다이스 74화 344660
[seed] 패러렐 파라다이스 74화 344660
[seed] 패러렐 파라다이스 74화 344660
[seed] 패러렐 파라다이스 74화 344660
fuckkk...
Traceback (most recent call last):
File "constants", line 601, in wrapper
File "manamoa_downloader", line 280, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 91, in get
File "FUCK(5)\remote\webdriver", line 333, in get
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 402, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=59199): Read timed out. (read timeout=<object object at 0x024584A8>)

stop
Traceback (most recent call last):
File "utils", line 535, in start
File "utils", line 579, in start_
File "manamoa_downloader", line 128, in read
File "manamoa_downloader", line 257, in get_imgs
File "constants", line 618, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 601, in wrapper
File "manamoa_downloader", line 280, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 91, in get
File "FUCK(5)\remote\webdriver", line 333, in get
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 402, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=59199): Read timed out. (read timeout=<object object at 0x024584A8>)

Fail: manamoa

done : https://manamoa8.net/bbs/board.php?bo_table=manga&wr_id=695515

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by meloncafe** [comment]
네 동일하게 안됩니다.
- https://manamoa8.net/bbs/page.php?hid=manga_detail&manga_id=252

위 주소도 동일한 오류가 발생하고 있습니다
