### ISSUE TITLE
다운로드를 시작해놓고 나중에 확인하면 프로그램이 종료되어 있어요

### ISSUE THREAD

**Issue by Elements8** [KurtBestor/Hitomi-Downloader-issues#1115]
약 850개 정도 히토미에서 다운로드 시작해놓고 나중에 확인했는데 프로그램이 종료되어 있네요.
사용버전은 #1099에서 위에 있는 테스트버전을 사용했습니다.
항상 그런것은 아니고 간헐적으로 발생하는 오류인 것 같습니다.
언제 종료되는건지 정확한 시점은 불분명한데 이렇게 종료되고 프로그램을 다시키면 도움말 옆에 벌레모양의 버튼이 생기고 로그/스레드현황/인터프리터... 이런게 나오네요

로그에 나와있는 내용을 복붙해놓겠습니다

 ==============================
Checking for updates... HitomiDownloader
Checking for updates... version_check.txt

뺍통똤펍덎끲뗓즑뜿끒쪝깭뽞뜺놙꾐꼁푎퀴짧뾛렰됩졡쏡썷괄럲괋뭑쒞쳄굈쏨씭뷻뭠일낒섔왺똿읗쿧섡댴궟쓙솕딄님콓췽텤쒚썫룷럛쎷탹쁃푠컄픴둷렅둣쪞벖쏦똉톆퀡퍊쒪톔쪓촘씄땑배란뛩퍘퀉금릠뽵뮗각

4.8.6 / 4.11.2 / 4.16.3
Font: Gulim -> 맑은 고딕
Supported Image Formats: ['bmp', 'pbm', 'pgm', 'png', 'ppm', 'xbm', 'xpm']
v2.6d (latest : v2.6d)
Encodings: ['cp949', 'mbcs', 'ascii', 'utf-8', 'ascii']
Traceback (most recent call last):
  File "downloader", line 276, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Traceback (most recent call last):
  File "downloader", line 276, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Traceback (most recent call last):
  File "downloader", line 276, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Traceback (most recent call last):
  File "downloader", line 276, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

GoodbyeDPI activated

Styles:
    Windows
    WindowsXP
    WindowsVista
    Motif
    CDE
    Plastique
    Cleanlooks

start GoodbyeDPI
Traceback (most recent call last):
  File "downloader", line 262, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/551272/fb427f5784

Traceback (most recent call last):
  File "downloader", line 262, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/552384/1369efd195

Traceback (most recent call last):
  File "downloader", line 262, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/552368/6d46e75b6d

Traceback (most recent call last):
  File "downloader", line 262, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: https://e-hentai.org/g/552690/a247568d05

Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted

 ===========================

**Comment by KurtBestor** [comment]
작업 900개 이상은 권장하지 않아요. 참고해주세요: #170
