### ISSUE TITLE
모든 인스타 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by saanaaghkd** [KurtBestor/Hitomi-Downloader-issues#1157]
인스타 다운로드가 전부 안 됩니다.

전부 File "insta downloader3", line 55, in read 라는 메시지와 함께 다운로드가 진행되지 않습니다

그 중에 하나 작업 정보 올립니다

Traceback (most recent call last):
File "insta_downloader3", line 55, in read
File "insta_downloader3", line 270, in get_imgs
File "insta_downloader3", line 118, in get_urls
Exception: Invalid page
- barbie_fit_

version: 2.6d
platform: Windows-10-10.0.17134
gal_num: https://www.instagram.com/barbie_fit_/
dir: hitomi_downloaded_insta\바비핏 (insta_barbie_fit_)
zip: 
type: insta
artist: None
url: https://www.instagram.com/barbie_fit_
valid: False
done: False
range: None
range_p: None
single: False
time: 1567329457.85 (Sep 1)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
try v4
Traceback (most recent call last):
File "insta_downloader3", line 261, in get_imgs
File "insta_downloader4", line 27, in get_urls
Exception: Invalid page

try v3
stop
Traceback (most recent call last):
File "insta_downloader3", line 55, in read
File "insta_downloader3", line 270, in get_imgs
File "insta_downloader3", line 118, in get_urls
Exception: Invalid page

Fail: insta

stop
done : https://www.instagram.com/barbie_fit_/

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by saanaaghkd** [comment]
테스트 버전 정상 구동 확인했습니다.

다만 답변까지 시간이 걸려서 먼저 기존 다운로더(옛날에 받아서 업데이트 해온 버전)를 제거하고 아예 다시 새로 받아서 하니 정상 구동했습니다.
