### ISSUE TITLE
유튜브 에러

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader-issues#1158]
[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning

가끔 안되는것들은 다 비슷하네요

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by rlacks1237** [comment]
읽는 중... https://www.youtube.com / watch?v=EuCj0aSEwNY

version: 2.6d
platform: Windows-10-10.0.18362
gal_num: https://www.youtube.com/watch?v=EuCj0aSEwNY
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=EuCj0aSEwNY
valid: True
done: False
range: None
range_p: None
single: True
time: 1567584162.49 (Sep 4)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1163

**Comment by rlacks1237** [comment]
저 파일로 해야하는건가요?
