### ISSUE TITLE
bilibili 영상 다운로드가 안됩니다

### ISSUE THREAD

**Issue by zeroeyes4212** [KurtBestor/Hitomi-Downloader-issues#1167]
안녕하세요.

최근에 bilibili 영상 다운받는데 문제가 없었는데 갑자기 다운이 안되는 영상이 있어 문의드립니다.

어느정도 다운로드가 진행되다가  다운로드 작업색이 주황색이 되고 거기에서 다운이 중지 됩니다.

다시 다운로드하면 1.1kb만 다운받고 작업색 주황색으로 완료됩니다.

version: 2.6d
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.bilibili.com/video/av66453706/?p=2
dir: hitomi_downloaded_bili\【蓝光1080P】TWICE演唱会：TWICELAND ZONE 2 ： Fantasy Park第二次单独巡回演唱会 正片+花絮_p2
zip: 
type: bili
artist: None
url: https://www.bilibili.com/video/av66453706/?p=2
valid: False
done: True
range: None
range_p: None
single: False
time: 1567601540.94 (Sep 4)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_bili\【蓝光1080P】TWICE演唱会：TWICELAND ZONE 2 ： Fantasy Park第二次单独巡回演唱会 正片+花絮_p2\66453706_0.flv

[URLs]
[0001] LazyUrl(https://www.bilibili.com/video/av66453706/?p=2) ---> http://upos-hz-mirrorwcsu.acgvideo.com/upgcxcode/59/08/115310859/115310859-1-80.flv?e=ig8euxZM2rNcNbeM7WdVhoMH7wUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1567608736&gen=playurl&nbs=1&oi=2039623693&os=wcsu&platform=pc&trid=2801aea0608e46d49dd2f9c762353c75&uipk=5&upsig=cea92f51cb14ea9c97dadda97547ff02&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0

[Messages]
resolution: 1080p
n_threads: 8
downloader_v3 fail... p[480 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[478 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 524288 / 1048576

downloader_v3 fail... p[483 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[480 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[484 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[486 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[483 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[480 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[478 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 524288 / 1048576

downloader_v3 fail... p[484 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[488 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[486 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[483 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[480 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[484 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[488 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[483 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[478 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 524288 / 1048576

downloader_v3 fail... p[486 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[480 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 0 / 1048576

downloader_v3 fail... p[484 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 400

downloader_v3 fail... p[488 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 400

downloader_v3 fail... p[483 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 400

downloader_v3 fail... p[478 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 400

downloader_v3 fail... p[486 / 1633]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 400

Traceback (most recent call last):
File "utils", line 674, in start_
File "bili_downloader2", line 88, in post_processing
File "ffmpeg", line 427, in join
File "ffmpeg", line 113, in rename
Exception: No file

done : https://www.bilibili.com/video/av66453706/?p=2

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
