### ISSUE TITLE
이틀전부터 이헨 다운로드가 갑자기 안됍니다

### ISSUE THREAD

**Issue by tpl44** [KurtBestor/Hitomi-Downloader-issues#1177]
![eh](https://user-images.githubusercontent.com/51487672/64467827-bf19a680-d157-11e9-9dcc-08aefbd2b52a.png)

 열개정도 다운로드 잘 돼다가 갑자기 다음것부터 (0/200) 이렇게 다운로드가 안돼다가 그림처럼 빨간색 뜨고 invalid 뜨네요...
그냥 갑자기 저런식이었던게 예전에도 한두번 있었는데 금방 고쳐졌었는데 이번에는 이틀 후에 해도 안돼네요
다른 글들 보니 제작자님이 우클- 정보 눌러서 댓글 달라고 하는 글을 봐서 밑에 올립니다

Invalid: [hitomi] https://e-hentai.org / g / 1410351 / ca1428e9f1 / ?p=8

version: 2.7
platform: Windows-10-10.0.17134
gal_num: https://e-hentai.org/g/1410351/ca1428e9f1/?p=8
dir: 
zip: 
type: ehen
artist: None
url: https://e-hentai.org/g/1410351/ca1428e9f1/?p=8
valid: False
done: True
range: None
range_p: None
single: False
time: 1567778802.6 (Sep 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
********************************
Gallery number : 1410351
Number of Threads : 48
********************************
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 676, in get_imgs
File "hiyobi_downloader", line 24, in pop_img_hiyobi
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 676, in get_imgs
File "hiyobi_downloader", line 24, in pop_img_hiyobi
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://e-hentai.org/g/1410351/ca1428e9f1/?p=8)
#### https://e-hentai.org/g/1410351/ca1428e9f1 ----> https://e-hentai.org/g/1410351/ca1428e9f1
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 678, in get_imgs
File "hitomi_downloader", line 1204, in ehen_imgs
Exception: no images

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 676, in get_imgs
File "hiyobi_downloader", line 24, in pop_img_hiyobi
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://e-hentai.org/g/1410351/ca1428e9f1/?p=8)
#### https://exhentai.org/g/1410351/ca1428e9f1 ----> https://exhentai.org/g/1410351/ca1428e9f1
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 678, in get_imgs
File "hitomi_downloader", line 1204, in ehen_imgs
Exception: no images

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 676, in get_imgs
File "hiyobi_downloader", line 24, in pop_img_hiyobi
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://e-hentai.org/g/1410351/ca1428e9f1/?p=8)
#### https://e-hentai.org/g/1410351/ca1428e9f1 ----> https://e-hentai.org/g/1410351/ca1428e9f1
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 678, in get_imgs
File "hitomi_downloader", line 1204, in ehen_imgs
Exception: no images

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 676, in get_imgs
File "hiyobi_downloader", line 24, in pop_img_hiyobi
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://e-hentai.org/g/1410351/ca1428e9f1/?p=8)
#### https://exhentai.org/g/1410351/ca1428e9f1 ----> https://exhentai.org/g/1410351/ca1428e9f1
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 678, in get_imgs
File "hitomi_downloader", line 1204, in ehen_imgs
Exception: no images

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 676, in get_imgs
File "hiyobi_downloader", line 24, in pop_img_hiyobi
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://e-hentai.org/g/1410351/ca1428e9f1/?p=8)
#### https://e-hentai.org/g/1410351/ca1428e9f1 ----> https://e-hentai.org/g/1410351/ca1428e9f1
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 678, in get_imgs
File "hitomi_downloader", line 1204, in ehen_imgs
Exception: no images

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 668, in get_imgs
File "hitomi", line 19, in pop_img
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 676, in get_imgs
File "hiyobi_downloader", line 24, in pop_img_hiyobi
File "downloader", line 292, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://e-hentai.org/g/1410351/ca1428e9f1/?p=8)
#### https://exhentai.org/g/1410351/ca1428e9f1 ----> https://exhentai.org/g/1410351/ca1428e9f1
Traceback (most recent call last):
File "hitomi_downloader", line 815, in read
File "hitomi_downloader", line 678, in get_imgs
File "hitomi_downloader", line 1204, in ehen_imgs
Exception: no images

FINAL SERVER : auto
ehen_url : None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 862, in read
File "gallery", line 221, in get_gal
Exception: get_gal Invalid server: auto

stop
Invalid: fail=False
stop
EOT: https://e-hentai.org/g/1410351/ca1428e9f1/?p=8

**Comment by siwkd2** [comment]
그건 4페이지 6페이지 주소를 복사하는게 아니라 이미지모음 페이지 주소를 복사하셔야됩니다

**Comment by KurtBestor** [comment]
브라우저에선 들어가지나요?

**Comment by tpl44** [comment]
이건 특정페이지 링크를 복사한것이지만 다른것들은 이미지 모음 페이지 주소를 복사했는데도 invalid 라고 나옵니다

**Comment by tpl44** [comment]
네 예전에 다운 프로그램을 썻다고 몇시간밴~이틀밴(이틀인데 몇시간만에 풀림)을 당해보기는 했는데 일단 브라우저로는 들어가집니다 
이미지 클릭시에도 큰 이미지 보여지고요

**Comment by KurtBestor** [comment]
다음 링크에서 `Image Limits` 가 어떻게 되어있는지 알려주세요:
https://e-hentai.org/home.php

**Comment by tpl44** [comment]
> 다음 링크에서 `Image Limits` 가 어떻게 되어있는지 알려주세요:
> https://e-hentai.org/home.php

백개가량 다운로드를 시도해서 그런가...
지금 이틀밴 먹어서 1d 10hr 뒤에 접속 가능하다고 나오네요 그때 다시 하겠습니다

**Comment by tpl44** [comment]
> 다음 링크에서 `Image Limits` 가 어떻게 되어있는지 알려주세요:
> https://e-hentai.org/home.php

아 지금 풀렸는지 접속 되네요 이미지 리미트는 항상 0으로 돼있습니다 예전에도 이것때문인가 하고 봤는데 아니었네요.
히토미와 히요비는 괜찮은데 가끔씩 이러면 이헨만 꼭 문제가 납니다 이헨이 검색부터 편한게 많아서 자주 쓰는건데.
예전에는 안됄떄 dpi 우회를 누르면 됐었는데 지금은 해제했다 활성화했다 반복해도 안됍니다
