### ISSUE TITLE
유튜브 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by a24325** [KurtBestor/Hitomi-Downloader-issues#1196]
모든 영상이 안됩니다.

Invalid: [youtube] https://www.youtube.com / watch?v=Zl_RvSL1OTg

version: 2.7
platform: Windows-10-10.0.17763
gal_num: https://www.youtube.com/watch?v=Zl_RvSL1OTg
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=Zl_RvSL1OTg
valid: False
done: True
range: None
range_p: None
single: True
time: 1568216727.25 (Sep 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

stop
Traceback (most recent call last):
File "utils", line 634, in start
File "utils", line 680, in start_
File "youtube_downloader", line 138, in read
File "constants", line 640, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video is unavailable.

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=Zl_RvSL1OTg

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by rlacks1237** [comment]
저도 같은 현상이 있어서 혹시나 하고 해봤는데 다운되네요 감사합니다

**Comment by a24325** [comment]
잘 됩니다. 감사합니다.
