### ISSUE TITLE
마루마루 다운이 안됩니다..

### ISSUE THREAD

**Issue by mr99999** [KurtBestor/Hitomi-Downloader-issues#121]
비번 걸린건 다운이 다 안되네요.. 비번없는건 잘 되구요..
고급설정에서 reCAPTCHA 뚫기 설정했는데도 안되네요..
다른 글 보고 실행폴더에 chromedriver.exe을 지워봐도 소용이 없네요.
chrome_data 폴더는 없었구요..
혹시나 해서 크롬으로 직접들어가서 비번 입력하면 잘 보입니다만.. 프로그램으로 하면 안되네요...

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

크롬 창이 뜨나요? 증상을 좀 더 자세히 알려주세요.

**Comment by mr99999** [comment]
이것도 안되네요;;
크롬창은 크롬창이 뜬다는게 아니라 프로그램만 안되는건지 직접 사이트 들어가도 안되는지 몰라서.. 직접 크롬으로 사이트들어가서 비번입력하고 들어가본거에요..

계속 읽는중만 뜨고 안되네요..

그리고 이젠 비번 있는것만 아니라 비번 없는것도 다운이 안되네요;; 

Invalid : [maru] maru_265287

gal_num: maru_265287
dir: 
zip: 
type: maru
artist: None
url: http://marumaru.in/b/manga/265287
valid: False
done: False
range: None
range_p: None


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


stop
Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 487, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 483, in wrapper
File "maru_downloader", line 374, in read_html
File "downloader", line 258, in read_html
Exception: ???


Fail: maru

stop
done : maru_265287
