### ISSUE TITLE
유튜브 성인 영상 다운로드 오류

### ISSUE THREAD

**Issue by listandtag** [KurtBestor/Hitomi-Downloader-issues#1211]
https://www.youtube.com/watch?v=jnCoqqwWQ0I
일단 다른 성인 영상도 안 되는지는 확인을 안 해봤습니다...

Invalid: [youtube] https://www.youtube.com / watch?v=jnCoqqwWQ0I

version: 2.7
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=jnCoqqwWQ0I
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=jnCoqqwWQ0I
valid: False
done: True
range: None
range_p: None
single: True
time: 1568792470.68 (Sep 18)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

stop
Traceback (most recent call last):
File "utils", line 641, in start
File "utils", line 687, in start_
File "youtube_downloader", line 138, in read
File "constants", line 640, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=jnCoqqwWQ0I

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1163
