### ISSUE TITLE
다운로드가 제대로 완료되지 않았는데도 압축->원복삭제가 진행되는 경우가 있습니다

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader-issues#1255]
그리고 불완전다운로드된 항목을 해당폴더를 삭제하지 않은채로 다시시작했더니 문제가 된 페이지가 빠진채로 압축->원본삭제된다음 다운로드 목록에는 또 제대로 완료된것으로 표시됩니다.
몇번을 재시도해도 파일 2장이 다운이 안되는 항목도 있습니다.
수작업으로 보충해볼까 했지만 몇페이지가 빠진것인지 모르겠습니다
해당 항목의 정보는 아래와 같습니다

-----------------------
[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉

version: 2.7b
platform: Windows-10-10.0.17763
gal_num: [Arigase Shinji] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHaa CG Shuu (1475693)
dir: C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉
zip: C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉.zip
type: hitomi
artist: arigase shinji
url: https://hitomi.la/galleries/1475693.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1570371794.03 (Oct 6)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False

[Gallery]
갤러리 넘버: 1475693

제목: Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHaa CG Shuu

작가: arigase shinji

그룹: lolitachannel

타입: artistcg

시리즈: ore no imouto ga konna ni kawaii wake ga nai

캐릭터: N/A

태그: mosaic censorship, female:loli

언어: N/A

[File Names]
[0001] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\01_RJ146728_img_main.jpg
[0002] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\02_at_ayase.jpg
[0003] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\03_at_kanbri.jpg
[0004] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\04_at_rurihina.jpg
[0005] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\05_at_saori.jpg
[0006] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\06_lo_ayase.jpg
[0007] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\07_lo_kanako.jpg
[0008] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\08_lo_saori.jpg
[0009] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\09_ma_trio.jpg
[0010] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\10_ra_ria.jpg
[0011] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\11_ra_siroaya.jpg
[0012] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\12_screencapture_at_ayase_htm.png
[0013] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\13_screencapture_at_kanbri_htm.png
[0014] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\14_screencapture_at_rurihina_htm.png
[0015] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\15_screencapture_at_saori_htm.png
[0016] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\16_screencapture_lo_ayase_htm.png
[0017] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\17_screencapture_lo_kanako_htm.png
[0018] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\18_screencapture_lo_saori_htm.png
[0019] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\19_screencapture_ma_trio_htm.png
[0020] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\20_screencapture_ra_ria_htm.png
[0021] C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉\21_screencapture_ra_siroaya_htm.png

[URLs]
[0001] https://aa.hitomi.la/galleries/1475693/01_RJ146728_img_main.jpg
[0002] https://aa.hitomi.la/galleries/1475693/02_at_ayase.jpg
[0003] https://aa.hitomi.la/galleries/1475693/03_at_kanbri.jpg
[0004] https://aa.hitomi.la/galleries/1475693/04_at_rurihina.jpg
[0005] https://aa.hitomi.la/galleries/1475693/05_at_saori.jpg
[0006] https://aa.hitomi.la/galleries/1475693/06_lo_ayase.jpg
[0007] https://aa.hitomi.la/galleries/1475693/07_lo_kanako.jpg
[0008] https://aa.hitomi.la/galleries/1475693/08_lo_saori.jpg
[0009] https://aa.hitomi.la/galleries/1475693/09_ma_trio.jpg
[0010] https://aa.hitomi.la/galleries/1475693/10_ra_ria.jpg
[0011] https://aa.hitomi.la/galleries/1475693/11_ra_siroaya.jpg
[0012] https://aa.hitomi.la/galleries/1475693/12_screencapture_at_ayase_htm.png
[0013] https://aa.hitomi.la/galleries/1475693/13_screencapture_at_kanbri_htm.png
[0014] https://aa.hitomi.la/galleries/1475693/14_screencapture_at_rurihina_htm.png
[0015] https://aa.hitomi.la/galleries/1475693/15_screencapture_at_saori_htm.png
[0016] https://aa.hitomi.la/galleries/1475693/16_screencapture_lo_ayase_htm.png
[0017] https://aa.hitomi.la/galleries/1475693/17_screencapture_lo_kanako_htm.png
[0018] https://aa.hitomi.la/galleries/1475693/18_screencapture_lo_saori_htm.png
[0019] https://aa.hitomi.la/galleries/1475693/19_screencapture_ma_trio_htm.png
[0020] https://aa.hitomi.la/galleries/1475693/20_screencapture_ra_ria_htm.png
[0021] https://aa.hitomi.la/galleries/1475693/21_screencapture_ra_siroaya_htm.png

[Messages]
get_imgs server: hitomi
Size (https://aa.hitomi.la/galleries/1475693/01_RJ146728_img_main.jpg): 242043 status: 200
FINAL SERVER : hitomi
ehen_url : None
imgs: 21

Title :
[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉

skip zip: C:\Users\kdss9\Downloads\manga\[Arigase Shinji][Lolitachannel] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHa 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│N／A│(1475693)〉.zip
valid=False 2
Compress... \01_RJ146728_img_main.jpg
Compress... \02_at_ayase.jpg
Compress... \03_at_kanbri.jpg
Compress... \04_at_rurihina.jpg
Compress... \05_at_saori.jpg
Compress... \06_lo_ayase.jpg
Compress... \07_lo_kanako.jpg
Compress... \08_lo_saori.jpg
Compress... \09_ma_trio.jpg
Compress... \10_ra_ria.jpg
Compress... \11_ra_siroaya.jpg
Compress... \12_screencapture_at_ayase_htm.png
Compress... \13_screencapture_at_kanbri_htm.png
Compress... \15_screencapture_at_saori_htm.png
Compress... \16_screencapture_lo_ayase_htm.png
Compress... \17_screencapture_lo_kanako_htm.png
Compress... \18_screencapture_lo_saori_htm.png
Compress... \19_screencapture_ma_trio_htm.png
Compress... \20_screencapture_ra_ria_htm.png
EOT: #-*- [Arigase Shinji] Yuumei Chara Kannou Shousetsu CG Shuu No. 273!! Ore no Imouto ga Konna ni Kawaii Wake ga Nai 3 HaaHaa CG Shuu (1475693)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by supermekadeathstalin** [comment]
불완전한 상태로 압축되는 문제는 사라졌는데 불완전 다운로드 문제는 여전히 있습니다. 예전에 다운로드 했을때는 별탈없이 다운됬었던건데.  몇개는 계속 재시도하니까 완료됬는데 안되는건 끝까지 안되네요.

**Comment by KurtBestor** [comment]
계속 안되는 작업 정보 보여주세요.

**Comment by KurtBestor** [comment]
계속 안 되는 작업 정보 보여주세요.

**Comment by supermekadeathstalin** [comment]
다섯개인데 너무 기니까 하나만 올립니다.
-------


[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉

version: 2.7b
platform: Windows-10-10.0.17763
gal_num: [Ohtomo Takuji] Damette Ittemo Nakadashi Surundesuyone (517322)
dir: C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉
zip: 
type: hitomi
artist: ohtomo takuji
url: https://hitomi.la/galleries/517322.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1570673499.55 (Oct 10)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False


[Gallery]
갤러리 넘버: 517322

제목: Damette Ittemo Nakadashi Surundesuyone

작가: ohtomo takuji

그룹: number2

타입: doujinshi

시리즈: ore no imouto ga konna ni kawaii wake ga nai

캐릭터: ayase aragaki, kyousuke kousaka

태그: female:anal, female:bikini, female:nakadashi, female:schoolgirl uniform, female:swimsuit, female:x-ray, full color, mosaic censorship

언어: Japanese


[File Names]
[0001] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\1.jpg
[0002] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\2.jpg
[0003] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\3.jpg
[0004] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\4.jpg
[0005] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\5.jpg
[0006] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\6.jpg
[0007] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\7.jpg
[0008] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\8.jpg
[0009] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\9.jpg
[0010] C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\10.jpg


[URLs]
[0001] https://ca.hitomi.la/galleries/517322/1.jpg
[0002] https://ca.hitomi.la/galleries/517322/2.jpg
[0003] https://ca.hitomi.la/galleries/517322/3.jpg
[0004] https://ca.hitomi.la/galleries/517322/4.jpg
[0005] https://ca.hitomi.la/galleries/517322/5.jpg
[0006] https://ca.hitomi.la/galleries/517322/6.jpg
[0007] https://ca.hitomi.la/galleries/517322/7.jpg
[0008] https://ca.hitomi.la/galleries/517322/8.jpg
[0009] https://ca.hitomi.la/galleries/517322/9.jpg
[0010] https://ca.hitomi.la/galleries/517322/10.jpg


[Messages]
get_imgs server: hitomi
Size (https://ca.hitomi.la/galleries/517322/1.jpg): 2575188 status: 200
FINAL SERVER : hitomi
ehen_url : None
imgs: 10

Title :
[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\3.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\4.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\6.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\7.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\8.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\9.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\3.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\4.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\7.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\6.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\8.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\9.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\3.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\4.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\7.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\6.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\8.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found


Fail : \\?\C:\Users\kdss9\Downloads\manga\[Ohtomo Takuji][Number2] Damette Ittemo Nakadashi Surundesuyone 〈Ore No Imouto Ga Konna Ni Kawaii Wake Ga Nai│Japanese│(517322)〉\9.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

valid=False 1
EOT: #-*- [Ohtomo Takuji] Damette Ittemo Nakadashi Surundesuyone (517322)

**Comment by KurtBestor** [comment]
히토미 사이트에서 직접 봐도 안 보이는 이미지들이네요. 서버 문제예요.
