### ISSUE TITLE
마나모아 일부 파일이 다운로드 안받아 지네요

### ISSUE THREAD

**Issue by caisia** [KurtBestor/Hitomi-Downloader-issues#1266]
Invalid: [manamoa] https://manamoa15.net / bbs / board.php?bo_table=manga&wr_id=797738

version: 2.7b
platform: Windows-10-10.0.17763
gal_num: https://manamoa15.net/bbs/board.php?bo_table=manga&wr_id=797738
dir: 
zip: 
type: manamoa
artist: 쿨교신자
url: https://manamoa15.net/bbs/page.php?hid=manga_detail&manga_id=4798
valid: False
done: True
range: None
range_p: None
single: False
time: 1570618349.75 (Oct 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://manamoa15.net/bbs/page.php?hid=manga_detail&manga_id=4798
dirFormat: [artist] title
[seed] 코바야시네의 메이드래곤 82화 383350
[seed] 코바야시네의 메이드래곤 82화 383350
[seed] 코바야시네의 메이드래곤 82화 383350
[seed] 코바야시네의 메이드래곤 82화 383350
[seed] 코바야시네의 메이드래곤 82화 383350
[seed] 코바야시네의 메이드래곤 82화 383350
[seed] 코바야시네의 메이드래곤 82화 383350
[seed] 코바야시네의 메이드래곤 82화 383350
fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "manamoa_downloader", line 265, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 91, in get
File "FUCK(5)\remote\webdriver", line 333, in get
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 402, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=6923): Read timed out. (read timeout=<object object at 0x02468470>)

stop
Traceback (most recent call last):
File "utils", line 708, in start
File "utils", line 754, in start_
File "manamoa_downloader", line 122, in read
File "manamoa_downloader", line 242, in get_imgs
File "constants", line 640, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "manamoa_downloader", line 265, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 91, in get
File "FUCK(5)\remote\webdriver", line 333, in get
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 402, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=6923): Read timed out. (read timeout=<object object at 0x02468470>)

Invalid: fail=True
EOT: https://manamoa15.net/bbs/board.php?bo_table=manga&wr_id=797738

이런식으로 오류나면서 안받아 지는 파일들이 일부 존재 하네요

**Comment by KurtBestor** [comment]
다시 시도해도 안 되나요?

**Comment by caisia** [comment]
넵 다시시도해도 같은 오류가 발생 합니다.

**Comment by KurtBestor** [comment]
제 쪽에선 재현할 수 없네요.

**Comment by caisia** [comment]
아... 다른 피씨에서 해보던가 해봐야 겠네요...
