### ISSUE TITLE
마나모아 다운이 안되네요.

### ISSUE THREAD

**Issue by Honeyneo** [KurtBestor/Hitomi-Downloader-issues#1279]
마나모아 다운이 안됩니다. 

Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=4366

version: 2.7b
platform: Windows-10-10.0.18362
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4366
dir: 
zip: 
type: manamoa
artist: 스바루 이치
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4366
valid: False
done: True
range: None
range_p: [212]
single: False
time: 1570934463.4 (Oct 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "manamoa_downloader", line 257, in get_imgs_page
File "constants", line 632, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "manamoa_downloader", line 307, in get_imgs_page_legacy
File "manamoa_downloader", line 55, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

stop
Traceback (most recent call last):
File "utils", line 728, in start
File "utils", line 774, in start_
File "manamoa_downloader", line 122, in read
File "manamoa_downloader", line 242, in get_imgs
File "constants", line 632, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "manamoa_downloader", line 257, in get_imgs_page
File "constants", line 632, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "manamoa_downloader", line 307, in get_imgs_page_legacy
File "manamoa_downloader", line 55, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4366

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1277
