### ISSUE TITLE
유튜브 다운로드가 작동하지 않습니다

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader-issues#1290]
![20191018_012004](https://user-images.githubusercontent.com/36811336/67028018-91a41d80-f145-11e9-8b02-73f91c505854.png)

링크로 이동하면 아무 문제 없이 재생됩니다. 

https://youtu.be/ztKqa7jkN4s
https://youtu.be/xCjqjAB5gYE

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by Yoon0618** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

Invalid: [youtube] https://youtu.be / xCjqjAB5gYE

version: 2.7b
platform: Windows-10-10.0.17763
gal_num: https://youtu.be/xCjqjAB5gYE
dir: 
zip: 
type: youtube
artist: None
url: https://youtu.be/xCjqjAB5gYE
valid: False
done: True
range: None
range_p: None
single: True
time: 1571329045.29 (Oct 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data

stop
Traceback (most recent call last):
File "utils", line 708, in start
File "utils", line 754, in start_
File "youtube_downloader", line 142, in read
File "constants", line 640, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: xCjqjAB5gYE: YouTube said: Unable to extract video data


Invalid: fail=True
EOT: https://youtu.be/xCjqjAB5gYE

**Comment by Yoon0618** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

오늘 다시 해보니 정상적으로 다운로드 되네요.
