### ISSUE TITLE
히토미 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by rsef1234** [KurtBestor/Hitomi-Downloader-issues#1303]
어제는 잘 되던게 오늘 이상이 생겼습니다
히토미에 미러링 되어있고 잘 보이는 것을 다운하는데 우선순위가 히토미가 먼저임에도 이헨으로 다운이 받아지고 히토미를 수동으로 설정해서 다운로드하면 0p를 다운하고 완료됐다고 뜹니다
히토미쪽이 더 좋은 화질로 받아지는거 같아서 가능하면 이쪽으로 다운받고 싶은데 확인해주실 수 있나요?

히토미로 수동설정 후 0p다운로드 됐을때 정보를 첨부합니다
[Kishizuka Kenji] Intention Ch. 1-5e (1504422)

version: 2.7b
platform: Windows-10-10.0.18362
gal_num: https://hitomi.la/galleries/1504422.html
dir: hitomi_downloaded\[Kishizuka Kenji] Intention Ch. 1-5e (1504422)
zip: 
type: hitomi
artist: kishizuka kenji
url: https://hitomi.la/galleries/1504422.html
valid: True
done: True
range: None
range_p: None
single: False
time: 1571699498.87 (Oct 22)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False

[Gallery]
갤러리 넘버: 1504422

제목: Intention Ch. 1-5e

작가: kishizuka kenji

그룹: N/A

타입: manga

시리즈: N/A

캐릭터: N/A

태그: female:ahegao, female:apron, female:beauty mark, female:big breasts, female:blackmail, female:blowjob, female:cheating, female:dark skin, female:deepthroat, female:kissing, female:milf, female:nakadashi, female:ponytail, female:rape, female:sole female, female:sweating, full censorship, male:hairy, male:sweating, multi-work series

언어: Korean

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

get_imgs server: hitomi:la
Traceback (most recent call last):
File "hitomi_downloader", line 812, in read
File "hitomi_downloader", line 686, in get_imgs
Exception: No imgs

FINAL SERVER : hitomi:la
ehen_url : None
imgs: 0
get_title__

Title :
[Kishizuka Kenji] Intention Ch. 1-5e (1504422)

EOT: https://hitomi.la/galleries/1504422.html

**Comment by whgmlqja12** [comment]
동일증상 겪었습니다. 몇몇개는 바로 이헨으로 연결되고 몇몇개는 아예 다운조차 안되서 0p로 다운완료 됩니다.

**Comment by bringemichum** [comment]
same here, i can't download anything in hitomi.la. i have tried three servers, but none of them work

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by rsef1234** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

다운 잘 됩니다 감사합니다
