### ISSUE TITLE
마나모아 일부 파일는 다운이 안받아 지네요

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader-issues#1304]
이상하게도 다른건 잘되는데..요 
Invalid: [manamoa] https://manamoa16.net / bbs / board.php?bo_table=manga&wr_id=2137483

version: 2.7b
platform: Windows-10-10.0.17763
gal_num: https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2137483
dir: 
zip: 
type: manamoa
artist: 사카모토 아키라
url: https://manamoa16.net/bbs/page.php?hid=manga_detail&manga_id=10017
valid: False
done: True
range: None
range_p: None
single: False
time: 1571709125.08 (Oct 22)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://manamoa16.net/bbs/page.php?hid=manga_detail&manga_id=10017
dirFormat: [artist] title
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
[seed] 복수를 바라는 최강용사는, 어둠의 힘으로 섬멸무쌍한다 8화 332920
fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "manamoa_downloader", line 278, in get_imgs_page
File "capture", line 29, in capture
File "phantomjs", line 178, in start
File "phantomjs", line 79, in __init__
File "FUCK(5)\phantomjs\webdriver", line 56, in __init__
File "FUCK(5)\common\service", line 100, in start
File "FUCK(5)\common\service", line 113, in assert_process_still_running
WebDriverException: Message: Service c:\users\admini~1\appdata\local\temp\phantomjs.exe unexpectedly exited. Status code was: -1073741819

stop
Traceback (most recent call last):
File "utils", line 738, in start
File "utils", line 787, in start_
File "manamoa_downloader", line 135, in read
File "manamoa_downloader", line 255, in get_imgs
File "constants", line 640, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "manamoa_downloader", line 278, in get_imgs_page
File "capture", line 29, in capture
File "phantomjs", line 178, in start
File "phantomjs", line 79, in __init__
File "FUCK(5)\phantomjs\webdriver", line 56, in __init__
File "FUCK(5)\common\service", line 100, in start
File "FUCK(5)\common\service", line 113, in assert_process_still_running
WebDriverException: Message: Service c:\users\admini~1\appdata\local\temp\phantomjs.exe unexpectedly exited. Status code was: -1073741819

Invalid: fail=True
EOT: https://manamoa16.net/bbs/board.php?bo_table=manga&wr_id=2137483

이 두개가 다운이 안받아 지네요

**Comment by KurtBestor** [comment]
웹브라우저에서 보는 건 되나요?

**Comment by geniussjt** [comment]
네 웹브라우저 문제는 아닌 걸로 짐작...또 사이트 문제인가요 
진짜로 다른건 다 잘되는데요T^T

**Comment by KurtBestor** [comment]
저는 이렇게 뜨네요:
![image](https://user-images.githubusercontent.com/14768120/67257449-f4d7dc00-f4c6-11e9-870f-46483d0aed9e.png)

**Comment by geniussjt** [comment]
이상하네요 전 잘 나오는데...그런다면 진짜로 지금 사이트에 문제있군요ㅠ-ㅠ
그럼 사이트 정상화 될때까지 기다려야겠네요T^T
빠른 답변 정말 감사합니다^^
