### ISSUE TITLE
히토미 삭제된 데이터가 안받아 집니다

### ISSUE THREAD

**Issue by hjhsys** [KurtBestor/Hitomi-Downloader-issues#1307]
항상 감사하게 잘 쓰고 있습니다

오랫동안 못쓰다가 오늘 이용하려고 기본 데이터랑 삭제된 데이터를 다운 받으려는데

기본 데이터는 다운이 받아지는데 삭제된 데이터는

Traceback (most recent call last);
 File "hitom_searcher', line 116, in
donwnload_json_forbidden
 File "zip_forbidden", line 54, in load
 File "zipfile", line 1063, in extractall
 File "zipfile", line 1051, in extract
 File "zipfile", line 1106, in extract_member
IOError: [Errno 13} Permission denied: u'C:
\\\ucd94\ucd9c\hitomi_data\\galleries0_forbidden.json'

이렇게 뜨면서 자꾸 실패 하네요
관리자 권한으로도 해봤고, 이전버전 몇개 다운받아서 해봤는데도 안되네요

에러메세지는 복사가 안되길레 그냥 따라 적은거라 한두문장 정도는 틀릴 수 도 있을 거예요

**Comment by KurtBestor** [comment]
재부팅 후에 시도해도 안 되나요?

**Comment by hjhsys** [comment]
네 재부팅 몇번 해 봤는데 안되네요...
