### ISSUE TITLE
Pornhub 프리미엄 다운로드 불가 관련 추가 질문사항

### ISSUE THREAD

**Issue by orangespoons** [KurtBestor/Hitomi-Downloader-issues#1335]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1296

제가 예전에 드렸던 질문입니다.
ID/PW를 어떤 이메일로 보내야 할까요?

추가 정보)) 스크린샷과 오류정보를 긁어왔습니다.
DPI문제는 아닌 듯 한게, 프로그램 내 DPI설정 ON/OFF 다 테스트해봤고,
GoodbyeDPI와 시크릿디피아이, SafeVisit 3가지 프로그램을 각각 ON/OFF하면서 실험해봤습니다.
결과는 같더라구요.

주소)
https://www.pornhubpremium.com/view_video.php?viewkey=ph5da6fb6e547d8
https://www.pornhubpremium.com/view_video.php?viewkey=ph5daac741b0010 

스크린샷)
https://ibb.co/HTsqnR8

오류정보)
Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5daac741b0010

version: 2.7c
platform: Windows-10-10.0.18362
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5daac741b0010
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5daac741b0010
valid: False
done: True
range: None
range_p: None
single: True
time: 1572084477.28 (Oct 26)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
Video
[1080p] 
[1080p] 
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[1080, 720, 480, 240]p] 
force
fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "pornhub_downloader", line 258, in get_video
File "pornhub_downloader", line 197, in get_video_new
File "youtube_dl\YoutubeDL", line 830, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: no suitable InfoExtractor for URL https://www.pornhubpremium.com/view_video.php?viewkey=ph5daac741b0010

stop
Traceback (most recent call last):
File "utils", line 738, in start
File "utils", line 787, in start_
File "pornhub_downloader", line 138, in read
File "constants", line 640, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 615, in wrapper
File "pornhub_downloader", line 258, in get_video
File "pornhub_downloader", line 197, in get_video_new
File "youtube_dl\YoutubeDL", line 830, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: no suitable InfoExtractor for URL https://www.pornhubpremium.com/view_video.php?viewkey=ph5daac741b0010

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5daac741b0010

**Comment by KurtBestor** [comment]
mangrovn★gmail.com 으로 보내주세요. (★ -> @)

**Comment by orangespoons** [comment]
> mangrovn★gmail.com 으로 보내주세요. (★ -> @)

보냈습니다!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by orangespoons** [comment]
로딩을 1~2분정도 하긴 하지만
정상적으로 받아지는 것 확인했습니다
감사합니다!
