### ISSUE TITLE
이헨에서 다운로드가 안되는 파일이 있습니다.

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader-issues#1344]
히토미에서 파일이 손상되어있어 이헨에서 같은 파일을 찾아
다운을 받으려는데 서버를 이헨으로 지정하니 다운이 되지 않습니다.
https://e-hentai.org/g/1075414/6af3193160/

Invalid: [hitomi] https://e-hentai.org / g / 1075414 / 6af3193160 / 

version: 2.7c
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://e-hentai.org/g/1075414/6af3193160/
dir: 
zip: 
type: ehen
artist: None
url: https://e-hentai.org/g/1075414/6af3193160/
valid: False
done: True
range: None
range_p: None
single: False
time: 1572323258.23 (Oct 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
FINAL SERVER: ehen
ehen_url: None
imgs: 0
get_title_ehen: 1075414
TITLE FAILED : ehen (1)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2C1AF6B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_title_ehen: 1075414
TITLE FAILED : ehen (2)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2D54DE30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_title_ehen: 1075414
TITLE FAILED : ehen (3)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2D54D8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_title_ehen: 1075414
TITLE FAILED : ehen (4)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2DB00530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_title_ehen: 1075414
TITLE FAILED : ehen (5)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2C0B82F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_title_ehen: 1075414
TITLE FAILED : ehen (6)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x37571A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_title_ehen: 1075414
TITLE FAILED : ehen (7)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2CA74D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_title_ehen: 1075414
TITLE FAILED : ehen (8)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2D6A66F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

Traceback (most recent call last):
File "hitomi_downloader", line 684, in read
File "gallery", line 217, in get_gal
File "gallery", line 315, in get_gal_ehen
Exception: Cant get title - ehen (1075414)
Traceback (most recent call last):
File "gallery", line 306, in get_gal_ehen
File "gallery", line 360, in get_gal__ehen
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2D6A66F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

stop
Invalid: fail=False
stop
EOT: https://e-hentai.org/g/1075414/6af3193160/

다운로더 버전은 2.7c 픽시브 ip 접속 차단 수정한 test 버전입니다.
다운로더 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by yuchan39** [comment]
정상작동 확인했습니다. 감사합니다!
