### ISSUE TITLE
이헨에서 다운로드가 안되는 파일이 있습니다.

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader-issues#1350]
Invalid: [hitomi] https://exhentai.org / g / 69663 / 3d0e560b71 / 

version: 2.7c
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://exhentai.org/g/69663/3d0e560b71/
dir: 
zip: 
type: exhen
artist: None
url: https://exhentai.org/g/69663/3d0e560b71/
valid: False
done: True
range: None
range_p: None
single: False
time: 1572406491.78 (Oct 30)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Size (https://aa.hitomi.la/galleries/69663/ikazuchi05_001.jpg): 513004 status: 200
FINAL SERVER: hitomi
ehen_url: None
imgs: 260
TITLE FAILED (1)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 470, in get_gal__
IndexError: list index out of range

TITLE FAILED (2)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 470, in get_gal__
IndexError: list index out of range

TITLE FAILED (3)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 470, in get_gal__
IndexError: list index out of range

TITLE FAILED (4)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 470, in get_gal__
IndexError: list index out of range

TITLE FAILED (5)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 470, in get_gal__
IndexError: list index out of range

TITLE FAILED (6)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 470, in get_gal__
IndexError: list index out of range

TITLE FAILED : brute (1)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : brute (2)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : brute (3)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : brute (4)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : hiyobi (1)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 286, in get_gal_hiyobi
Exception: No loader

TITLE FAILED : hiyobi (2)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 286, in get_gal_hiyobi
Exception: No loader

TITLE FAILED : hiyobi (3)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 286, in get_gal_hiyobi
Exception: No loader

TITLE FAILED : hiyobi (4)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 286, in get_gal_hiyobi
Exception: No loader

Traceback (most recent call last):
File "hitomi_downloader", line 683, in read
File "gallery", line 215, in get_gal
File "gallery", line 352, in get_gal_
Exception: Cant get title

stop
Invalid: fail=False
stop
EOT: https://exhentai.org/g/69663/3d0e560b71/

다운로더는 test 버전 최신입니다.
다운로더 잘 쓰고 있습니다. 감사합니다.

**Comment by yuchan39** [comment]
서버를 이헨으로 따로 지정하니 다시 다운로드 되네요.
