### ISSUE TITLE
invalid exhentai

### ISSUE THREAD

**Issue by wantcxy** [KurtBestor/Hitomi-Downloader-issues#1355]
![QQ截图20191031141620](https://user-images.githubusercontent.com/57209492/67923563-2cdacf80-fbe9-11e9-8275-8191aff24cb3.jpg)
Invalid: [hitomi] https://exhentai.org / g / 1428501 / d400bd476b / 

version: 2.7c
platform: Windows-10-10.0.18362
gal_num: https://exhentai.org/g/1428501/d400bd476b/
dir: 
zip: 
type: exhen
artist: None
url: https://exhentai.org/g/1428501/d400bd476b/
valid: False
done: True
range: None
range_p: None
single: False
time: 1572500704.45 (Oct 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Size (https://ba.hitomi.la/galleries/1428501/089.png): 1192130 status: 200
FINAL SERVER: hitomi
ehen_url: None
imgs: 26
TITLE FAILED (1)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 465, in get_gal__
File "downloader", line 291, in read_html
Exception: 404

TITLE FAILED (2)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 465, in get_gal__
File "downloader", line 291, in read_html
Exception: 404

TITLE FAILED (3)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 465, in get_gal__
File "downloader", line 291, in read_html
Exception: 404

TITLE FAILED (4)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 465, in get_gal__
File "downloader", line 291, in read_html
Exception: 404

TITLE FAILED (5)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 465, in get_gal__
File "downloader", line 291, in read_html
Exception: 404

TITLE FAILED (6)
Traceback (most recent call last):
File "gallery", line 325, in get_gal_
File "gallery", line 465, in get_gal__
File "downloader", line 291, in read_html
Exception: 404

TITLE FAILED : brute (1)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : brute (2)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : brute (3)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : brute (4)
Traceback (most recent call last):
File "gallery", line 338, in get_gal_
File "gallery", line 579, in get_gal_brute
File "gallery", line 158, in html2gal
File "gallery", line 165, in html2gal_galleryblock
IndexError: list index out of range

TITLE FAILED : hiyobi (1)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 242, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'text'

TITLE FAILED : hiyobi (2)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 242, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'text'

TITLE FAILED : hiyobi (3)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 242, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'text'

TITLE FAILED : hiyobi (4)
Traceback (most recent call last):
File "gallery", line 346, in get_gal_
File "gallery", line 242, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'text'

Traceback (most recent call last):
File "hitomi_downloader", line 731, in read
File "gallery", line 215, in get_gal
File "gallery", line 352, in get_gal_
Exception: Cant get title

stop
Invalid: fail=False
stop
EOT: https://exhentai.org/g/1428501/d400bd476b/

**Comment by wantcxy** [comment]
I don't know how to solve this problem.

**Comment by KurtBestor** [comment]
Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
I fixed the issue. Now it's working again in server mode `Auto`.
