### ISSUE TITLE
invalid문구 말고도 죄다 빨간색이 뜹니다 

### ISSUE THREAD

**Issue by ssjyham** [KurtBestor/Hitomi-Downloader-issues#1357]
![스크린샷(17)](https://user-images.githubusercontent.com/56762735/67966775-c933bf00-fc47-11e9-8599-07b9555113c6.png)
어떻게 해야하나요

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by ssjyham** [comment]
Invalid: [hitomi] https://e-hentai.org / s / d4fd27eec9 / 1399853

version: 2.7d
platform: Windows-10-10.0.18362
order: 2
group: False
gal_num: https://e-hentai.org/s/d4fd27eec9/1399853
dir: 
zip: 
type: ehen
artist: None
url: https://e-hentai.org/s/d4fd27eec9/1399853
valid: False
done: True
range: None
range_p: None
single: False
time: 1572798762.83 (Nov 4)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
FINAL SERVER: hiyobi
ehen_url: None
imgs: 56
Traceback (most recent call last):
File "hitomi_downloader", line 683, in read
File "gallery", line 222, in get_gal
File "gallery", line 245, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'text'

stop
Invalid: fail=False
stop
EOT: https://e-hentai.org/s/d4fd27eec9/1399853
