### ISSUE TITLE
픽시브코믹이 다운이 되지 않습니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader-issues#1372]
Invalid: [pixiv_comic] https://comic.pixiv.net / works / 5777

version: 2.7d
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://comic.pixiv.net/works/5777
dir: 
zip: 
type: pixiv_comic
artist: None
url: https://comic.pixiv.net/works/5777
valid: False
done: True
range: None
range_p: None
single: False
time: 1572859774.31 (Nov 4)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Message: session not created: This version of ChromeDriver only supports Chrome version 76

stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "pixiv_comic_downloader", line 76, in read
File "pixiv_comic_downloader", line 60, in name
File "pixiv_comic_downloader", line 55, in soup
File "pixiv_comic_downloader", line 89, in get_soup
File "pixiv_comic_downloader", line 95, in read_html
File "chrome", line 154, in start
File "chrome", line 80, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 76

Invalid: fail=True
EOT: https://comic.pixiv.net/works/5777

크롬업데이트후 안되는것 같습니다
부탁드립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
오 잘되네요 감사합니다
