### ISSUE TITLE
히요비 다운이 안됩니다

### ISSUE THREAD

**Issue by gevela** [KurtBestor/Hitomi-Downloader-issues#1380]
히요비 사이트에서 주소를 그대로 복붙했는데 invalid 뜹니다
https://히요비.asia/reader/1467714
사용한 주소는 이거구요 히요비.asia를 hiyobi.me로 바꿔서도 해봤는데 똑같습니다.
Invalid: [hitomi] https://히요비.asia / reader / 1467714

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://히요비.asia/reader/1467714
dir: 
zip: 
type: hiyobi
artist: None
url: https://히요비.asia/reader/1467714
valid: False
done: True
range: None
range_p: None
single: False
time: 1573276065.84 (Nov 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
FINAL SERVER: hiyobi
ehen_url: None
imgs: 37
Traceback (most recent call last):
File "hitomi_downloader", line 683, in read
File "gallery", line 222, in get_gal
File "gallery", line 245, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'text'

stop
Invalid: fail=False
stop
EOT: https://히요비.asia/reader/1467714

우클릭 - 정보 누르면 이렇게 나옵니다
분명 히요비엔 멀쩡히 업로드 되있는건데 다운로드를 못하네요

**Comment by gevela** [comment]
네 아직도 안되네요

Invalid: [hitomi] https://히요비.asia / reader / 1467714

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://히요비.asia/reader/1467714
dir: 
zip: 
type: hiyobi
artist: None
url: https://히요비.asia/reader/1467714
valid: False
done: True
range: None
range_p: None
single: False
time: 1573492852.58 (Nov 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
FINAL SERVER: hiyobi
ehen_url: None
imgs: 37
Traceback (most recent call last):
File "hitomi_downloader", line 683, in read
File "gallery", line 222, in get_gal
File "gallery", line 245, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'text'

stop
Invalid: fail=False
stop
EOT: https://히요비.asia/reader/1467714


이렇게 떠요. 다운로더 다시 다운받아서 해봤는데도 그러네요

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 창 열고 다음과 같이 입력하고 <kbd>Enter</kbd> 누르세요:
```
with open('test_hiyobi.txt', 'w') as f: f.write(downloader.read_html('https://xn--9w3b15m8vo.asia/info/1467714').encode('utf8')) 
```

그러면 실행파일 경로에 `test_hiyobi.txt` 가 만들어졌을텐데 파일 보내주세요.

**Comment by gevela** [comment]
[test_hiyobi.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3832557/test_hiyobi.txt)
열어봤는데 해외에서 히요비 접속할때랑 똑같이 뜨는거 보면 vpn 써서 다운받아야되는거같네요

**Comment by KurtBestor** [comment]
웹에선 히요비 어떻게 접속하시나요?

**Comment by gevela** [comment]
크롬 확장 프로그램으로 vpn쓰는데 확장 프로그램이라서 다운로더는 안되네요. 한국으로 우회할 수 있는 vpn을 찾아될듯 하네요

**Comment by gevela** [comment]
vpn써서 해봤는데 잘 되네요
