### ISSUE TITLE
폰헙(pornhub), 유튭 다운 질문드립니다.

### ISSUE THREAD

**Issue by sg01007** [KurtBestor/Hitomi-Downloader-issues#1400]
버전은 현재 

v2.7d를 쓰고 있습니다.

질문 드리고 싶은 것은 몇몇 폰헙 영상과 유튭영상이 다운이 되질 않아서 어떻게 해야하는지 여쭤보고자 합니다. 

유튭
https://www.youtube.com/watch?v=y5lnvZnWUQc&has_verified=1

폰헙
https://cn.pornhub.com/view_video.php?viewkey=ph5da211747880d
폰헙은 cn을 www로 바꿔서도 해봤습니다.

**Comment by sg01007** [comment]
유튭 정보

Invalid: [youtube] https://www.youtube.com / watch?v=y5lnvZnWUQc

version: 2.7d
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=y5lnvZnWUQc
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=y5lnvZnWUQc
valid: False
done: True
range: None
range_p: None
single: True
time: 1573822294.17 (Nov 15)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "youtube_downloader", line 138, in read
File "constants", line 633, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age


Invalid: fail=True
EOT: https://www.youtube.com/watch?v=y5lnvZnWUQc

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age

stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "youtube_downloader", line 138, in read
File "constants", line 633, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Content Warning
This video may be inappropriate for some users.
Sign in to confirm your age


Invalid: fail=True
EOT: https://www.youtube.com/watch?v=y5lnvZnWUQc

**Comment by sg01007** [comment]
폰헙은 여러번 시도 하니깐 되네요

**Comment by KurtBestor** [comment]
로그인이 필요한 영상인데, 현재 로그인은 지원하지 않아서 다운로드 불가능해요.

**Comment by sg01007** [comment]
> 로그인이 필요한 영상인데, 현재 로그인은 지원하지 않아서 다운로드 불가능해요.

유튜브 로그인이 아닌 다른 어떤 로그인을 말씀하시는 건가요?

**Comment by KurtBestor** [comment]
유튜브 로그인이요.

**Comment by sg01007** [comment]
> 유튜브 로그인이요.

저 유튜브에 로그인이 되어있는데, 어떻게 로그인 해야 하는건가요?

**Comment by KurtBestor** [comment]
브라우저에서 로그인 정보를 가져오진 못 하고, 프로그램에서 따로 로그인을 해야해요.

현재 Pixiv, Flickr, Niconico, Pornhub 등 일부분만 구현되었어요.

만약에 구현되면 `옵션` - `설정... (F5)` - `유튜브` 에 추가될거예요.

**Comment by sg01007** [comment]
> 브라우저에서 로그인 정보를 가져오진 못 하고, 프로그램에서 따로 로그인을 해야해요.
> 
> 현재 Pixiv, Flickr, Niconico, Pornhub 등 일부분만 구현되었어요.
> 
> 만약에 구현되면 `옵션` - `설정... (F5)` - `유튜브` 에 추가될거예요.

답변 정말 감사합니다!
