### ISSUE TITLE
유튜브 다운로드가 막힌것 같습니다

### ISSUE THREAD

**Issue by lducjswo** [KurtBestor/Hitomi-Downloader-issues#1412]
어제 오후까지만해도 잘 되다가
저녁 11시쯤부터 한두개씩 invalid가 뜨면서 안되더니 이젠 아예 모든 영상이 다운로드되질 않네요

Invalid: [youtube] https://www.youtube.com / watch?v=AkWSBYyqbbM

version: 2.7d
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=AkWSBYyqbbM
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=AkWSBYyqbbM
valid: False
done: True
range: None
range_p: None
single: True
time: 1574208771.74 (Nov 20)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "youtube_downloader", line 138, in read
File "constants", line 633, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "youtube_downloader", line 291, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: AkWSBYyqbbM: YouTube said: Unable to extract video data

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=AkWSBYyqbbM

혹시나 해서 ummy video downloader나 1gram player 같은 프로그램도 써봤는데 다 안되는거 보니  유튜브 자체적인 문제이거나 제 ip가 막힌걸까요?

**Comment by KurtBestor** [comment]
사이트에서 직접 보는 건 되나요?

**Comment by lducjswo** [comment]
혹시나해서 ip변경했더니 됩니다
변경전에도 보는건 됐었구요
제 ip가 막혔었나봅니다
