### ISSUE TITLE
기본 데이터 다운로드 이슈

### ISSUE THREAD

**Issue by aria1th** [KurtBestor/Hitomi-Downloader-issues#1414]
---------------------------
Hitomi Downloader
---------------------------
데이터를 다운로드하는 중에 실패했습니다.
Traceback (most recent call last):  File "hitomi_searcher", line 214, in download_json  File "hitomi_searcher", line 372, in download_json_ValueError: Expected object or value

---------------------------
확인   자세한 정보 숨기기...   
---------------------------

직접 링크를 붙여넣어서 다운로드하는건 되는데 기본 데이터가 다운로드되지 않네요.
삭제된 데이터는 정상적으로 다운로드됩니다

**Comment by aria1th** [comment]
현재는 또 되는걸 보니 일시적인 서버 문제같아요
