### ISSUE TITLE
마나모아 차단스크립트 있는 듯 합니다. 

### ISSUE THREAD

**Issue by korhentai** [KurtBestor/Hitomi-Downloader-issues#1417]
<img src="https://imgdb.in/g9mx.jpg">
invalid 라고 뜨면서 다운로드가 되지 않습니다.

`
Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=4291

version: 2.7d
platform: Windows-10-10.0.10240
order: 0
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4291
dir: 
zip: 
type: manamoa
artist: 토조 치카
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4291
valid: False
done: True
range: None
range_p: None
single: False
time: 1574508746.67 (Nov 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
[seed] 유녀전기 1화 0
[seed] 유녀전기 2-1화 0
[seed] 유녀전기 2-2화 0
[seed] 유녀전기 3화 0
[seed] 유녀전기 4화 0
[seed] 유녀전기 5-1화 0
[seed] 유녀전기 5-2화 0
[seed] 유녀전기 6-1화 0
[seed] 유녀전기 6-2화 0
[seed] 유녀전기 7화 0
[seed] 유녀전기 8화 0
[seed] 유녀전기 8-2화 0
[seed] 유녀전기 9화 0
[seed] 유녀전기 10화 0
[seed] 유녀전기 11화 0
[seed] 유녀전기 11-2화 0
[seed] 유녀전기 12화 0
[seed] 유녀전기 13화 0
[seed] 유녀전기 13-2화 0
[seed] 유녀전기 14화 0
[seed] 유녀전기 15화 0
[seed] 유녀전기 16화 0
[seed] 유녀전기 17화 0
[seed] 유녀전기 18화 0
[seed] 유녀전기 19화 0
[seed] 유녀전기 20화 0
[seed] 유녀전기 21화 0
[seed] 유녀전기 22화 0
[seed] 유녀전기 23화 0
[seed] 유녀전기 24화 0
[seed] 유녀전기 스핀오프1화 0
[seed] 유녀전기 특별편 0
[seed] 유녀전기 25화 0
[seed] 유녀전기 25-2화 0
[seed] 유녀전기 25.5화 0
[seed] 유녀전기 26-1화 0
[seed] 유녀전기 26-2화 0
[seed] 유녀전기 27화 0
[seed] 유녀전기 27-2화 0
[seed] 유녀전기 28화 0
[seed] 유녀전기 29화 0
[seed] 유녀전기 29-2화 0
[seed] 유녀전기 30화 0
[seed] 유녀전기 30-2화 0
[seed] 유녀전기 31화 0
[seed] 유녀전기 31-2화 0
[seed] 유녀전기 32화 0
[seed] 유녀전기 33화 0
[seed] 유녀전기 34화 0
[seed] 유녀전기 35화 0
[seed] 유녀전기 35-2화 0
[seed] 유녀전기 36화 0
[seed] 유녀전기 37화 0
[seed] 유녀전기 37-2화 0
[seed] 유녀전기 38화 0
[seed] 유녀전기 38-2화 83830
[seed] 유녀전기 38-2화 83830
[seed] 유녀전기 38-2화 83830
[seed] 유녀전기 38-2화 83830
[seed] 유녀전기 38-2화 83830
[seed] 유녀전기 38-2화 83830
[seed] 유녀전기 38-2화 83830
[seed] 유녀전기 38-2화 83830
fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "manamoa_downloader", line 266, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=2691): Read timed out. (read timeout=<object object at 0x00C48488>)

stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "manamoa_downloader", line 137, in read
File "manamoa_downloader", line 241, in get_imgs
File "constants", line 633, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "manamoa_downloader", line 266, in get_imgs_page
File "capture", line 34, in capture
File "phantomjs", line 97, in get
File "FUCK(5)\remote\webdriver", line 201, in get
File "FUCK(5)\remote\webdriver", line 192, in execute
File "FUCK(5)\remote\remote_connection", line 210, in execute
File "FUCK(5)\remote\remote_connection", line 224, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host=u'127.0.0.1', port=2691): Read timed out. (read timeout=<object object at 0x00C48488>)

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=4291
`

**Comment by KurtBestor** [comment]
다시 시도해도 안 되나요?

**Comment by korhentai** [comment]
네 같은오류가 나는 상황이고요 몇몇 타이틀에서 나타납니다. 

 fuckkk 이라고 나오는 저 오류라인은 adblock 인가 다운로더 쓸때 마나모아에서 보였던거같은 메세지였던거같은데 맞나요 ? 

제가 설정을 바꿔가면서 테스트해보겠습니다.

**Comment by KurtBestor** [comment]
adblock 다운로더가 뭔가요?

**Comment by korhentai** [comment]
에드블럭 다운로더가 아니고요 애드블럭 쓰면 애드블럭 차단스크립트였나가 저런 스트링이 있었던거같은데... 아니면 다른 다운로더를 썼을때 저런 문자열이 나왔던지요

**Comment by KurtBestor** [comment]
이 창이 떴을 때 <kbd>액세스 허용(A)</kbd> 누르셨나요?:
![image](https://user-images.githubusercontent.com/14768120/69902251-8ee84980-13ce-11ea-9ca5-71908cc8d666.png)

**Comment by korhentai** [comment]
네 다른사이트는 정상적으로 받아지고요 
마나모아에서 그럽니다.

**Comment by KurtBestor** [comment]
제 쪽에선 재현할 수 없네요.
