### ISSUE TITLE
soundcloud 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by dlehdrjs0606** [KurtBestor/Hitomi-Downloader-issues#1424]
최근에 마나모아용 test gui를 받았는데
잘되던 soundcloud 다운로드가 안됩니다.
Tido Kang - 07 흩날리는 벚꽃 - Tido Kang

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://soundcloud.com/tido-kang/07-tido-kang
dir: hitomi_downloaded_soundcloud
zip: 
type: soundcloud
artist: Tido Kang
url: https://soundcloud.com/tido-kang/07-tido-kang
valid: True
done: False
range: None
range_p: None
single: True
time: 1574745936.07 (Nov 26)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3

[URLs]
[0001] LazyUrl(https://soundcloud.com/tido-kang/07-tido-kang)

[Messages]

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0

Fail : \\?\C:\Users\dlehd\Desktop\hitomi_downloader_GUI_test\hitomi_downloaded_soundcloud\Tido Kang - 07 흩날리는 벚꽃 - Tido Kang.mp3
Traceback (most recent call last):
File "downloader", line 877, in download
IOError: Size is 0
원래 걸 다시 받아도 안되네요.
머지

**Comment by dlehdrjs0606** [comment]
IOerror : size is 0이라고...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by dlehdrjs0606** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

음 이번에는 invalid라고 나오는데..
Invalid: [soundcloud] https://soundcloud.com / sakuzyo / cytus-chapter-m-xi-vs-sakuzyo-storia

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://soundcloud.com/sakuzyo/cytus-chapter-m-xi-vs-sakuzyo-storia
dir: 
zip: 
type: soundcloud
artist: None
url: https://soundcloud.com/sakuzyo/cytus-chapter-m-xi-vs-sakuzyo-storia
valid: False
done: True
range: None
range_p: None
single: True
time: 1574773766.22 (Nov 26)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "soundcloud_downloader", line 130, in get_audios
File "soundcloud_downloader", line 156, in foo
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
File "soundcloud_downloader", line 106, in get_audios
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

No JSON object could be decoded
stop
Traceback (most recent call last):
File "utils", line 798, in start
File "utils", line 845, in start_
File "soundcloud_downloader", line 59, in read
File "soundcloud_downloader", line 141, in get_audios
ValueError: No JSON object could be decoded

Invalid: fail=True
EOT: https://soundcloud.com/sakuzyo/cytus-chapter-m-xi-vs-sakuzyo-storia

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
