### ISSUE TITLE
히요비에서 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by Romount** [KurtBestor/Hitomi-Downloader-issues#1426]
자동으로 설정시 히토미로 받아지고 수동으로 히요비에서 받으려고 하면 info.txt.만 받아지고 완료가 뜨네요.

Safevisit쓰는데 웹으로는 잘 들어가집니다.

혹시나해서 Safevisit 종료하고 히토미다운로더 내장dpi켜고 해봐도 동일하네요.

히토미.asia나 다른 이슈글에서 언급하신 with open('test_hiyobi.txt', 'w') as f: f.write(downloader.read_html('https://xn--9w3b15m8vo.asia/info/1467714').encode('utf8'))
이걸로도 접근이 안되구요 주소부분만 크롬으로 들어가도 접속안되요. hiyobi.me 주소만 되네요.

```
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]

with open('test_hiyobi.txt', 'w') as f: f.write(downloader.read_html('https://xn--9w3b15m8vo.asia/info/1467714').encode('utf8')) 

Traceback (most recent call last):
  File "downloader", line 278, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 305, in connect
  File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0F663510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

    Traceback (most recent call last):
      File "console\Console.pyo", line 157, in execSingle
      File "<string>", line 1, in <module>
      File "downloader.pyo", line 278, in read_html
      File "urllib3\poolmanager.pyo", line 326, in urlopen
      File "urllib3\connectionpool.pyo", line 641, in urlopen
      File "urllib3\util\retry.pyo", line 344, in increment
      File "urllib3\connectionpool.pyo", line 603, in urlopen
      File "urllib3\connectionpool.pyo", line 344, in _make_request
      File "urllib3\connectionpool.pyo", line 843, in _validate_conn
      File "urllib3\connection.pyo", line 305, in connect
      File "urllib3\connection.pyo", line 169, in _new_conn
    NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0F663510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1358

**Comment by Romount** [comment]
1358에 링크하신 프리뷰 버전으로 잘 동작하네요
