### ISSUE TITLE
히요비 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by DBGJ-Cat** [KurtBestor/Hitomi-Downloader-issues#1432]
다른 것들은 잘되는데 이것만 Invaild 뜨면서 안되네요

주소 : https://hiyobi.me/reader/10000036#1-

정보
Invalid: [hitomi] https://hiyobi.me / reader / 10000036

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://hiyobi.me/reader/10000036
dir: 
zip: 
type: hiyobi
artist: None
url: https://hiyobi.me/reader/10000036
valid: False
done: True
range: None
range_p: None
single: False
time: 1575030194.84 (Nov 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2809D050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2D6CF850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hiyobi.me/reader/10000036)
Find_ehen(id:10000036, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1ED0A2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hiyobi.me/reader/10000036)
Find_ehen(id:10000036, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2809DD30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hiyobi.me/reader/10000036)
Find_ehen(id:10000036, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x241157D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hiyobi.me/reader/10000036)
Find_ehen(id:10000036, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x24115170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:False, url:https://hiyobi.me/reader/10000036)
Find_ehen(id:10000036, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2809D7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:True, url:https://hiyobi.me/reader/10000036)
Find_ehen(id:10000036, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 683, in read
File "gallery", line 224, in get_gal
Exception: get_gal Invalid server: auto

stop
Invalid: fail=False
stop
EOT: https://hiyobi.me/reader/10000036

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1358

**Comment by DBGJ-Cat** [comment]
알려주신 방법으로 해결했습니다. 감사합니다.
