### ISSUE TITLE
히요비를 통한 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by korm2cg** [KurtBestor/Hitomi-Downloader-issues#1459]
얼마 전부터 서버를 히요비로 설정하거나, 히요비에만 있는 작품을 다운로드 하는 것이 불가능해졌습니다.

오류 내용은 다음과 같습니다.

Invalid: [hitomi] https://히요비.asia / reader / 10000092

version: 2.7d
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://히요비.asia/reader/10000092
dir: 
zip: 
type: hiyobi
artist: None
url: https://히요비.asia/reader/10000092
valid: False
done: True
range: None
range_p: None
single: False
time: 1575689987.31 (Dec 7)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F5C3E50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1BF94330>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F5E85F0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://히요비.asia/reader/10000092)
Find_ehen(id:10000092, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F5C3B30>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://히요비.asia/reader/10000092)
Find_ehen(id:10000092, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F5C3F50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://히요비.asia/reader/10000092)
Find_ehen(id:10000092, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1ECB3B30>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://히요비.asia/reader/10000092)
Find_ehen(id:10000092, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F5B7AB0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:False, url:https://히요비.asia/reader/10000092)
Find_ehen(id:10000092, ex:False)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F5B7ED0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: ehen
ehen_imgs(ex:True, url:https://히요비.asia/reader/10000092)
Find_ehen(id:10000092, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 529, in get_imgs
File "hitomi_downloader", line 954, in ehen_imgs
File "hitomi_downloader", line 881, in find_ehen
Exception: out of range

FINAL SERVER: auto
ehen_url: None
imgs: 0
Traceback (most recent call last):
File "hitomi_downloader", line 683, in read
File "gallery", line 224, in get_gal
Exception: get_gal Invalid server: auto

stop
Invalid: fail=False
stop
EOT: https://히요비.asia/reader/10000092

**Comment by korm2cg** [comment]
해결되었습니다.

Technical Preview 에 있는 시험버전으로 실행파일을 교체하니 다운로드가 정상적으로 작동합니다 :)
