### ISSUE TITLE
마나모아 다운로드 에러 문의

### ISSUE THREAD

**Issue by amouu76** [KurtBestor/Hitomi-Downloader-issues#1461]
바람의 검심, 사채꾼 우시지마 등 마나모아에서 03-26일에 
올라왔던 오래된 자료 중 일부가 다운되지 않습니다.
마나모아 사이트에서 직접 보는건 가능한 상태입니다
혹시 수정이 가능하신지 부탁드립니다
관련 로그 첨부합니다.

[와츠키 노부히로] 바람의 검심

version: 2.7d
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087
dir: D:\Comics\01 New\[와츠키 노부히로] 바람의 검심
zip: 
type: manamoa
artist: 와츠키 노부히로
url: https://manamoa21.net/bbs/page.php?hid=manga_detail&manga_id=657
valid: False
done: True
range: None
range_p: None
single: False
time: 1575738474.51 (Dec 8)
tags: []
goodbyedpi: False
lock: False
color: invalid_done
paused: False

[Gallery]
None

[File Names]
[0001] D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0000.jpg
[0002] D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0001.jpg
[0003] D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0002.jpg
[0004] D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0003.jpg
[0005] D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0004.jpg
[0006] D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0005.jpg
[0007] D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg

[URLs]
[0001] LazyUrl(https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087) ---> https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg
[0002] LazyUrl(https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087) ---> https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg
[0003] LazyUrl(https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087) ---> https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg
[0004] LazyUrl(https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087) ---> https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg
[0005] LazyUrl(https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087) ---> https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg
[0006] LazyUrl(https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087) ---> https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg
[0007] LazyUrl(https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087) ---> https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg

[Messages]
redirect: https://manamoa21.net/bbs/page.php?hid=manga_detail&manga_id=657
dirFormat: [artist] title
[seed] 바람의 검심 260화 0

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0000.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg --> https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0004.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg --> https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg --> https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0002.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg --> https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0001.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg --> https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0003.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg --> https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0005.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg --> https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0000.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg --> https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0004.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg --> https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0002.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg --> https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg --> https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0001.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg --> https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0003.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg --> https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0005.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg --> https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0004.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0000.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0002.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0001.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0003.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0005.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

valid=False 1
EOT: https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087

redirect: https://manamoa21.net/bbs/page.php?hid=manga_detail&manga_id=657
dirFormat: [artist] title
[seed] 바람의 검심 260화 0

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0000.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg --> https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0001.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg --> https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg --> https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0005.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg --> https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0003.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg --> https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0004.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg --> https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0002.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg --> https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0000.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg --> https://cdnwowmax.xyz/upload3/79ca66c7cbc5bdb9443b3016be21a1aa.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0001.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg --> https://cdnwowmax.xyz/upload3/040747ba82113e5e3144f6e8703c16e5.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0003.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg --> https://cdnwowmax.xyz/upload3/703fda79dd74bd47f69bbd4055302e2b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0005.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg --> https://cdnwowmax.xyz/upload3/d477345cf1f3b661568e2bbb11e5dfef.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0004.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg --> https://cdnwowmax.xyz/upload3/df05a3c547190bedd10ec894573bb10b.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0002.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg --> https://cdnwowmax.xyz/upload3/84dc9b1e5438aa99ce117d95a4b2239f.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0000.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0001.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg
Traceback (most recent call last):
File "downloader", line 756, in download
Exception: 403

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0005.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0003.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0004.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0002.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg --> https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

use alternative url: https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg --> https://cdnwowmax.xyz/upload3/95e027fe703f04acfc7e4ee11d83c1c9.jpg

Fail : \\?\D:\Comics\01 New\[와츠키 노부히로] 바람의 검심\바람의 검심 260화\0006.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

valid=False 1
EOT: https://manamoa21.net/bbs/board.php?bo_table=manga&wr_id=311087

**Comment by amouu76** [comment]
아래에 있는 답변 중에 hitomi_downloader_GUI_test 가 있길래
다운받아서 해보니 테스트 버전에서는 다운 잘 됩니다.
감사합니다.
혹시 2.7d 버전에도 반영이 가능할까요?

**Comment by KurtBestor** [comment]
실행파일 교체하시면 돼요.

**Comment by amouu76** [comment]
> 실행파일 교체하시면 돼요.

실행 잘 됩니다.
항상 감사합니다.
수고하세요
