### ISSUE TITLE
마나모아 일부 페이지가 다운로드 안 되는 오류

### ISSUE THREAD

**Issue by EDD1802** [KurtBestor/Hitomi-Downloader-issues#1468]
Fail : \\?\C:\Users\EOP\Downloads\hitomi_downloader_GUI\hitomi_downloaded_manamoa\[치다 다이스케] 비정상인의 사랑\비정상인의 사랑 34,35화\0003.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Fail : \\?\C:\Users\EOP\Downloads\hitomi_downloader_GUI\hitomi_downloaded_manamoa\[N／A] 사랑하는 기생충\사랑하는 기생충 5화\0002.jpg
Traceback (most recent call last):
File "downloader", line 719, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

--

안녕하세요. 프로그램 언제나 잘 이용하고 있습니다. 
다른게 아니라 마나모아에서 전체 다운로드를 할 때 일부 화들이 다운로드 안 되는 경우가 있어서 문의 드립니다. 한 두화씩 저런 식으로 오류가 나면서 다운로드가 진행이 안 되는데 해결 방안이 있을까요??

**Comment by EDD1802** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
아 여기서 이 실행파일로 교체해보니 잘 되는군요. 감사합니다.
