### ISSUE TITLE
마리망 크롬 버전업 안 된건가요?

### ISSUE THREAD

**Issue by azzxxa** [KurtBestor/Hitomi-Downloader-issues#1477]
[Messages]
cf protection
stop
Traceback (most recent call last):
File "utils", line 642, in __init__
File "mrm_downloader", line 44, in init
File "mrm_downloader", line 193, in get_session
File "constants", line 633, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "clf", line 14, in wait
File "chrome", line 154, in start
File "chrome", line 80, in __init__
File "FUCK(5)\chrome\webdriver", line 28, in __init__
File "FUCK(5)\remote\webdriver", line 83, in __init__
File "FUCK(5)\remote\webdriver", line 138, in start_session
File "FUCK(5)\remote\webdriver", line 194, in execute
File "FUCK(5)\remote\errorhandler", line 183, in check_response
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 76

안 되네요 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by azzxxa** [comment]
잘 됩니다. 감사합니다.
