### ISSUE TITLE
youtube와 pixiv 다운로드 안됨

### ISSUE THREAD

**Issue by 12344353** [KurtBestor/Hitomi-Downloader-issues#149]
![image](https://user-images.githubusercontent.com/40817956/42403910-c9533050-81bf-11e8-95fc-bf6baa33e0da.png)
위와 같이 뜨면서, 유투브랑 픽시브가 다운로드 되질 않습니다.

**Comment by 12344353** [comment]
유투브는 

Fail: youtube_youtube_7Sf2E3U8EnA

gal_num: youtube_7Sf2E3U8EnA
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=7Sf2E3U8EnA
valid: False
done: False
range: None
range_p: None
single: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 1746, in download_hitomi
File "hitomi_downloader", line 914, in download_youtube
File "youtube_downloader", line 84, in get_videos
File "FUUUUCK\__main__", line 83, in __init__
File "FUUUUCK\__main__", line 91, in prefetch_init
File "FUUUUCK\__main__", line 148, in prefetch
File "FUUUUCK\request", line 21, in get
File "urllib2", line 154, in urlopen
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1241, in https_open
File "urllib2", line 1198, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Fail: youtube

done : youtube_7Sf2E3U8EnA



픽시브는

Fail: youtube_youtube_7Sf2E3U8EnA

gal_num: youtube_7Sf2E3U8EnA
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=7Sf2E3U8EnA
valid: False
done: False
range: None
range_p: None
single: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 1746, in download_hitomi
File "hitomi_downloader", line 914, in download_youtube
File "youtube_downloader", line 84, in get_videos
File "FUUUUCK\__main__", line 83, in __init__
File "FUUUUCK\__main__", line 91, in prefetch_init
File "FUUUUCK\__main__", line 148, in prefetch
File "FUUUUCK\request", line 21, in get
File "urllib2", line 154, in urlopen
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1241, in https_open
File "urllib2", line 1198, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Fail: youtube

done : youtube_7Sf2E3U8EnA


이렇게 뜨네요,,,

**Comment by KurtBestor** [comment]
둘 다 유튜브인데 잘못 적으신 것 같아요. 픽시브 쪽만 다시 적어주실 수 있나요?

**Comment by 12344353** [comment]
아 그렇네요


픽시브는

Error L: pixiv_https://www.pixiv.net / member_illust.php?id=341433

[u'Traceback (most recent call last):\n File "pixiv_downloader", line 60, in init\n File "pixiv_downloader", line 271, in get_api\nPixivError: requests POST https://oauth.secure.pixiv.net / auth / token error: \nTraceback (most recent call last):\n File "pixivpy3\\api", line 62, in requests_call\n File "requests\\api", line 29, in post\n File "requests\\api", line 10, in request\n File "downloader", line 44, in session_request\n File "requests\\sessions", line 225, in request\n File "requests\\sessions", line 264, in send\n File "requests\\adapters", line 244, in send\nProxyError: HTTPSConnectionPool(host=\'oauth.secure.pixiv.net\', port=443): Max retries exceeded with url: / auth / token (Caused by ProxyError(\'Cannot connect to proxy.\', NewConnectionError(\'<urllib3.connection.VerifiedHTTPSConnection object at 0x2841B990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\',)))\n\n']

gal_num: pixiv_341433
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member_illust.php?id=341433
valid: False
done: False
range: None
range_p: None
single: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
stop
Traceback (most recent call last):
File "pixiv_downloader", line 60, in init
File "pixiv_downloader", line 271, in get_api
PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: 
Traceback (most recent call last):
File "pixivpy3\api", line 62, in requests_call
File "requests\api", line 29, in post
File "requests\api", line 10, in request
File "downloader", line 44, in session_request
File "requests\sessions", line 225, in request
File "requests\sessions", line 264, in send
File "requests\adapters", line 244, in send
ProxyError: HTTPSConnectionPool(host='oauth.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2841B990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))


Fail: pixiv

stop
done : pixiv_341433

이렇게 뜹니다

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by 12344353** [comment]
유투브는 제대로 작동합니다.


픽시브는

Error L: pixiv_https://www.pixiv.net / member_illust.php?id=341433

[u'Traceback (most recent call last):\n File "pixiv_downloader", line 60, in init\n File "pixiv_downloader", line 271, in get_api\nPixivError: requests POST https://oauth.secure.pixiv.net / auth / token error: \nTraceback (most recent call last):\n File "pixivpy3\\api", line 62, in requests_call\n File "requests\\api", line 29, in post\n File "requests\\api", line 10, in request\n File "downloader", line 44, in session_request\n File "requests\\sessions", line 225, in request\n File "requests\\sessions", line 264, in send\n File "requests\\adapters", line 244, in send\nProxyError: HTTPSConnectionPool(host=\'oauth.secure.pixiv.net\', port=443): Max retries exceeded with url: / auth / token (Caused by ProxyError(\'Cannot connect to proxy.\', NewConnectionError(\'<urllib3.connection.VerifiedHTTPSConnection object at 0x2305A1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\',)))\n\n']

gal_num: pixiv_341433
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member_illust.php?id=341433
valid: False
done: False
range: None
range_p: None
single: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
stop
Traceback (most recent call last):
File "pixiv_downloader", line 60, in init
File "pixiv_downloader", line 271, in get_api
PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: 
Traceback (most recent call last):
File "pixivpy3\api", line 62, in requests_call
File "requests\api", line 29, in post
File "requests\api", line 10, in request
File "downloader", line 44, in session_request
File "requests\sessions", line 225, in request
File "requests\sessions", line 264, in send
File "requests\adapters", line 244, in send
ProxyError: HTTPSConnectionPool(host='oauth.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2305A1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))


Fail: pixiv

stop
done : pixiv_341433


여전히 이렇게 뜨면서 똑같이 안되네요...

**Comment by KurtBestor** [comment]
Ctrl + Alt + C 눌러서 콘솔 열고
```
downloader.requests.utils.get_environ_proxies('https://pixiv.net')
```
위 명령어를 입력하고 Enter 누른 다음 나오는 내용 알려주세요.

**Comment by 12344353** [comment]
{'ftp': 'ftp:// ', 'http': 'http:// ', 'https': 'https:// '}

이렇게 나오네요

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by 12344353** [comment]
Error L: pixiv_https://www.pixiv.net / member_illust.php?id=15305293

[u'Traceback (most recent call last):\n File "pixiv_downloader", line 60, in init\n File "pixiv_downloader", line 271, in get_api\nPixivError: requests POST https://oauth.secure.pixiv.net / auth / token error: \nTraceback (most recent call last):\n File "pixivpy3\\api", line 69, in requests_call\n File "requests\\api", line 112, in post\n File "requests\\api", line 58, in request\n File "downloader", line 50, in session_request\n File "requests\\sessions", line 503, in request\n File "requests\\sessions", line 676, in merge_environment_settings\n File "requests\\utils", line 760, in get_environ_proxies\n File "requests\\utils", line 744, in should_bypass_proxies\n File "requests\\utils", line 93, in proxy_bypass\n File "requests\\utils", line 59, in proxy_bypass_registry\nValueError: invalid literal for int() with base 10: \'\'\n\n']

gal_num: pixiv_15305293
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member_illust.php?id=15305293
valid: False
done: False
range: None
range_p: None
single: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: user
stop
Traceback (most recent call last):
File "pixiv_downloader", line 60, in init
File "pixiv_downloader", line 271, in get_api
PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: 
Traceback (most recent call last):
File "pixivpy3\api", line 69, in requests_call
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 50, in session_request
File "requests\sessions", line 503, in request
File "requests\sessions", line 676, in merge_environment_settings
File "requests\utils", line 760, in get_environ_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''


Fail: pixiv

stop
done : pixiv_15305293



이번엔 이렇게 뜨면서 여전히 픽시브 다운로드가 안됩니다 ㅠㅠ

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.
