### ISSUE TITLE
익헨 다운이 되질 않습니다 (무한로딩)

### ISSUE THREAD

**Issue by alseomo** [KurtBestor/Hitomi-Downloader-issues#1517]
어제부터인가 히토미에 있는 작품들은 다운이 잘 되는데

익헨에만 있는 자료들 ( 논엣지나 기타 작품들 ) 은 로딩만 무한히 하면서 다운이 안되네요 

그중 하나 로그 첨부해드립니다

[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)

version: 2.7d
platform: Windows-10-10.0.18362
order: 47
group: False
gal_num: https://e-hentai.org/g/1542105/a233366df0
dir: D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)
zip: 
type: ehen
artist: N／A
url: https://e-hentai.org/g/1542105/a233366df0
valid: True
done: False
range: None
range_p: None
single: False
time: 1577706782.06 (Dec 30)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: True

[Gallery]
갤러리 넘버: 1542105

제목: (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai

작가: N/A

그룹: N/A

타입: non-h

시리즈: N/A

캐릭터: N/A

태그: artbook, full color, female:schoolgirl uniform, female:stockings

언어: N／A

[File Names]
[0001] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-1
[0002] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-2
[0003] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-3
[0004] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-4
[0005] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-5
[0006] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-6
[0007] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-7
[0008] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-8
[0009] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-9
[0010] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-10
[0011] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-11
[0012] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-12
[0013] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-13
[0014] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-14
[0015] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-15
[0016] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-16
[0017] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-17
[0018] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-18
[0019] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-19
[0020] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-20
[0021] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-21
[0022] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-22
[0023] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-23
[0024] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-24
[0025] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-25
[0026] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-26
[0027] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-27
[0028] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-28
[0029] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-29
[0030] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-30
[0031] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-31
[0032] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-32
[0033] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-33
[0034] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-34
[0035] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-35
[0036] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-36
[0037] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-37
[0038] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-38
[0039] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-39
[0040] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-40
[0041] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-41
[0042] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-42
[0043] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-43
[0044] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-44
[0045] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-45
[0046] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-46
[0047] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-47
[0048] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-48
[0049] D:\hitomi_downloaded\[N／A] (C97) [Melonbooks (Various)] Melonbooks Girls Collection 2019 winter Sai (1542105)\1542105-49

[URLs]
[0001] https://e-hentai.org/s/b02f50ec11/1542105-1 ---> https://ehgt.org/g/509.gif
[0002] https://e-hentai.org/s/c0fa4dc63e/1542105-2 ---> https://ehgt.org/g/509.gif
[0003] https://e-hentai.org/s/973685a684/1542105-3
[0004] https://e-hentai.org/s/127d5ffa5d/1542105-4
[0005] https://e-hentai.org/s/c70bec9046/1542105-5
[0006] https://e-hentai.org/s/95f275fe22/1542105-6
[0007] https://e-hentai.org/s/c8155b21d1/1542105-7
[0008] https://e-hentai.org/s/c532e7f05d/1542105-8
[0009] https://e-hentai.org/s/fa4200b4f9/1542105-9
[0010] https://e-hentai.org/s/dbce412bfd/1542105-10
[0011] https://e-hentai.org/s/03e9438e8f/1542105-11
[0012] https://e-hentai.org/s/fa83fe6c25/1542105-12
[0013] https://e-hentai.org/s/789575658a/1542105-13
[0014] https://e-hentai.org/s/ac2f0a60cc/1542105-14
[0015] https://e-hentai.org/s/961d418a87/1542105-15
[0016] https://e-hentai.org/s/f998a5b37b/1542105-16
[0017] https://e-hentai.org/s/c5f3ef6d57/1542105-17
[0018] https://e-hentai.org/s/a6d3287284/1542105-18
[0019] https://e-hentai.org/s/e1df5acc01/1542105-19
[0020] https://e-hentai.org/s/5900ae30e3/1542105-20
[0021] https://e-hentai.org/s/d943dfd5a8/1542105-21
[0022] https://e-hentai.org/s/0e9280db1e/1542105-22
[0023] https://e-hentai.org/s/51ac8ec227/1542105-23
[0024] https://e-hentai.org/s/1d891f3f6d/1542105-24
[0025] https://e-hentai.org/s/857c8c9960/1542105-25
[0026] https://e-hentai.org/s/c7656014d7/1542105-26
[0027] https://e-hentai.org/s/a4cbe156d5/1542105-27
[0028] https://e-hentai.org/s/5ef450da6d/1542105-28
[0029] https://e-hentai.org/s/2c7646a5f2/1542105-29
[0030] https://e-hentai.org/s/50e0e8aa86/1542105-30
[0031] https://e-hentai.org/s/3b415415f9/1542105-31
[0032] https://e-hentai.org/s/cab4970ab1/1542105-32
[0033] https://e-hentai.org/s/0ea88f6ea4/1542105-33
[0034] https://e-hentai.org/s/0b267bb30f/1542105-34
[0035] https://e-hentai.org/s/69889a86ce/1542105-35
[0036] https://e-hentai.org/s/7e66ffeec3/1542105-36
[0037] https://e-hentai.org/s/a8186fb8e0/1542105-37
[0038] https://e-hentai.org/s/d330dfe195/1542105-38
[0039] https://e-hentai.org/s/9bdbaf9f3c/1542105-39
[0040] https://e-hentai.org/s/ffe73a1f36/1542105-40
[0041] https://e-hentai.org/s/f64e751978/1542105-41
[0042] https://e-hentai.org/s/3fa3555e8d/1542105-42
[0043] https://e-hentai.org/s/0c74e830af/1542105-43
[0044] https://e-hentai.org/s/c0e19f77a9/1542105-44
[0045] https://e-hentai.org/s/c5b83ef69f/1542105-45
[0046] https://e-hentai.org/s/097a756a01/1542105-46
[0047] https://e-hentai.org/s/88e6ca3d36/1542105-47
[0048] https://e-hentai.org/s/b82620ca15/1542105-48
[0049] https://e-hentai.org/s/3373997bea/1542105-49

[Messages]
get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x08AA77F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: hitomi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 519, in get_imgs
File "hitomi", line 41, in pop_img
File "downloader", line 291, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 637, in read
File "hitomi_downloader", line 527, in get_imgs
File "hiyobi_downloader", line 20, in pop_img_hiyobi
File "downloader", line 278, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1F920D70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

get_imgs server: ehen
ehen_imgs(ex:False, url:https://e-hentai.org/g/1542105/a233366df0)
#### https://e-hentai.org/g/1542105/a233366df0 ----> https://e-hentai.org/g/1542105/a233366df0/?p=1
FINAL SERVER: ehen
ehen_url: https://e-hentai.org/g/1542105/a233366df0
imgs: 49
get_title_ehen: https://e-hentai.org/g/1542105/a233366df0
E-Hentai: https://e-hentai.org/g/1542105/a233366df0

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

Retry ehen...https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

Retry ehen...https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

Retry ehen...https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

Retry ehen...https://e-hentai.org/s/b02f50ec11/1542105-1
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

Retry ehen...https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 42, in get_img
Exception: 509.gif

Retry ehen...https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

Retry ehen...https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

ehen retry... https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "ehen_downloader", line 20, in get_img
File "downloader", line 219, in read_html
Exception: customWidget paused

Retry ehen...https://e-hentai.org/s/c0fa4dc63e/1542105-2
Traceback (most recent call last):
File "hitomi_downloader", line 250, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

EOT: https://e-hentai.org/g/1542105/a233366df0

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1407

**Comment by alseomo** [comment]
![image](https://user-images.githubusercontent.com/59363485/71637669-1524d380-2c8c-11ea-90dc-27d7a8745af8.png)
Image Limits
Nothing to reset.

You are currently at 0 towards a limit of 25000. This regenerates at a rate of 5 per minute.

Reset Cost: 0 GP

입니다 ㅜㅜ

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by alseomo** [comment]
네 ㅜㅜ

**Comment by alseomo** [comment]
아무래도 제 인터넷이나 익헨설정문제겠죠?
