### ISSUE TITLE
유튜브 다운로드 실패

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader-issues#1608]
유튜브 다운로드가 되지 않습니다

https://youtu.be/RKLKDJ1QsLs
https://youtu.be/xRbPAVnqtcs

작업정보 1

Invalid: [youtube] https://youtu.be / RKLKDJ1QsLs

version: 2.7h
platform: Windows-10-10.0.17763
order: 2
group: False
gal_num: https://youtu.be/RKLKDJ1QsLs
dir: 
zip: 
type: youtube
artist: None
url: https://youtu.be/RKLKDJ1QsLs
valid: False
done: True
range: None
range_p: None
single: True
time: 1579958324.01 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "youtube_downloader", line 142, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "youtube_downloader", line 296, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
File "youtube_dl\extractor\youtube", line 1380, in _decrypt_signature
File "youtube_dl\extractor\youtube", line 1293, in _extract_signature_function
File "youtube_dl\extractor\youtube", line 1356, in <lambda>
File "youtube_dl\jsinterp", line 258, in resf
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 92, in interpret_expression
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 189, in interpret_expression
File "youtube_dl\jsinterp", line 56, in interpret_statement
File "youtube_dl\jsinterp", line 211, in interpret_expression
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Invalid: fail=True
EOT: https://youtu.be/RKLKDJ1QsLs

**Comment by KurtBestor** [comment]
참고해주세요: #1604
