### ISSUE TITLE
마나모아 다운 오류

### ISSUE THREAD

**Issue by dlehdrjs0606** [KurtBestor/Hitomi-Downloader-issues#1664]
use alternative url: https://drive.google.com/uc?export=view&id=1gbg2E3BIz4nrRjSIzZ4huAdo-8R8bwje --> http://img.filecdn.xyz/upload/cf17cea0ef507bba1d37480a92b0b4c5.jpg
use alternative url: http://s3.filecdn.xyz/upload/6cf748b40831550c4580692fd41f0664.jpg --> https://drive.google.com/uc?export=view&id=1XAgzdR2nyPDUWXC3l1L1D-huxRFedSvV

Fail : \\?\C:\Users\dlehd\Downloads\hitomi_downloaded_manamoa\[하루바 네기] 5등분의 신부\5등분의 신부 57화\0017.jpg
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403

Fail : \\?\C:\Users\dlehd\Downloads\hitomi_downloaded_manamoa\[하루바 네기] 5등분의 신부\5등분의 신부 57화\0018.jpg
Traceback (most recent call last):
File "downloader", line 779, in download
Exception: 403
오류의 일부를 따왔습니다
일부분의 파일이 누락되는데 왜 그럴까요

**Comment by dlehdrjs0606** [comment]
해결됐습니다
