### ISSUE TITLE
갑자기 픽시브 다운 안돼얌... 낮에만 해도 됐는데

### ISSUE THREAD

**Issue by marumar** [KurtBestor/Hitomi-Downloader-issues#167]
https://www.pixiv.net/member_illust.php?id=21995968

id=2222&illust 라고 해도 됐었고 개떡같이 인식했는데

지금은 http https 뭐 바꿔봐도 안돼고 힝...

**Comment by KurtBestor** [comment]
해당 작업 마우스 우클릭 후 [정보...] 눌러서 나오는 내용 알려주시면 분석해볼게요.

**Comment by marumar** [comment]
Error L: pixiv_https://www.pixiv.net / member.php?id=1709432

[u'Traceback (most recent call last):\n File "pixiv_downloader", line 60, in init\n File "pixiv_downloader", line 271, in get_api\nPixivError: requests POST https://oauth.secure.pixiv.net / auth / token error: \nTraceback (most recent call last):\n File "pixivpy3\\api", line 62, in requests_call\n File "requests\\api", line 29, in post\n File "requests\\api", line 10, in request\n File "downloader", line 44, in session_request\n File "requests\\sessions", line 225, in request\n File "requests\\sessions", line 264, in send\n File "requests\\adapters", line 244, in send\nProxyError: HTTPSConnectionPool(host=\'oauth.secure.pixiv.net\', port=443): Max retries exceeded with url: / auth / token (Caused by ProxyError(\'Cannot connect to proxy.\', NewConnectionError(\'<urllib3.connection.VerifiedHTTPSConnection object at 0x070E0890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\',)))\n\n']

gal_num: https://www.pixiv.net/member.php?id=1709432
dir: 
zip: 
type: 
artist: None
url: https://www.pixiv.net/member.php?id=1709432
valid: False
done: False
range: None
range_p: None
single: True


[Gallery]
None


[File Names]



[URLs]

**Comment by marumar** [comment]
みこフライ@1日目東ム-46b (pixiv_19855603)

gal_num: https://www.pixiv.net/member.php?id=19855603
dir: hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/member.php?id=19855603
valid: True
done: True
range: None
range_p: None
single: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\69719466_p0.jpg
[0002] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\69601611_p0.jpg
[0003] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\69365033_p0.jpg
[0004] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\69260175_p0.jpg
[0005] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\69149922_p0.jpg
[0006] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\69056645_p0.jpg
[0007] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\69009433_p0.jpg
[0008] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68934544_p0.jpg
[0009] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68804191_p0.jpg
[0010] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68710322_p0.jpg
[0011] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68667097_p0.jpg
[0012] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68448857_p0.jpg
[0013] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68334439_p0.jpg
[0014] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68245535_p0.jpg
[0015] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68183778_p0.jpg
[0016] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68121321_p0.jpg
[0017] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\68006434_p0.jpg
[0018] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67911581_p0.jpg
[0019] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67893645_p0.jpg
[0020] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67667531_p0.jpg
[0021] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67500644_p0.jpg
[0022] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67308301_p0.jpg
[0023] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67220440_p0.jpg
[0024] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67185864_p0.jpg
[0025] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\67009597_p0.jpg
[0026] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\66784721_p0.jpg
[0027] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\66656754_p0.jpg
[0028] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\66431083_p0.jpg
[0029] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\66314459_p0.jpg
[0030] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\66253645_p0.jpg
[0031] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\66148557_p0.jpg
[0032] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\66053702_p0.jpg
[0033] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65867147_p0.jpg
[0034] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65683411_p0.jpg
[0035] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65650272_p0.jpg
[0036] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65592183_p0.jpg
[0037] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65431395_p0.jpg
[0038] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65325118_p0.jpg
[0039] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65206654_p0.jpg
[0040] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\65028854_p0.jpg
[0041] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64872487_p0.jpg
[0042] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64753868_p0.jpg
[0043] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64649721_p0.jpg
[0044] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64547753_p0.jpg
[0045] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64318721_p0.jpg
[0046] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64260449_p0.jpg
[0047] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64186608_p0.jpg
[0048] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\64015139_p0.jpg
[0049] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63947101_p0.jpg
[0050] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63896942_p0.jpg
[0051] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63787892_p0.jpg
[0052] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63734172_p0.jpg
[0053] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63635731_p0.jpg
[0054] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63578944_p0.jpg
[0055] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63298818_p0.jpg
[0056] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\63144256_p0.jpg
[0057] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62944082_p0.jpg
[0058] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62754921_p0.jpg
[0059] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62717830_p0.jpg
[0060] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62575926_p0.jpg
[0061] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62508456_p0.jpg
[0062] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62418623_p0.jpg
[0063] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62352113_p0.jpg
[0064] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62254668_p0.jpg
[0065] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62137883_p0.jpg
[0066] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62088976_p0.jpg
[0067] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\62044322_p0.jpg
[0068] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61975859_p0.jpg
[0069] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61926150_p0.jpg
[0070] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61858041_p0.jpg
[0071] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61809872_p0.jpg
[0072] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61765408_p0.jpg
[0073] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61636695_p0.jpg
[0074] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61617253_p0.jpg
[0075] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61488916_p0.jpg
[0076] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61454956_p0.jpg
[0077] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61399079_p0.jpg
[0078] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61347687_p0.jpg
[0079] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61315342_p0.jpg
[0080] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61195846_p0.jpg
[0081] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\61011544_p0.jpg
[0082] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60955915_p0.jpg
[0083] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60890160_p0.jpg
[0084] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60801356_p0.jpg
[0085] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60705565_p0.jpg
[0086] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60417958_p0.jpg
[0087] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60375613_p0.jpg
[0088] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60334495_p0.jpg
[0089] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60301898_p0.jpg
[0090] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\60236560_p0.jpg
[0091] hitomi_downloaded_pixiv\みこフライ@1日目東ム-46b (pixiv_19855603)\58819779_p0.jpg


[URLs]
[0001] https://i.pximg.net/img-original/img/2018/07/16/18/56/53/69719466_p0.jpg
[0002] https://i.pximg.net/img-original/img/2018/07/08/21/12/19/69601611_p0.jpg
[0003] https://i.pximg.net/img-original/img/2018/06/23/18/59/58/69365033_p0.jpg
[0004] https://i.pximg.net/img-original/img/2018/06/16/21/15/26/69260175_p0.jpg
[0005] https://i.pximg.net/img-original/img/2018/06/09/21/00/28/69149922_p0.jpg
[0006] https://i.pximg.net/img-original/img/2018/06/03/17/24/10/69056645_p0.jpg
[0007] https://i.pximg.net/img-original/img/2018/05/31/19/59/16/69009433_p0.jpg
[0008] https://i.pximg.net/img-original/img/2018/05/26/22/54/04/68934544_p0.jpg
[0009] https://i.pximg.net/img-original/img/2018/05/18/20/03/09/68804191_p0.jpg
[0010] https://i.pximg.net/img-original/img/2018/05/12/20/19/47/68710322_p0.jpg
[0011] https://i.pximg.net/img-original/img/2018/05/09/21/03/34/68667097_p0.jpg
[0012] https://i.pximg.net/img-original/img/2018/04/28/19/53/33/68448857_p0.jpg
[0013] https://i.pximg.net/img-original/img/2018/04/21/19/42/27/68334439_p0.jpg
[0014] https://i.pximg.net/img-original/img/2018/04/15/19/17/11/68245535_p0.jpg
[0015] https://i.pximg.net/img-original/img/2018/04/11/20/08/37/68183778_p0.jpg
[0016] https://i.pximg.net/img-original/img/2018/04/07/19/55/05/68121321_p0.jpg
[0017] https://i.pximg.net/img-original/img/2018/03/31/20/54/18/68006434_p0.jpg
[0018] https://i.pximg.net/img-original/img/2018/03/25/19/55/09/67911581_p0.jpg
[0019] https://i.pximg.net/img-original/img/2018/03/24/19/57/11/67893645_p0.jpg
[0020] https://i.pximg.net/img-original/img/2018/03/10/20/58/44/67667531_p0.jpg
[0021] https://i.pximg.net/img-original/img/2018/02/28/09/18/55/67500644_p0.jpg
[0022] https://i.pximg.net/img-original/img/2018/02/16/20/44/50/67308301_p0.jpg
[0023] https://i.pximg.net/img-original/img/2018/02/11/20/41/53/67220440_p0.jpg
[0024] https://i.pximg.net/img-original/img/2018/02/09/20/49/00/67185864_p0.jpg
[0025] https://i.pximg.net/img-original/img/2018/01/28/20/21/41/67009597_p0.jpg
[0026] https://i.pximg.net/img-original/img/2018/01/13/20/47/25/66784721_p0.jpg
[0027] https://i.pximg.net/img-original/img/2018/01/05/18/42/33/66656754_p0.jpg
[0028] https://i.pximg.net/img-original/img/2017/12/24/20/58/24/66431083_p0.jpg
[0029] https://i.pximg.net/img-original/img/2017/12/16/20/08/45/66314459_p0.jpg
[0030] https://i.pximg.net/img-original/img/2017/12/11/20/57/26/66253645_p0.jpg
[0031] https://i.pximg.net/img-original/img/2017/12/03/22/15/17/66148557_p0.jpg
[0032] https://i.pximg.net/img-original/img/2017/11/26/20/54/57/66053702_p0.jpg
[0033] https://i.pximg.net/img-original/img/2017/11/12/21/05/04/65867147_p0.jpg
[0034] https://i.pximg.net/img-original/img/2017/10/31/20/11/52/65683411_p0.jpg
[0035] https://i.pximg.net/img-original/img/2017/10/29/20/51/34/65650272_p0.jpg
[0036] https://i.pximg.net/img-original/img/2017/10/25/21/02/04/65592183_p0.jpg
[0037] https://i.pximg.net/img-original/img/2017/10/14/20/53/53/65431395_p0.jpg
[0038] https://i.pximg.net/img-original/img/2017/10/07/21/11/42/65325118_p0.jpg
[0039] https://i.pximg.net/img-original/img/2017/09/30/20/56/16/65206654_p0.jpg
[0040] https://i.pximg.net/img-original/img/2017/09/18/21/05/03/65028854_p0.jpg
[0041] https://i.pximg.net/img-original/img/2017/09/09/21/06/40/64872487_p0.jpg
[0042] https://i.pximg.net/img-original/img/2017/09/02/20/53/38/64753868_p0.jpg
[0043] https://i.pximg.net/img-original/img/2017/08/27/21/31/04/64649721_p0.jpg
[0044] https://i.pximg.net/img-original/img/2017/08/21/20/39/30/64547753_p0.jpg
[0045] https://i.pximg.net/img-original/img/2017/08/09/21/09/50/64318721_p0.jpg
[0046] https://i.pximg.net/img-original/img/2017/08/06/20/50/36/64260449_p0.jpg
[0047] https://i.pximg.net/img-original/img/2017/08/02/20/25/55/64186608_p0.jpg
[0048] https://i.pximg.net/img-original/img/2017/07/23/21/41/53/64015139_p0.jpg
[0049] https://i.pximg.net/img-original/img/2017/07/19/21/00/52/63947101_p0.jpg
[0050] https://i.pximg.net/img-original/img/2017/07/16/20/55/20/63896942_p0.jpg
[0051] https://i.pximg.net/img-original/img/2017/07/09/20/54/39/63787892_p0.jpg
[0052] https://i.pximg.net/img-original/img/2017/07/06/20/55/45/63734172_p0.jpg
[0053] https://i.pximg.net/img-original/img/2017/06/30/20/55/24/63635731_p0.jpg
[0054] https://i.pximg.net/img-original/img/2017/06/26/20/53/23/63578944_p0.jpg
[0055] https://i.pximg.net/img-original/img/2017/06/09/21/12/42/63298818_p0.jpg
[0056] https://i.pximg.net/img-original/img/2017/05/30/20/02/18/63144256_p0.jpg
[0057] https://i.pximg.net/img-original/img/2017/05/17/21/05/27/62944082_p0.jpg
[0058] https://i.pximg.net/img-original/img/2017/05/05/20/58/00/62754921_p0.jpg
[0059] https://i.pximg.net/img-original/img/2017/05/03/20/54/57/62717830_p0.jpg
[0060] https://i.pximg.net/img-original/img/2017/04/25/22/03/57/62575926_p0.jpg
[0061] https://i.pximg.net/img-original/img/2017/04/21/21/02/11/62508456_p0.jpg
[0062] https://i.pximg.net/img-original/img/2017/04/15/20/43/26/62418623_p0.jpg
[0063] https://i.pximg.net/img-original/img/2017/04/10/20/54/19/62352113_p0.jpg
[0064] https://i.pximg.net/img-original/img/2017/04/04/20/47/57/62254668_p0.jpg
[0065] https://i.pximg.net/img-original/img/2017/03/28/21/03/09/62137883_p0.jpg
[0066] https://i.pximg.net/img-original/img/2017/03/25/20/43/12/62088976_p0.jpg
[0067] https://i.pximg.net/img-original/img/2017/03/22/21/09/36/62044322_p0.jpg
[0068] https://i.pximg.net/img-original/img/2017/03/18/20/58/50/61975859_p0.jpg
[0069] https://i.pximg.net/img-original/img/2017/03/15/21/07/52/61926150_p0.jpg
[0070] https://i.pximg.net/img-original/img/2017/03/11/21/06/14/61858041_p0.jpg
[0071] https://i.pximg.net/img-original/img/2017/03/08/21/05/56/61809872_p0.jpg
[0072] https://i.pximg.net/img-original/img/2017/03/05/21/41/37/61765408_p0.jpg
[0073] https://i.pximg.net/img-original/img/2017/02/25/23/23/41/61636695_p0.jpg
[0074] https://i.pximg.net/img-original/img/2017/02/24/21/07/20/61617253_p0.jpg
[0075] https://i.pximg.net/img-original/img/2017/02/16/21/05/07/61488916_p0.jpg
[0076] https://i.pximg.net/img-original/img/2017/02/14/21/00/53/61454956_p0.jpg
[0077] https://i.pximg.net/img-original/img/2017/02/11/20/52/19/61399079_p0.jpg
[0078] https://i.pximg.net/img-original/img/2017/02/08/21/07/03/61347687_p0.jpg
[0079] https://i.pximg.net/img-original/img/2017/02/06/20/39/57/61315342_p0.jpg
[0080] https://i.pximg.net/img-original/img/2017/01/30/22/12/06/61195846_p0.jpg
[0081] https://i.pximg.net/img-original/img/2017/01/19/20/37/11/61011544_p0.jpg
[0082] https://i.pximg.net/img-original/img/2017/01/15/21/43/37/60955915_p0.jpg
[0083] https://i.pximg.net/img-original/img/2017/01/11/19/48/16/60890160_p0.jpg
[0084] https://i.pximg.net/img-original/img/2017/01/06/20/26/46/60801356_p0.jpg
[0085] https://i.pximg.net/img-original/img/2017/01/01/20/43/21/60705565_p0.jpg
[0086] https://i.pximg.net/img-original/img/2016/12/17/21/39/25/60417958_p0.jpg
[0087] https://i.pximg.net/img-original/img/2016/12/14/19/51/20/60375613_p0.jpg
[0088] https://i.pximg.net/img-original/img/2016/12/11/19/26/25/60334495_p0.jpg
[0089] https://i.pximg.net/img-original/img/2016/12/09/18/59/10/60301898_p0.jpg
[0090] https://i.pximg.net/img-original/img/2016/12/04/20/20/32/60236560_p0.jpg
[0091] https://i.pximg.net/img-original/img/2016/09/04/20/55/16/58819779_p0.jpg


[Messages]
[pixmap loaded from str_pixmap] (316, 320) みこフライ@1日目東ム-46b (pixiv_19855603)

**Comment by marumar** [comment]
위에꺼가 다운 안되는거, 아래꺼가 '다운 됐던 것' 이에얌

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by marumar** [comment]
지금보니까 픽시브만 안돼는게 아니라 마루마루고 뭐고 다 안돼네... invalid error

**Comment by KurtBestor** [comment]
Ctrl + Alt + C 눌러서 콘솔 열고
```
downloader.requests.utils.get_environ_proxies('https://pixiv.net')
```
위 명령어를 입력하고 Enter 누른 다음 나오는 내용 알려주세요.

**Comment by marumar** [comment]
Traceback (most recent call last):
      File "console\Console.pyo", line 153, in execSingle
      File "<string>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'get_environ_proxies'

**Comment by marumar** [comment]
downloader.requests.utils.get_environ_proxies('https://pixiv.net') 

{'ftp': 'ftp:// ', 'http': 'http:// ', 'https': 'https:// '}

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by marumar** [comment]
참 프로그래밍 센-세... ㅠㅠ 됐습니더 ㅠ ㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by marumar** [comment]
만약 된다면 픽시브에서 일러스트 / 만화 폴더 구분해서 다운되게 가능해얌?

D:\Pixiv downloader\hitomi_downloaded_pixiv\すいと (pixiv_4910367)
여기에

D:\Pixiv downloader\hitomi_downloaded_pixiv\すいと (pixiv_4910367)\illust
D:\Pixiv downloader\hitomi_downloaded_pixiv\すいと (pixiv_4910367)\manga
이런식으로

폴더 두개가 생성되도록 ㅇㅇ

아니면 
https://www.pixiv.net/member_illust.php?id=4910367&type=illust
https://www.pixiv.net/member_illust.php?id=4910367&type=manga

픽시브 주소가 갈라지니까 링크를 type=illust로 밖으면 일러스트만 다운받게 해주세얌!

이분은 참 보배인 데수웅

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by marumar** [comment]
깃허브 다운속도 점점 0에 수렴하다가 멈추길래 vpn 돌려서 받음

진짜 일러스트만 다운되네얌 갓갓갓갓
