### ISSUE TITLE
avgle 다운로드 문제

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader-issues#1718]
링크 : https://avgle.com/video/1RdoLoIa1oX/%E5%A3%B2%E3%82%8A%E3%82%92%E3%81%99%E3%82%8B%E5%A5%B3%E5%AD%A6%E7%94%9F%E3%81%AE%E4%B8%AD%E5%87%BA%E3%81%97%E6%80%A7%E4%BA%A4%E9%8C%B2

브라우저에선 정상적으로 재생 됩니다
![image](https://user-images.githubusercontent.com/36811336/75448373-73311700-59ae-11ea-8198-61bfc404d59e.png)

로그

売りをする女学生の中出し性交録 跡美しゅり XVSR-417

version: 2.7h
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://avgle.com/video/1RdoLoIa1oX/売りをする女学生の中出し性交録
dir: hitomi_downloaded_avgle
zip: 
type: avgle
artist: None
url: https://avgle.com/video/1RdoLoIa1oX/売りをする女学生の中出し性交録
valid: False
done: True
range: None
range_p: None
single: True
time: 1582808985.61 (Feb 27)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_avgle\売りをする女学生の中出し性交録 跡美しゅり XVSR-417.mp4

[URLs]
[0001] LazyUrl(https://avgle.com/video/1RdoLoIa1oX/売りをする女学生の中出し性交録) ---> M3u8_stream(https://avgle.com/video/1RdoLoIa1oX/%E5%A3%B2%E3%82%8A%E3%82%92%E3%81%99%E3%82%8B%E5%A5%B3%E5%AD%A6%E7%94%9F%E3%81%AE%E4%B8%AD%E5%87%BA%E3%81%97%E6%80%A7%E4%BA%A4%E9%8C%B2)

[Messages]
https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-4-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-3-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-2-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Traceback (most recent call last):
File "m3u8_tools", line 35, in run
File "m3u8_tools", line 140, in _read
Exception: Failed to download

Fail : 売りをする女学生の中出し性交録 跡美しゅり XVSR-417.mp4
Traceback (most recent call last):
File "downloader", line 636, in download
File "m3u8_tools", line 124, in read
Exception: Failed to download

Traceback (most recent call last):
File "m3u8_tools", line 35, in run
File "m3u8_tools", line 140, in _read
Exception: Failed to download

stop
valid=False 1

Fail : https://ip57682638.ahcdn.com/key=iFZJhzBwSu9MGQ9sRdSz8w,s=,end=1582809790/state=Mw9-/reftag=72984513/media=hls/1/193/7/173914997.mp4/seg-1-v1-a1.ts
Traceback (most recent call last):
File "downloader", line 803, in download
Exception: 403

Traceback (most recent call last):
File "m3u8_tools", line 35, in run
File "m3u8_tools", line 140, in _read
Exception: Failed to download

Traceback (most recent call last):
File "m3u8_tools", line 35, in run
File "m3u8_tools", line 140, in _read
Exception: Failed to download

EOT: https://avgle.com/video/1RdoLoIa1oX/売りをする女学生の中出し性交録

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Yoon0618** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 다운로드됩니다!
