### ISSUE TITLE
다운로드 문제

### ISSUE THREAD

**Issue by kusmon** [KurtBestor/Hitomi-Downloader-issues#18]
1.9a 에서는 다운로드가 잘되는데 2.0부터는 안되네요.

**Comment by KurtBestor** [comment]
어떤 게 안되나요?

**Comment by akdwkdml** [comment]
일단 다운로드 속도 자체가 매우 느리고 (12mb짜리 파일인데 10분~1시간 에서 막왓다갔다해요)

그리고 크롬,익플 둘다 어제부터계속 시도했는데도 

다운이 안받아집니다.ㅠㅠㅠ

저는2.2mb에서 계속 멈춥니다.. 

간신히 10mb까지 가도 결국 중간에 멈춰집니다

크롬에서는 네트워크오류 익플에서는 그냥 다운로드 중단인가 실패라고 뜹니다..

**Comment by KurtBestor** [comment]
@akdwkdml 
문제가 많은 것 같아 일단 구글 드라이브로 다시 돌려놨습니다.

**Comment by goqhadl** [comment]
![default](https://user-images.githubusercontent.com/34686282/34839274-62c97048-f744-11e7-910f-fb5594283d06.PNG)
이런식으로 다운이 되고 안되고 하네요.
1.9 a 버전에서는 다운이 잘 됬습니다.

**Comment by KurtBestor** [comment]
@goqhadl 
해당 작업 마우스 우클릭 후 [정보...]를 눌러보시면 정보창이 나옵니다.
내용 보내주시면 감사하겠습니다.

**Comment by goqhadl** [comment]
@KurtBestor 
[N／A] Aruhi Totsuzen Full-size (1168413)

gal_num: https://hitomi.la/galleries/1168413.html
dir: hitomi_downloaded\[N／A] Aruhi Totsuzen Full-size (1168413)
zip: 
type: hitomi
artist: N／A
url: https://hitomi.la/galleries/1168413.html
valid: True
done: False


[File Names]
[0001] hitomi_downloaded\[N／A] Aruhi Totsuzen Full-size (1168413)\1.jpg
[0002] hitomi_downloaded\[N／A] Aruhi Totsuzen Full-size (1168413)\2.jpg


[URLs]
[0001] https://ba.hitomi.la/galleries/1168413/1.jpg
[0002] https://ba.hitomi.la/galleries/1168413/2.jpg


[Messages]
********************************
Gallery number : 1168413
Number of Threads : 64
********************************
FINAL SERVER : hitomi:ba
ehen_url : None
Traceback (most recent call last):
File "hitomi_downloader", line 264, in get_title__
Exception: Fail: get_title__ (group)

Traceback (most recent call last):
File "hitomi_downloader", line 279, in get_title__
Exception: Fail: get_title__ (series)

get_title__

Title :
[N／A] Aruhi Totsuzen Full-size (1168413)


Fail : C:\Users\name\Desktop\hitomi_downloader_GUI (1)\hitomi_downloaded\[N／A] Aruhi Totsuzen Full-size (1168413)\1.jpg
Traceback (most recent call last):
File "downloader", line 342, in download
File "downloader", line 337, in Stream
File "socket", line 284, in read
File "httplib", line 381, in read
File "socket", line 284, in read
File "ssl", line 479, in recv
File "ssl", line 373, in read
SSLError: ('The read operation timed out',)


Fail : C:\Users\name\Desktop\hitomi_downloader_GUI (1)\hitomi_downloaded\[N／A] Aruhi Totsuzen Full-size (1168413)\2.jpg
Traceback (most recent call last):
File "downloader", line 308, in download
ReadTimeoutError: HTTPSConnectionPool(host=u'ba.hitomi.la', port=443): Read timed out. (read timeout=12)

**Comment by KurtBestor** [comment]
@goqhadl 
히토미 말고 다른 사이트에서도 똑같은가요?

**Comment by KurtBestor** [comment]
답이 없어서 일단 닫습니다
