### ISSUE TITLE
마나모아 다운이 안됩니다.

### ISSUE THREAD

**Issue by nightow** [KurtBestor/Hitomi-Downloader-issues#1849]
안녕하십니까,
마나모아 다운중 갑자기 하나가 안되어 확인 요청드립니다.
프로그램 만들어 주시고, 시간들여서 업데이트 해주시는 것 항상 감사드립니다.

Invalid: [manamoa] https://manamoa.net / bbs / board.php?bo_table=manga&wr_id=2854482

version: 2.8 (20-04-01 17:48:18 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=2854482
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=2854482
valid: False
done: True
range: None
range_p: None
single: False
time: 1585811022.81 (Apr 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf solved
clf solved
clf solved
clf solved
stop
Traceback (most recent call last):
File "utils", line 730, in __init__
File "manamoa_downloader", line 144, in init
File "<decorator-gen-45>", line 2, in get_soup
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 226, in get_soup
File "manamoa_downloader", line 520, in read_html
File "downloader", line 385, in read_html
Exception: 502

Invalid: fail=True
stop
EOT: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=2854482

clf solved
clf solved
clf solved
clf solved
stop
Traceback (most recent call last):
File "utils", line 730, in __init__
File "manamoa_downloader", line 144, in init
File "<decorator-gen-45>", line 2, in get_soup
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 226, in get_soup
File "manamoa_downloader", line 520, in read_html
File "downloader", line 385, in read_html
Exception: 502

Invalid: fail=True
stop
EOT: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=2854482

clf solved
clf solved
clf solved
clf solved
stop
Traceback (most recent call last):
File "utils", line 730, in __init__
File "manamoa_downloader", line 144, in init
File "<decorator-gen-45>", line 2, in get_soup
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 226, in get_soup
File "manamoa_downloader", line 520, in read_html
File "downloader", line 385, in read_html
Exception: 502

Invalid: fail=True
stop
EOT: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=2854482

clf solved
clf solved
clf solved
clf solved
stop
Traceback (most recent call last):
File "utils", line 730, in __init__
File "manamoa_downloader", line 144, in init
File "<decorator-gen-46>", line 2, in get_soup
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "manamoa_downloader", line 226, in get_soup
File "manamoa_downloader", line 520, in read_html
File "downloader", line 385, in read_html
Exception: 502

Invalid: fail=True
stop
EOT: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=2854482

**Comment by KurtBestor** [comment]
502 서버 오류인데 잠시 뒤에 다시 시도하면 될거예요.

**Comment by nightow** [comment]
말씀하신 대로 시간 지난 뒤에 실행해보니 잘되네요
번거롭게 해드려 죄송합니다.
