### ISSUE TITLE
facebook - required login - not working

### ISSUE THREAD

**Issue by wankio** [KurtBestor/Hitomi-Downloader-issues#1869]
https://www.facebook.com/sovietsenpai/

Every pages required login, once you add cookies, it wont work

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by wankio** [comment]
it's working with that link

1- but fanpage : https://www.facebook.com/GoddessOfGenesisVI/
```
[Messages]
No JSON object could be decoded
stop
Traceback (most recent call last):
File "utils", line 870, in start
File "utils", line 920, in start_
File "facebook_downloader3", line 109, in read
File "facebook_downloader3", line 182, in get_imgs
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

```
or fb profile : https://www.facebook.com/hyeangyu.sin
is not working, dont know why.

2- folder name have fb_dtsg (facebook_[id]) instead fanpage/facebook name (facebook_[id])
