### ISSUE TITLE
올바르지 않은 형식의 검색 필터입니다

### ISSUE THREAD

**Issue by dspsble** [KurtBestor/Hitomi-Downloader-issues#187]
검색기 사용 시 다음과 같은 오류가 발생합니다.
```
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1805, in searchButton
  File "hitomi_downloader_GUI", line 1656, in parse
  File "<string>", line 1
    (True) and
              ^
SyntaxError: unexpected EOF while parsing
```
아무 태그도 넣지 않았을 때에 위와 같이, 태그를 넣었을 경우에는
```
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1805, in searchButton
  File "hitomi_downloader_GUI", line 1656, in parse
  File "<string>", line 1
    (((u"""korean""" in gal.simple)) and ((u"""webtoon""" not in gal.tags))) and
                                                                                ^
SyntaxError: unexpected EOF while parsing
```
처럼 발생합니다.

**Comment by dspsble** [comment]
옵션의 제외 태그 기능 사용 시 해당 목록이 비어 있으면 발생하는 태그로 생각됩니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

테스트 부탁드려요.

**Comment by dspsble** [comment]
해당 버그 사라진 것 확인했습니다.
