### ISSUE TITLE
허브 영상 다운로드 Invalid

### ISSUE THREAD

**Issue by Rainingdayz** [KurtBestor/Hitomi-Downloader-issues#1887]
로그입니다.

Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5d0a70f93c461

version: 2.8 (20-04-11 09:14:31 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d0a70f93c461
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d0a70f93c461
valid: False
done: True
range: None
range_p: None
single: True
time: 1586668573.11 (Apr 12)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
isLogin 2
stop
Traceback (most recent call last):
File "utils", line 731, in __init__
File "pornhub_downloader", line 85, in init
File "pornhub_downloader", line 58, in isLogin
File "downloader", line 295, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 89, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 514, in send
SSLError: HTTPSConnectionPool(host='www.pornhubpremium.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))

Invalid: fail=True
stop
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d0a70f93c461

**Comment by Rainingdayz** [comment]
쿠키 넣어서 다른 영상들은 다운이 되는 이런식으로 막히는게 하나씩 있더라고요.

**Comment by Rainingdayz** [comment]
아이고 아니네요. 해당 영상 링크 들어가서 쿠키를 새로 받고 넣으니까 정상적으로 다운로드 됩니다.
