### ISSUE TITLE
애니24가 다운이 안됩니다

### ISSUE THREAD

**Issue by hohoe** [KurtBestor/Hitomi-Downloader-issues#1895]
항상 감사드립니다.

애니 24 스크립트 설치하고 다운 시도했습니다만 잘안되네요 .  정보는 다음과 같습니다.

Invalid: [ani24] https://ani24do.com / ani_list / 2130.html

version: 2.8 (20-04-04 05:35:08 GMT+0)
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://ani24do.com/ani_list/2130.html
dir: 
zip: 
type: ani24
artist: None
url: https://ani24do.com/ani_list/2130.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1586952878.6 (Apr 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
failed to read page
stop
Traceback (most recent call last):
File "utils", line 869, in start
File "utils", line 919, in start_
File "dynamic_module_0", line 72, in read
Exception: failed to read page

Invalid: fail=True
EOT: https://ani24do.com/ani_list/2130.html

**Comment by KurtBestor** [comment]
오래된 스크립트 같은데 다시 다운로드해서 넣어주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts

**Comment by hohoe** [comment]
스크립트 및 프로그램 재설치 후 또 안되길래  혹시나 싶어 vpn(유료) 끄고 하니 작동 됩니다. vpn ip모두 막히는 것이 조금 이상하기는 하나 그래도 작동되서 잘쓰고 있습니다.  조언 감사합니다.

**Comment by Psychopath7** [comment]
https://github.com/Psychopath7/ohli24_script
