### ISSUE TITLE
폰헙 프리미엄 다운로드가 안됩니다

### ISSUE THREAD

**Issue by ponub** [KurtBestor/Hitomi-Downloader-issues#1899]
Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5e875507c2f6d

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
valid: False
done: True
range: None
range_p: None
single: True
time: 1587003808.81 (Apr 16)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e875507c2f6d

여기서 폰헙관련된거 다 찾아보고 개발자님이 남기신코멘트대로 다 따라해봤는데 결국 안되네요..

**Comment by KurtBestor** [comment]
참고해주세요: #1855
