### ISSUE TITLE
대기열에 추가한 인스타 계정 연속 다운로드 중 인스타그램 다운로드 불가 현상

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader-issues#1901]
안녕하세요 선생님!

인스타그램 쿠키 정상이며 다운로드시 읽는 과정까진 진행 되다가 다운로드 넘어가면 아예 노란색으로 표시되며 다운로드 되지 않는 현상입니다.

제가 인스타그램 계정을 대기열에 30개 정도 추가한 후, 연속해서 20계정 정도는 정상적으로 다운받던 중에 일어난 일인지라 일시적인 밴을 당한 가능성도 있다고 생각해보았습니다.

만약 밴을 당해서라면 무작정 시간을 두고 기다려보는 것이 해결방법 일까요?
DPI도 껐다 켜보고 쿠키 초기화->쿠키 새로 불러오기 해보았으나 이걸로는 해결되지 않았습니다.

혹시 로그로 해결방법을 알수 있을까 싶어서 로그를 남겨놓습니다.

로그 테스트 계정 : https://www.instagram.com/sing_harang/

로그는 다음과 같습니다.
------------------------------------------------------------------------------------------------------------
이하랑 (insta_sing_harang)

version: 2.8 (20-04-14 15:12:47 GMT+0)
platform: Windows-10-10.0.17134
order: 63
group: False
gal_num: https://www.instagram.com/sing_harang/
dir: crawl__insta\이하랑 (insta_sing_harang)
zip: 
type: insta
artist: 이하랑
url: https://www.instagram.com/sing_harang
valid: False
done: True
range: None
range_p: None
single: False
time: 1587037821.91 (Apr 16)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0002] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0003] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0004] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0005] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0006] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0007] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0008] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0009] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0010] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0011] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0012] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0013] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0014] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0015] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0016] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0017] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0018] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0019] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0020] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0021] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0022] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0023] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0024] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0025] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0026] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0027] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0028] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0029] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0030] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0031] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0032] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0033] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0034] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0035] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0036] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0037] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0038] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0039] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0040] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0041] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0042] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0043] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0044] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0045] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0046] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0047] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0048] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0049] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0050] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0051] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0052] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0053] crawl__insta\이하랑 (insta_sing_harang)\lazy
[0054] crawl__insta\이하랑 (insta_sing_harang)\lazy

[URLs]
[0001] LazyUrl(https://www.instagram.com/p/B_Blb7IAeXT/)
[0002] LazyUrl(https://www.instagram.com/p/B9zNse3gXaA/)
[0003] LazyUrl(https://www.instagram.com/p/B9zE7KQgSSm/)
[0004] LazyUrl(https://www.instagram.com/p/B9bvEwAAc-b/)
[0005] LazyUrl(https://www.instagram.com/p/B9UM_cuAxTA/)
[0006] LazyUrl(https://www.instagram.com/p/B9BDqEngXKK/)
[0007] LazyUrl(https://www.instagram.com/p/B8-rBeQgLWI/)
[0008] LazyUrl(https://www.instagram.com/p/B85--hvgGP0/)
[0009] LazyUrl(https://www.instagram.com/p/B80H0PNAWk4/)
[0010] LazyUrl(https://www.instagram.com/p/B8xSmqPgCgt/)
[0011] LazyUrl(https://www.instagram.com/p/B8AttKsAKcO/)
[0012] LazyUrl(https://www.instagram.com/p/B8AtGIzgQ-t/)
[0013] LazyUrl(https://www.instagram.com/p/B7sA7JugU2u/)
[0014] LazyUrl(https://www.instagram.com/p/B6p92OhAztz/)
[0015] LazyUrl(https://www.instagram.com/p/B5_41CXgUxW/)
[0016] LazyUrl(https://www.instagram.com/p/B54kY1pA4lp/)
[0017] LazyUrl(https://www.instagram.com/p/B5pWiKxARfY/)
[0018] LazyUrl(https://www.instagram.com/p/B47VBNrgcmk/)
[0019] LazyUrl(https://www.instagram.com/p/B40yDMogdXH/)
[0020] LazyUrl(https://www.instagram.com/p/B4rrU8vAnZ-/)
[0021] LazyUrl(https://www.instagram.com/p/B4Wn4MEg9TV/)
[0022] LazyUrl(https://www.instagram.com/p/B4Udfm9gu8D/)
[0023] LazyUrl(https://www.instagram.com/p/B4GyueCgef7/)
[0024] LazyUrl(https://www.instagram.com/p/B3vsqfmA92G/)
[0025] LazyUrl(https://www.instagram.com/p/B3jZ6rhAJbb/)
[0026] LazyUrl(https://www.instagram.com/p/B3Y_o2gAEbV/)
[0027] LazyUrl(https://www.instagram.com/p/B3F6gQ1gLPG/)
[0028] LazyUrl(https://www.instagram.com/p/B2ja396gPQP/)
[0029] LazyUrl(https://www.instagram.com/p/B2gFY6wAyRM/)
[0030] LazyUrl(https://www.instagram.com/p/B2eZmduA1SE/)
[0031] LazyUrl(https://www.instagram.com/p/B2TZfLZgvAd/)
[0032] LazyUrl(https://www.instagram.com/p/B2PDoaGAGao/)
[0033] LazyUrl(https://www.instagram.com/p/B2MDk9fABh-/)
[0034] LazyUrl(https://www.instagram.com/p/B18pGIfAvXo/)
[0035] LazyUrl(https://www.instagram.com/p/B15bOxJgDOx/)
[0036] LazyUrl(https://www.instagram.com/p/B10i1uAAgjQ/)
[0037] LazyUrl(https://www.instagram.com/p/B1gBuAbAtev/)
[0038] LazyUrl(https://www.instagram.com/p/B1WJmBAgNfR/)
[0039] LazyUrl(https://www.instagram.com/p/B1VgY8gAi92/)
[0040] LazyUrl(https://www.instagram.com/p/B1Qun6ngBX0/)
[0041] LazyUrl(https://www.instagram.com/p/B1MNqNIAd20/)
[0042] LazyUrl(https://www.instagram.com/p/B03IYEng02D/)
[0043] LazyUrl(https://www.instagram.com/p/B0f2OaAAi3L/)
[0044] LazyUrl(https://www.instagram.com/p/B0a50oWgb4T/)
[0045] LazyUrl(https://www.instagram.com/p/Bz_CWgSA381/)
[0046] LazyUrl(https://www.instagram.com/p/Bz5tFHFgg5E/)
[0047] LazyUrl(https://www.instagram.com/p/Bx_5ywdAJyG/)
[0048] LazyUrl(https://www.instagram.com/p/Bw_rzu_g4GB/)
[0049] LazyUrl(https://www.instagram.com/p/Bw6KutsANaN/)
[0050] LazyUrl(https://www.instagram.com/p/BwXK8-UgTNP/)
[0051] LazyUrl(https://www.instagram.com/p/BwQn12ygrBl/)
[0052] LazyUrl(https://www.instagram.com/p/BvvrtnvAjui/)
[0053] LazyUrl(https://www.instagram.com/p/BvtF9G-gEF9/)
[0054] LazyUrl(https://www.instagram.com/p/BvdvP0uBkCC/)

[Messages]
Failed to get stories; Login required: None

LazyUrl error (https://www.instagram.com/p/B_Blb7IAeXT/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B9bvEwAAc-b/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B9zNse3gXaA/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B9zE7KQgSSm/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B9UM_cuAxTA/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B9BDqEngXKK/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B85--hvgGP0/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B8-rBeQgLWI/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B80H0PNAWk4/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B8AttKsAKcO/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B8xSmqPgCgt/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B7sA7JugU2u/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B8AtGIzgQ-t/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B5_41CXgUxW/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B54kY1pA4lp/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B6p92OhAztz/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B5pWiKxARfY/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B47VBNrgcmk/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B40yDMogdXH/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B4rrU8vAnZ-/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B4Wn4MEg9TV/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B4Udfm9gu8D/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B4GyueCgef7/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B3vsqfmA92G/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B3jZ6rhAJbb/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B3Y_o2gAEbV/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B3F6gQ1gLPG/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B2ja396gPQP/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B2gFY6wAyRM/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B2eZmduA1SE/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B2TZfLZgvAd/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B2PDoaGAGao/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B18pGIfAvXo/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B2MDk9fABh-/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B15bOxJgDOx/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B10i1uAAgjQ/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B1gBuAbAtev/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B1WJmBAgNfR/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B1VgY8gAi92/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B1Qun6ngBX0/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B1MNqNIAd20/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B0f2OaAAi3L/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B03IYEng02D/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/B0a50oWgb4T/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bz5tFHFgg5E/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bz_CWgSA381/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bx_5ywdAJyG/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bw_rzu_g4GB/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/Bw6KutsANaN/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BwXK8-UgTNP/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BwQn12ygrBl/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BvvrtnvAjui/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BvdvP0uBkCC/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

LazyUrl error (https://www.instagram.com/p/BvtF9G-gEF9/):
Traceback (most recent call last):
File "hitomi_downloader", line 213, in run
File "utils", line 576, in __call__
File "insta_downloader", line 183, in f
File "insta_downloader", line 332, in __init__
File "insta_downloader", line 122, in get_sd
Exception: no _sharedData

stop
valid=False 1
EOT: https://www.instagram.com/sing_harang/

**Comment by tdi2020** [comment]
헉 선생님, 쿠키를 바꾸어 로그인 했더니 다운로드가 잘 되었습니다. 

그렇다면 이전 쿠키에 사용된 아이디는 다운받지 못하도록 인스타그램이 밴을 한 것일까요?

**Comment by KurtBestor** [comment]
로그아웃하거나 새로 로그인하면 이전 쿠키는 쓸 수 없어요.

프로그램에선 단순히 시간에 의한 만료만 체크해요.
