### ISSUE TITLE
20세 이상만 볼 수 있는 프로필입니다 라고 뜨는 인스타는 다운이 안됩니다

### ISSUE THREAD

**Issue by lducjswo** [KurtBestor/Hitomi-Downloader-issues#1902]
계속 다운이 실패하길래 보니까 20세 이상만 볼 수 있는 인스타더라구요
혹시 여기도 다운받는 방법이 있을까요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by lducjswo** [comment]
Invalid: [insta] https://www.instagram.com / siaoding_komachi / 

version: 2.7h (20-02-29 13:17:36 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.instagram.com/siaoding_komachi/
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/siaoding_komachi/
valid: False
done: True
range: None
range_p: None
single: False
time: 1587111463.35 (Apr 17)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "insta_downloader", line 34, in init
File "insta_downloader", line 39, in id
File "insta_downloader", line 99, in get_id
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Invalid: fail=True
stop
EOT: https://www.instagram.com/siaoding_komachi/

stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "insta_downloader", line 34, in init
File "insta_downloader", line 39, in id
File "insta_downloader", line 99, in get_id
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Invalid: fail=True
stop
EOT: https://www.instagram.com/siaoding_komachi/

stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "insta_downloader", line 34, in init
File "insta_downloader", line 39, in id
File "insta_downloader", line 99, in get_id
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Invalid: fail=True
stop
EOT: https://www.instagram.com/siaoding_komachi/

stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "insta_downloader", line 34, in init
File "insta_downloader", line 39, in id
File "insta_downloader", line 99, in get_id
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Invalid: fail=True
stop
EOT: https://www.instagram.com/siaoding_komachi/

stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "insta_downloader", line 34, in init
File "insta_downloader", line 39, in id
File "insta_downloader", line 99, in get_id
File "insta_downloader", line 94, in get_sd
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Invalid: fail=True
stop
EOT: https://www.instagram.com/siaoding_komachi/

이렇게 나옵니다

**Comment by KurtBestor** [comment]
최신 버전에서 로그인 쿠키 넣어주세요.

**Comment by lducjswo** [comment]
감사합니다!
