### ISSUE TITLE
폰허브 다운로드 오류입니다.

### ISSUE THREAD

**Issue by lordsidi66** [KurtBestor/Hitomi-Downloader-issues#1906]
2.8 버전이고 프리미엄 동영상의 로그인 창도 뜨지 않더라고요. 내역은 다음과 같습니다.

Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5debc602f1f70

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
valid: False
done: True
range: None
range_p: None
single: True
time: 1587179624.99 (Apr 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5debc602f1f70

**Comment by KurtBestor** [comment]
참고해주세요: #1855
