### ISSUE TITLE
마루마루 다운로드가 실패합니다

### ISSUE THREAD

**Issue by rainrain1984** [KurtBestor/Hitomi-Downloader-issues#208]
마루마루 다운로드가 실패합니다

혹시 해결책을 받을수 있을까요?

Invalid : [maru] https://marumaru.in / b / manga / 61281

gal_num: https://marumaru.in/b/manga/61281
dir: 
zip: 
type: maru
artist: None
url: http://marumaru.in/b/manga/61281
valid: False
done: False
range: None
range_p: None
single: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 501, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 497, in wrapper
File "maru_downloader", line 385, in read_html
File "downloader", line 284, in read_html
Exception: 403

Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 501, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 497, in wrapper
File "maru_downloader", line 385, in read_html
File "downloader", line 284, in read_html
Exception: 403

Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 501, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 497, in wrapper
File "maru_downloader", line 385, in read_html
File "downloader", line 284, in read_html
Exception: 403

Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 501, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 497, in wrapper
File "maru_downloader", line 385, in read_html
File "downloader", line 284, in read_html
Exception: 403

stop
Traceback (most recent call last):
File "maru_downloader", line 55, in init
File "constants", line 501, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 497, in wrapper
File "maru_downloader", line 385, in read_html
File "downloader", line 284, in read_html
Exception: 403

Fail: maru

stop
done : https://marumaru.in/b/manga/61281

**Comment by KurtBestor** [comment]
웹브라우저로 직접 들어가는 건 잘 되나요?

**Comment by rainrain1984** [comment]
네 웹으로는 잘 들어가집니다. 혹시 해외 접속인것도 영향이 있을까요

**Comment by KurtBestor** [comment]
![hd](https://user-images.githubusercontent.com/14768120/44305382-c76a3c80-a3b0-11e8-9948-5fd4f1fbec05.png)

크롬 브라우저에서 해당 페이지 들어간 다음 [F12] 누르고 [Ctrl + F5] 누른 다음 위와 같이 들어가서 마지막 박스에 나오는 내용 알려주실 수 있나요?

**Comment by rainrain1984** [comment]
캡차 전

General

Request URL: https://marumaru.in/b/manga/61281
Request Method: GET
Status Code: 403 Forbidden
Remote Address: 104.20.32.152:443
Referrer Policy: no-referrer-when-downgrade

Response Headers

Cache-Control: max-age=2
CF-Chl-Bypass: 1
CF-RAY: 44ca0c665c7ba9ba-SIN
Connection: close
Content-Type: text/html; charset=UTF-8
Date: Sun, 19 Aug 2018 04:59:01 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Sun, 19 Aug 2018 04:59:03 GMT
Server: cloudflare
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN

Request Headers

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Cookie: __cfduid=d0ab4c01b3a94481ca60ad363b45759f31534654735
Host: marumaru.in
Pragma: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36


캡차 후

General

Request URL: https://marumaru.in/b/manga/61281
Request Method: GET
Status Code: 200 OK
Remote Address: 104.20.32.152:443
Referrer Policy: no-referrer-when-downgrade

Response Headers

Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
CF-RAY: 44ca01bf7d4370bc-SIN
Connection: keep-alive
Content-Encoding: br
Content-Type: text/html;charset=utf-8
Date: Sun, 19 Aug 2018 04:51:45 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: cloudflare
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Transfer-Encoding: chunked
X-Turbo-Charged-By: LiteSpeed

Request Headers

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Cookie: __cfduid=d56e05de3d069f1435e5679a6b74f60d71521643708; _ga=GA1.2.239386431.1521643710; marumaru-banner=true; cf_clearance=7f0d264c2f6d863933975cd3973b1994ab2b610e-1534654281-14400-250; PHPSESSID=bsugft3lpk69bg8fcu1nu89nr6
Host: marumaru.in
Pragma: no-cache
Referer: https://marumaru.in/b/manga/61281
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
