### ISSUE TITLE
인스타그램 다운로드가 안되요 ㅠㅠ

### ISSUE THREAD

**Issue by jun0000000** [KurtBestor/Hitomi-Downloader-issues#209]
오래전 부터 안되다 이제야 물어 보네요 .

정보는 아래와 같습니다.

ps. 덕분에 프로그램 잘 쓰고 있습니다. 고맙습니다. 

Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 177, in get_imgs
File "selenium\webdriver\phantomjs\webdriver", line 58, in __init__
File "selenium\webdriver\remote\webdriver", line 154, in __init__
File "selenium\webdriver\remote\webdriver", line 243, in start_session
File "selenium\webdriver\remote\webdriver", line 309, in execute
File "selenium\webdriver\remote\remote_connection", line 460, in execute
File "selenium\webdriver\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1198, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>
- __leeheeeun__

gal_num: https://www.instagram.com/__leeheeeun__/?hl=ko
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/__leeheeeun__
valid: False
done: False
range: None
range_p: None
single: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 177, in get_imgs
File "selenium\webdriver\phantomjs\webdriver", line 58, in __init__
File "selenium\webdriver\remote\webdriver", line 154, in __init__
File "selenium\webdriver\remote\webdriver", line 243, in start_session
File "selenium\webdriver\remote\webdriver", line 309, in execute
File "selenium\webdriver\remote\remote_connection", line 460, in execute
File "selenium\webdriver\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1198, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Fail: insta

Traceback (most recent call last):
File "utils", line 664, in Invalid
File "downloader", line 234, in read_html
Exception: 404

stop
done : https://www.instagram.com/__leeheeeun__/?hl=ko

**Comment by jun0000000** [comment]
다운 되요! 감사합니다!
