### ISSUE TITLE
이미지 셋 다운이 40개에서 멈춰요

### ISSUE THREAD

**Issue by gustn2306** [KurtBestor/Hitomi-Downloader-issues#212]
익헨에서 40개 이상 되는 파일을 받다가 보면 어쩔때 40개 혹은 20개로 받아집니다.

**Comment by KurtBestor** [comment]
해당 작업 [마우스 우클릭 - 정보] 눌러서 나오는 내용 알려주세요.

**Comment by gustn2306** [comment]
[Krenz] Studies by Krenz (883632)

gal_num: https://exhentai.org/g/883632/deb86d946f/?p=11
dir: hitomi_downloaded\[Krenz] Studies by Krenz (883632)
zip: hitomi_downloaded\[Krenz] Studies by Krenz (883632).zip
type: ehen
artist: Krenz
url: https://e-hentai.org/g/883632/deb86d946f/?p=11
valid: True
done: True
range: None
range_p: None
single: False


[Gallery]
갤러리 넘버: 883632

제목: Studies by Krenz

작가: krenz

그룹: N/A

타입: non-h

시리즈: N/A

캐릭터: N/A

태그: N/A

언어: N／A


[File Names]
[0001] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\537527_459697674067040_1901199065_n.jpg
[0002] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\538431_396855887017886_1372384632_n.jpg
[0003] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\540223_351901784846630_1296692196_n.jpg
[0004] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\540623_371082712928537_288966418_n.jpg
[0005] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\540795_404929346210540_1557070182_n.jpg
[0006] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\541516_600375413332598_1532633087_n.jpg
[0007] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\542284_475364309167043_1797679194_n.jpg
[0008] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\543828_472546116115529_1959252119_n.jpg
[0009] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\544083_508345979202209_61662267_n.jpg
[0010] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\547047_441121479257993_1521021812_n.jpg
[0011] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\547415_502283033141837_418385236_n.jpg
[0012] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\548318_370919562944852_1966120502_n.jpg
[0013] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\548426_432665353436939_800511540_n.jpg
[0014] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\549521_421251991244942_709914624_n.jpg
[0015] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\549922_491570500879757_848839612_n.jpg
[0016] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\551327_507171892652951_1047984873_n.jpg
[0017] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\553433_554882447881895_478811800_n.jpg
[0018] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\557435_427425877294220_817507493_n.jpg
[0019] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\557858_443841665652641_207920821_n.jpg
[0020] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\558009_502357219801085_2137581669_n.jpg
[0021] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\559091_541830782520395_1106236485_n.jpg
[0022] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\560681_392995780737230_851825615_n.jpg
[0023] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\562271_382861798417295_1054220256_n.jpg
[0024] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\563038_487533477950126_675186307_n.jpg
[0025] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\563263_407752899261518_518756252_n.jpg
[0026] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\564177_427454350624706_1972332091_n.jpg
[0027] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\577024_422879741082167_2081804360_n.jpg
[0028] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\577613_513900121980128_883645644_n.jpg
[0029] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\578166_385570804813061_1359614238_n.jpg
[0030] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\581648_538694229500717_464136195_n.jpg
[0031] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\58267_471019906268150_2099544014_n.jpg
[0032] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\582727_421307177906090_838589252_n.jpg
[0033] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\598760_555167757853364_25197618_n.jpg
[0034] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\600029_413171485386326_2635834_n.jpg
[0035] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\603942_449150895121718_905622773_n.jpg
[0036] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\604057_444161272287347_992367043_n.jpg
[0037] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\61468_430294293674045_2019436715_n.jpg
[0038] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\61751_482138868489587_1660642450_n.jpg
[0039] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\64452_503455869691220_591144164_n.jpg
[0040] hitomi_downloaded\[Krenz] Studies by Krenz (883632)\64537_443671849002956_513903838_n.jpg


[URLs]
[0001] https://e-hentai.org/s/8ff8271599/883632-441 ---> http://175.193.48.68:8500/h/8ff8271599e78bd0cd787e8d54db5760af6efdc4-101740-960-640-jpg/keystamp=1542150900-e459fcfd37;fileindex=40438324;xres=org/537527_459697674067040_1901199065_n.jpg
[0002] https://e-hentai.org/s/5d0693802b/883632-442 ---> http://112.166.75.182:56702/h/5d0693802b53deb8cd631bcf0b43f4f9d799a390-131201-850-532-jpg/keystamp=1542150900-104839bfee;fileindex=40438325;xres=org/538431_396855887017886_1372384632_n.jpg
[0003] https://e-hentai.org/s/4dfd360c2f/883632-443 ---> http://14.49.100.116:58198/h/4dfd360c2fb111b4a5992d5914eeba4ccf673f86-154638-800-566-jpg/keystamp=1542150900-e6c24b0165;fileindex=40438326;xres=org/540223_351901784846630_1296692196_n.jpg
[0004] https://e-hentai.org/s/719426ecdc/883632-444 ---> http://171.5.48.54:55555/h/719426ecdc90acbdd9dc8f1713fd4ed772308bed-89730-500-707-jpg/keystamp=1542150900-79b3a5d386;fileindex=40438327;xres=org/540623_371082712928537_288966418_n.jpg
[0005] https://e-hentai.org/s/ca190424c6/883632-445 ---> http://218.173.116.151:21000/h/ca190424c624b1a7f2abaea99e2a4f993c1bd025-54666-550-778-jpg/keystamp=1542150900-c4675a6831;fileindex=40438328;xres=org/540795_404929346210540_1557070182_n.jpg
[0006] https://e-hentai.org/s/ec93ee635d/883632-446 ---> http://222.103.24.51:61245/h/ec93ee635db18c7b769eb36b42e5852481b2ebff-138652-960-720-jpg/keystamp=1542150900-e6c8363e88;fileindex=40438329;xres=org/541516_600375413332598_1532633087_n.jpg
[0007] https://e-hentai.org/s/d1ecb038ca/883632-447 ---> http://61.93.125.35:9595/h/d1ecb038ca08794f98840adf86227178918614a3-41947-550-778-jpg/keystamp=1542150900-2da7f98df5;fileindex=40438330;xres=org/542284_475364309167043_1797679194_n.jpg
[0008] https://e-hentai.org/s/ea16869b05/883632-448 ---> http://220.92.54.121:1024/h/ea16869b05a8b6083c88c0816297495b98449093-49712-960-576-jpg/keystamp=1542150900-df253f2268;fileindex=40438331;xres=org/543828_472546116115529_1959252119_n.jpg
[0009] https://e-hentai.org/s/42baf7761c/883632-449 ---> http://175.193.48.68:8500/h/42baf7761cdab20dac3acbaafaf71e78687b3012-77072-500-707-jpg/keystamp=1542150900-cf7a64b378;fileindex=40438332;xres=org/544083_508345979202209_61662267_n.jpg
[0010] https://e-hentai.org/s/9f875234d9/883632-450 ---> http://1.232.78.67:31415/h/9f875234d9b222060e10fdc46deb25b6eaa5aece-55547-800-566-jpg/keystamp=1542150900-129753d4f3;fileindex=40438333;xres=org/547047_441121479257993_1521021812_n.jpg
[0011] https://e-hentai.org/s/88a4b5de1f/883632-451 ---> http://211.195.182.79:56133/h/88a4b5de1fbdd7ad39b220b3d177bbbc756f183a-67971-800-566-jpg/keystamp=1542150900-8ea1288d2d;fileindex=40438334;xres=org/547415_502283033141837_418385236_n.jpg
[0012] https://e-hentai.org/s/7eb1105b96/883632-452 ---> http://111.242.184.135:5566/h/7eb1105b96b861e596635c36643530306fcdcd50-161455-850-605-jpg/keystamp=1542150900-257b3340dc;fileindex=40438335;xres=org/548318_370919562944852_1966120502_n.jpg
[0013] https://e-hentai.org/s/d60508c84d/883632-453 ---> http://61.93.125.35:9595/h/d60508c84d79be5f83df700e0a1fdfb151e59632-67370-450-637-jpg/keystamp=1542150900-544665342c;fileindex=40438336;xres=org/548426_432665353436939_800511540_n.jpg
[0014] https://e-hentai.org/s/7e8d498bf3/883632-454 ---> http://133.18.168.124:42059/h/7e8d498bf3ec10065fcb11426d6ed224d2bf4c66-51174-500-707-jpg/keystamp=1542150900-ce97eacb6f;fileindex=40438337;xres=org/549521_421251991244942_709914624_n.jpg
[0015] https://e-hentai.org/s/307adf5034/883632-455 ---> http://211.195.182.79:56133/h/307adf5034ad4cf0139e6db0e422756531cb2b76-26604-474-741-jpg/keystamp=1542150900-3d72472075;fileindex=40438338;xres=org/549922_491570500879757_848839612_n.jpg
[0016] https://e-hentai.org/s/d983572272/883632-456 ---> http://182.227.147.73:1024/h/d98357227218af9065ab47c827e614b8b873e707-56623-960-557-jpg/keystamp=1542150900-82e2c9b624;fileindex=40438339;xres=org/551327_507171892652951_1047984873_n.jpg
[0017] https://e-hentai.org/s/5719d731a7/883632-457 ---> http://219.78.252.140:55871/h/5719d731a7dcf7d418e0888e34c910b5e8039601-35028-550-756-jpg/keystamp=1542150900-41f5d56473;fileindex=40438340;xres=org/553433_554882447881895_478811800_n.jpg
[0018] https://e-hentai.org/s/dd63f6d4dd/883632-458 ---> http://211.178.21.95:1999/h/dd63f6d4ddda939f1641af8c5cf59a1154236a8c-57103-550-778-jpg/keystamp=1542150900-639fd081fd;fileindex=40438341;xres=org/557435_427425877294220_817507493_n.jpg
[0019] https://e-hentai.org/s/909a02a216/883632-459 ---> http://117.68.165.125:65501/h/909a02a216a21c9642865b84c1551db8b43458ec-66955-800-566-jpg/keystamp=1542150900-f3dc4b6a5c;fileindex=40438342;xres=org/557858_443841665652641_207920821_n.jpg
[0020] https://e-hentai.org/s/620ac4d429/883632-460 ---> http://1.232.78.67:31415/h/620ac4d429873774b2c12f6d7dbb49230441dd2e-80038-800-566-jpg/keystamp=1542150900-4bc6859886;fileindex=40438343;xres=org/558009_502357219801085_2137581669_n.jpg
[0021] https://e-hentai.org/s/d4fc3fb770/883632-461 ---> http://14.49.100.116:58198/h/d4fc3fb7701a287a2ca1a75ee8f70e142eb1707b-47859-550-778-jpg/keystamp=1542150900-24cf08eab1;fileindex=40438344;xres=org/559091_541830782520395_1106236485_n.jpg
[0022] https://e-hentai.org/s/c3696d6bf3/883632-462 ---> http://39.117.42.45:4467/h/c3696d6bf348bd92fb255a990e74b8466325de92-103035-800-566-jpg/keystamp=1542150900-65e1676211;fileindex=40438345;xres=org/560681_392995780737230_851825615_n.jpg
[0023] https://e-hentai.org/s/241052d77a/883632-463 ---> http://153.120.38.17:65000/h/241052d77abdd3eb2186ba5c64df52ec6402f11c-33644-400-566-jpg/keystamp=1542150900-623399ccec;fileindex=40438346;xres=org/562271_382861798417295_1054220256_n.jpg
[0024] https://e-hentai.org/s/daae1e4b6a/883632-464 ---> http://112.166.75.182:56702/h/daae1e4b6ac830338fbbae6d688ae6666f3cd787-74830-960-678-jpg/keystamp=1542150900-28bbee8859;fileindex=40438347;xres=org/563038_487533477950126_675186307_n.jpg
[0025] https://e-hentai.org/s/b3bd58a871/883632-465 ---> http://112.166.75.182:56702/h/b3bd58a8714328db57edbc321f76f11ea6d344c4-55722-750-515-jpg/keystamp=1542150900-a3433168be;fileindex=40438348;xres=org/563263_407752899261518_518756252_n.jpg
[0026] https://e-hentai.org/s/da9751fc71/883632-466 ---> http://58.96.235.46:9001/h/da9751fc71d9639451d39681441fb942b189c32d-72164-550-778-jpg/keystamp=1542150900-8af65f270f;fileindex=40438349;xres=org/564177_427454350624706_1972332091_n.jpg
[0027] https://e-hentai.org/s/165578cbd2/883632-467 ---> http://210.222.101.138:6969/h/165578cbd2a96f7f926c708d880bb95c881851c3-64690-960-729-jpg/keystamp=1542150900-3979e31a4a;fileindex=40438350;xres=org/577024_422879741082167_2081804360_n.jpg
[0028] https://e-hentai.org/s/9c8e600857/883632-468 ---> http://153.164.217.52:62311/h/9c8e60085771b2de9c0dbbd8ac602547d1a43d08-82103-800-566-jpg/keystamp=1542150900-1b2aaaf5d1;fileindex=40438351;xres=org/577613_513900121980128_883645644_n.jpg
[0029] https://e-hentai.org/s/b921d32519/883632-469 ---> http://142.54.171.114:1028/h/b921d325194a478c139ee317f365251bb7d268c0-113437-600-847-jpg/keystamp=1542150900-efd593fdb6;fileindex=40438352;xres=org/578166_385570804813061_1359614238_n.jpg
[0030] https://e-hentai.org/s/9235fbdf88/883632-470 ---> http://140.113.66.20:57975/h/9235fbdf883bcbb301892a56f13866d31bbf5436-83546-960-720-jpg/keystamp=1542150900-1beacaa708;fileindex=40438353;xres=org/581648_538694229500717_464136195_n.jpg
[0031] https://e-hentai.org/s/1969a9b2a7/883632-471 ---> http://112.164.144.213:46534/h/1969a9b2a7dca7a241582df1cb1a18c4dd40adaa-55500-960-576-jpg/keystamp=1542150900-0ac0e0a160;fileindex=40438354;xres=org/58267_471019906268150_2099544014_n.jpg
[0032] https://e-hentai.org/s/954b335a82/883632-472 ---> http://180.24.108.182:10428/h/954b335a82297d3536013dabb91e68345ca8147d-78715-500-707-jpg/keystamp=1542150900-5951c2d858;fileindex=40438355;xres=org/582727_421307177906090_838589252_n.jpg
[0033] https://e-hentai.org/s/9a82711a02/883632-473 ---> http://211.178.21.95:1999/h/9a82711a02e62e846cc09f64942b9c9889600d34-34576-600-828-jpg/keystamp=1542150900-deb2f4e89b;fileindex=40438356;xres=org/598760_555167757853364_25197618_n.jpg
[0034] https://e-hentai.org/s/c801424439/883632-474 ---> http://220.92.54.121:1024/h/c8014244397edbf428a255702a68987766bbcd30-71746-603-875-jpg/keystamp=1542150900-5fbe96fd58;fileindex=40438357;xres=org/600029_413171485386326_2635834_n.jpg
[0035] https://e-hentai.org/s/02229f1849/883632-475 ---> http://182.227.147.73:1024/h/02229f1849a0f8f307ad7b01cc757e99354103ee-47409-800-365-jpg/keystamp=1542150900-06d31c4cde;fileindex=40438358;xres=org/603942_449150895121718_905622773_n.jpg
[0036] https://e-hentai.org/s/a27b2eb5bf/883632-476 ---> http://211.195.182.79:56133/h/a27b2eb5bf62c3e47cabe2b7a1255f6746deacb2-44838-800-566-jpg/keystamp=1542150900-cf30d37673;fileindex=40438359;xres=org/604057_444161272287347_992367043_n.jpg
[0037] https://e-hentai.org/s/b576367dbe/883632-477 ---> http://14.49.100.116:58198/h/b576367dbe7716eca94dcf31dfdf432ce92f1c4e-37764-477-648-jpg/keystamp=1542150900-739b11222a;fileindex=40438360;xres=org/61468_430294293674045_2019436715_n.jpg
[0038] https://e-hentai.org/s/3702eae944/883632-478 ---> http://211.195.182.79:56133/h/3702eae9441d2fd199eacd36bdb770d780ec3b18-107647-960-740-jpg/keystamp=1542150900-15065846ac;fileindex=40438361;xres=org/61751_482138868489587_1660642450_n.jpg
[0039] https://e-hentai.org/s/51a800caa0/883632-479 ---> http://121.144.133.97:6556/h/51a800caa0e22b58abb0b3d4bf706bbe5b14f32f-16169-292-777-jpg/keystamp=1542150900-6470fcf34b;fileindex=40438362;xres=org/64452_503455869691220_591144164_n.jpg
[0040] https://e-hentai.org/s/d74c54e614/883632-480 ---> http://36.224.209.80:21731/h/d74c54e61410149c594fa2e58e7dd3cf8dcc3657-82749-500-707-jpg/keystamp=1542150900-26b01d4fee;fileindex=40438363;xres=org/64537_443671849002956_513903838_n.jpg


[Messages]
********************************
Gallery number : 883632
Number of Threads : 64
********************************
Traceback (most recent call last):
File "hitomi_downloader", line 1087, in download_hitomi
File "hitomi_downloader", line 136, in pop_img
File "downloader", line 239, in read_html
Exception: 404

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1117, in download_hitomi
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1087, in download_hitomi
File "hitomi_downloader", line 136, in pop_img
File "downloader", line 239, in read_html
Exception: 404

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1117, in download_hitomi
Exception: 404

ehen_imgs(ex:False, url:https://exhentai.org/g/883632/deb86d946f/?p=11)
#### https://e-hentai.org ----> https://e-hentai.org/g/883632/deb86d946f/?p=11
FINAL SERVER : ehen
ehen_url : https://e-hentai.org/g/883632/deb86d946f/?p=11
imgs: 40
get_title_ehen: https://e-hentai.org/g/883632/deb86d946f/?p=11, {}
E-Hentai: https://e-hentai.org/g/883632/deb86d946f/?p=11

Title :
[Krenz] Studies by Krenz (883632)

skip zip
Compress... \537527_459697674067040_1901199065_n.jpg
Compress... \538431_396855887017886_1372384632_n.jpg
Compress... \540223_351901784846630_1296692196_n.jpg
Compress... \540623_371082712928537_288966418_n.jpg
Compress... \540795_404929346210540_1557070182_n.jpg
Compress... \541516_600375413332598_1532633087_n.jpg
Compress... \542284_475364309167043_1797679194_n.jpg
Compress... \543828_472546116115529_1959252119_n.jpg
Compress... \544083_508345979202209_61662267_n.jpg
Compress... \547047_441121479257993_1521021812_n.jpg
Compress... \547415_502283033141837_418385236_n.jpg
Compress... \548318_370919562944852_1966120502_n.jpg
Compress... \548426_432665353436939_800511540_n.jpg
Compress... \549521_421251991244942_709914624_n.jpg
Compress... \549922_491570500879757_848839612_n.jpg
Compress... \551327_507171892652951_1047984873_n.jpg
Compress... \553433_554882447881895_478811800_n.jpg
Compress... \557435_427425877294220_817507493_n.jpg
Compress... \557858_443841665652641_207920821_n.jpg
Compress... \558009_502357219801085_2137581669_n.jpg
Compress... \559091_541830782520395_1106236485_n.jpg
Compress... \560681_392995780737230_851825615_n.jpg
Compress... \562271_382861798417295_1054220256_n.jpg
Compress... \563038_487533477950126_675186307_n.jpg
Compress... \563263_407752899261518_518756252_n.jpg
Compress... \564177_427454350624706_1972332091_n.jpg
Compress... \577024_422879741082167_2081804360_n.jpg
Compress... \577613_513900121980128_883645644_n.jpg
Compress... \578166_385570804813061_1359614238_n.jpg
Compress... \581648_538694229500717_464136195_n.jpg
Compress... \58267_471019906268150_2099544014_n.jpg
Compress... \582727_421307177906090_838589252_n.jpg
Compress... \598760_555167757853364_25197618_n.jpg
Compress... \600029_413171485386326_2635834_n.jpg
Compress... \603942_449150895121718_905622773_n.jpg
Compress... \604057_444161272287347_992367043_n.jpg
Compress... \61468_430294293674045_2019436715_n.jpg
Compress... \61751_482138868489587_1660642450_n.jpg
Compress... \64452_503455869691220_591144164_n.jpg
Compress... \64537_443671849002956_513903838_n.jpg
done : https://exhentai.org/g/883632/deb86d946f/?p=11

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
