### ISSUE TITLE
최신버전 유튜브 다운로드에 문제가 생겼습니다

### ISSUE THREAD

**Issue by JSPN1** [KurtBestor/Hitomi-Downloader-issues#235]
일부는 다운로드가 되고 일부는 계속 안되는데

계속 안되는 목록중 하나 우클릭 후 정보를 가져왔습니다

Fail: youtube_https://youtu.be / DrKrSBoNqBg

gal_num: https://youtu.be/DrKrSBoNqBg
dir: 
zip: 
type: youtube
artist: None
url: https://youtu.be/DrKrSBoNqBg
valid: False
done: False
range: None
range_p: None
single: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 1746, in download_hitomi
File "hitomi_downloader", line 914, in download_youtube
File "youtube_downloader", line 86, in get_videos
File "FUUUUCK\__main__", line 83, in __init__
File "FUUUUCK\__main__", line 92, in prefetch_init
File "FUUUUCK\__main__", line 127, in init
File "FUUUUCK\mixins", line 40, in apply_signature
File "FUUUUCK\cipher", line 245, in get_signature
File "FUUUUCK\cipher", line 64, in get_transform_plan
File "FUUUUCK\cipher", line 40, in get_initial_function_name
File "FUUUUCK\helpers", line 39, in regex_search
RegexMatchError: regex pattern ("signature",\s?([a-zA-Z0-9$]+)\() had zero matches

Fail: youtube

done : https://youtu.be/DrKrSBoNqBg

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
테스트 부탁드려요.

**Comment by JSPN1** [comment]
> https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
> 테스트 부탁드려요.

해결됐네요 감사합니다
