### ISSUE TITLE
마루마루 시 문제

### ISSUE THREAD

**Issue by locien10** [KurtBestor/Hitomi-Downloader-issues#251]
비밀번호가 걸려있는 만화의 경우에 다운로드시에 크롬드라이버가 열렸다가 비밀번호를 치기도 전에 종료되어버립니다. 2.5 이전에 2.4에도 문제가 있었고, 기억하기로는 2.4도 처음엔 다운로드가 되었는데 어느 이후부터 안되던걸로 기억을 하고 있습니다.... 뭐가 문제일까요.. 아래는 에러 코드인데...

[Messages]
[172] 하레혼(하렘혼) 172화: http://wasabisyrup.com/archives/HtdlaZvUqVc
Traceback (most recent call last):
File "recaptcha.pyo", line 91, in get
File "selenium\webdriver\remote\webdriver.pyo", line 323, in get
File "selenium\webdriver\remote\webdriver.pyo", line 309, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 460, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 484, in _request
File "httplib.pyo", line 719, in getresponse
File "httplib.pyo", line 271, in begin
File "httplib.pyo", line 234, in _read_status
File "socket.pyo", line 373, in readline
timeout: timed out

Traceback (most recent call last):
File "recaptcha.pyo", line 91, in get
File "selenium\webdriver\remote\webdriver.pyo", line 323, in get
File "selenium\webdriver\remote\webdriver.pyo", line 309, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 460, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 484, in _request
File "httplib.pyo", line 719, in getresponse
File "httplib.pyo", line 271, in begin
File "httplib.pyo", line 234, in _read_status
File "socket.pyo", line 373, in readline
timeout: timed out

Traceback (most recent call last):
File "maru_downloader", line 99, in read
File "maru_downloader", line 332, in get_imgs_all
File "bs4\__init__", line 246, in __init__
TypeError: object of type 'NoneType' has no len()

stop
Traceback (most recent call last):
File "maru_downloader", line 99, in read
File "maru_downloader", line 332, in get_imgs_all
File "bs4\__init__", line 246, in __init__
TypeError: object of type 'NoneType' has no len()

Fail: maru

stop
done : http://marumaru.in/b/manga/60545

**Comment by locien10** [comment]
여러 만화를 다운받아보니 모든 리캡챠에서 저러는게 아니라 몇몇 만화에서 그러는 것 같고 리캡챠 걸린만화중에서는 일부는 앞부분은 잘 다운 받다가 뒷부분에서 갑자기 크롬드라이버가 종료되고 에러가 뜨기도 했습니다. 시간 날때 다시 시도해보고 어떤 특징이 있었는지 다시 말씀 드리도록 하겠습니다...

**Comment by KurtBestor** [comment]
혹시 테스트하실거면 다음 파일로 테스트 부탁드려요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by locien10** [comment]
요즘 바빠서 오늘 테스트 해봤는데 카스퍼스키 백신 문제였던 것 같습니다. 백신 보호를 끄고 했더니 잘 되네요... 이전버전을 끄고 테스트해보진 않았습니다.

**Comment by KurtBestor** [comment]
백신 보호 키고 다시 테스트 해주실 수 있나요? 테스트 버전에서 문제가 해결된 건지, 아니면 백신 문제인지 판단을 하기가 어려워서요.

**Comment by locien10** [comment]
요즘 바빠서 오늘 시도를 해봤습니다. 저번에는 어떻게 잘 다운이 됐었는데 이번에는 크롬드라이버는 켜졌는데 해당화로 연결이 되지가 않네요. 몇몇곳에서 에러나긴 했는데 그 중 하나 알고 있는 것은 하렘혼 172화입니다. 이 부분은 여러번 시도를 하고 말씀을 드리도록 하겠습니다.

[Messages]
[1] 하레혼(하렘혼) 171화: http://wasabisyrup.com/archives/nSWWo5rcJFw
[2] 하레혼(하렘혼) 172화: http://wasabisyrup.com/archives/HtdlaZvUqVc
Traceback (most recent call last):
File "recaptcha.pyo", line 90, in get
File "selenium\webdriver\remote\webdriver.pyo", line 323, in get
File "selenium\webdriver\remote\webdriver.pyo", line 309, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 460, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 484, in _request
File "httplib.pyo", line 719, in getresponse
File "httplib.pyo", line 271, in begin
File "httplib.pyo", line 234, in _read_status
File "socket.pyo", line 373, in readline
timeout: timed out

Traceback (most recent call last):
File "recaptcha.pyo", line 90, in get
File "selenium\webdriver\remote\webdriver.pyo", line 323, in get
File "selenium\webdriver\remote\webdriver.pyo", line 309, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 460, in execute
File "selenium\webdriver\remote\remote_connection.pyo", line 484, in _request
File "httplib.pyo", line 719, in getresponse
File "httplib.pyo", line 271, in begin
File "httplib.pyo", line 234, in _read_status
File "socket.pyo", line 373, in readline
timeout: timed out

Traceback (most recent call last):
File "maru_downloader", line 99, in read
File "maru_downloader", line 332, in get_imgs_all
File "bs4\__init__", line 246, in __init__
TypeError: object of type 'NoneType' has no len()

stop
Traceback (most recent call last):
File "maru_downloader", line 99, in read
File "maru_downloader", line 332, in get_imgs_all
File "bs4\__init__", line 246, in __init__
TypeError: object of type 'NoneType' has no len()

Fail: maru

stop
done : http://marumaru.in/b/manga/60545

오늘은 이런 에러코드가 뜨네요..

**Comment by locien10** [comment]
아 백신을 켜도 꺼도 양쪽다 문제가 있습니다

**Comment by KurtBestor** [comment]
테스트 버전으로 실행한 것 맞나요?

다운로더에서 `Ctrl + Alt + C` 눌러서 콘솔 띄우신 다음 `__import__('socket').getdefaulttimeout()` 입력하고 Enter 누른다음 나오는 내용 알려주세요.

**Comment by locien10** [comment]
아 백신 문제가 아닌가 봅니다...... 지금 뭐가 문제인지를 정확하게 모르겠네요 지금은 5번정도 시도해봤는데 3번은 문제없이 잘 되고 2번은 로딩상태로 몇분간 대기하길래 작업을 종료하였습니다. 아까 실행했을 때도 성공은 했는데 테스트버전에서 수정하신것 같은데 한번 172화가 떴다가 바로 종료되고 이후 다시 172화 비밀번호 입력란이 떴었습니다. 아까 실패했을 때의 경우는 지금 다운로드가 되고 있어 잘 모르겠네요.... 서버의 문제인지 다른 만화나 다른화는 이상이 없는데 특정 화에서만 에러가 생기곤 합니다. 시간 날때 한번씩 해보고 다운이 안되는 경우가 확인되면 그 때 다시 말씀드리겠습니다. ㅜㅜ 항상 잘쓰고 있습니다 감사합니다

**Comment by locien10** [comment]
먼저 콘솔에서 나온 값은 24.0이구요.
다운로드는 여전히 실패하기도 하고 성공하기도 합니다. 서버 상태의 문제인건지 리캡챠 종류에 따른 문제인건지....는 모르겠네요...

**Comment by locien10** [comment]
단순히 한번 시도해 본것은 아니고 약 10번쯤 같은 내용으로 시도를 해본 것 같네요.... 실패는 여전히 같은 방식으로 입력하기도 전에 종료되버리는 문제, 크롬드라이버가 로딩을 기다리다가 크롬드라이버에 로딩이 안되는 경우가 있었습니다. 물론 정상적으로 성공하기도 합니다....

**Comment by locien10** [comment]
http://marumaru.in/b/manga/182179 만화 23화를 이어 다운받던 중
크롬에서 비밀번호를 입력 후 리캡챠가 떠서 골라야하는데 고르기도 전에 새로고침되서 비밀번호를 다시 입력하고 다시 고르려고 하면 새로고침 반복을 여러번 한 뒤에 크롬이 종료되어버립니다. 심지어 다운로드 실패인데도 다운로드가 성공이라고 떠버리네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
