### ISSUE TITLE
마루마루 다운로드시 Invalid가 뜹니다.

### ISSUE THREAD

**Issue by sendyourjunkmails** [KurtBestor/Hitomi-Downloader-issues#267]
다운로드 창에 https://marumaru.in/b/manga/147490 이라고 붙여넣고 다운로드 버튼 눌렀는데, 좀 있다가 빨간 글씨로 이렇게 뜹니다:
Invalid : [maru] http://marumaru.in / b / manga / 148089

다음은 Task info의 내용입니다.
도와주시면 정말 감사드리겠습니다...

Invalid : [maru] http://marumaru.in / b / manga / 148089

gal_num: http://marumaru.in/b/manga/148089
dir: 
zip: 
type: maru
artist: None
url: http://marumaru.in/b/manga/148089
valid: False
done: False
range: None
range_p: None
single: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "maru_downloader", line 57, in init
File "constants", line 510, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 506, in wrapper
File "maru_downloader", line 386, in read_html
File "downloader", line 287, in read_html
Exception: 403

Traceback (most recent call last):
File "maru_downloader", line 57, in init
File "constants", line 510, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 506, in wrapper
File "maru_downloader", line 386, in read_html
File "downloader", line 287, in read_html
Exception: 403

Traceback (most recent call last):
File "maru_downloader", line 57, in init
File "constants", line 510, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 506, in wrapper
File "maru_downloader", line 386, in read_html
File "downloader", line 287, in read_html
Exception: 403

Traceback (most recent call last):
File "maru_downloader", line 57, in init
File "constants", line 510, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 506, in wrapper
File "maru_downloader", line 386, in read_html
File "downloader", line 287, in read_html
Exception: 403

stop
Traceback (most recent call last):
File "maru_downloader", line 57, in init
File "constants", line 510, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 506, in wrapper
File "maru_downloader", line 386, in read_html
File "downloader", line 287, in read_html
Exception: 403

Fail: maru

stop
done : http://marumaru.in/b/manga/148089

**Comment by KurtBestor** [comment]
Duplicate of #208
