### ISSUE TITLE
안녕하세요. 인스타그램 다운로드가 안되서 글을 남깁니다.

### ISSUE THREAD

**Issue by an101** [KurtBestor/Hitomi-Downloader-issues#284]
안녕하세요.

좋은 프로그램을 만들어 주신것에 우선 감사의 말씀을 드립니다. 

글의 제목처럼 인스타그램 다운로드가 되지 않아서 작업 정보와 함께 어떻게 하면

될지 궁금해서 질문을 드립니다.

작업 정보는 다음과 같습니다.

Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 258, in get_imgs
Exception: Too short
- my_sweet_dove

gal_num: https://www.instagram.com/my_sweet_dove/
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/my_sweet_dove
valid: False
done: False
range: None
range_p: None
single: False
time: 1541906183.88 (Nov 10)

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 258, in get_imgs
Exception: Too short

Fail: insta

stop
done : https://www.instagram.com/my_sweet_dove/

다른 인스타그램 주소에서는 다운로드를 할 수 있었고 다음과 같은 작업정보가 
나왔습니다.

LEEHEE 이희은 (insta_leehee.eun)

gal_num: https://www.instagram.com/leehee.eun/
dir: hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)
zip: 
type: insta
artist: None
url: https://www.instagram.com/leehee.eun
valid: True
done: True
range: None
range_p: None
single: False
time: 1541906078.69 (Nov 10)

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\[18-11-10] BqAkE5JHGzE_p0.jpg
[0002] hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\[18-11-10] BqAVmfHnaAS_p0.mp4
[0003] hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\[18-11-10] BqAU9Pgn9FO_p0.mp4
[0004] hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\[18-11-10] BqAUG5-H3pd_p0.mp4
[0005] hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\[18-11-10] BqAS4dgHz0c_p0.mp4
[0006] hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\[18-11-10] BqAOfNiHEPu_p0.jpg
[0007] hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\[18-11-10] Bp_uAsHngRI_p0.jpg

[URLs]
[0001] LazyUrl(https://www.instagram.com/p/BqAkE5JHGzE/) ---> https://scontent-yyz1-1.cdninstagram.com/vp/d33fe6ba3594cafe5c698d603aeb1bd2/5C869902/t51.2885-15/e35/44425904_367130500689429_2715672693705068588_n.jpg
[0002] LazyUrl(https://www.instagram.com/p/BqAVmfHnaAS/) ---> https://scontent-yyz1-1.cdninstagram.com/vp/2e9b4f89315d7baf11caf849b2dae312/5BE9C29D/t50.2886-16/45673510_570618006710076_5184108526514995200_n.mp4
[0003] LazyUrl(https://www.instagram.com/p/BqAU9Pgn9FO/) ---> https://scontent-yyz1-1.cdninstagram.com/vp/2ca1f5efae9a1883e9507e11d870eddc/5BEA9C5A/t50.2886-16/45782867_1016669558505686_583227619307159552_n.mp4
[0004] LazyUrl(https://www.instagram.com/p/BqAUG5-H3pd/) ---> https://scontent-yyz1-1.cdninstagram.com/vp/fc53f1edd265061bce77e50dd3f0fcbb/5BEA21FD/t50.2886-16/45622341_2015424421837263_207289660169256960_n.mp4
[0005] LazyUrl(https://www.instagram.com/p/BqAS4dgHz0c/) ---> https://scontent-yyz1-1.cdninstagram.com/vp/66f8fb845b21cd11fa222761cd5988b2/5BEAB2A3/t50.2886-16/45507386_756802301327982_8882812247320035328_n.mp4
[0006] LazyUrl(https://www.instagram.com/p/BqAOfNiHEPu/) ---> https://scontent-yyz1-1.cdninstagram.com/vp/0183316406ccdc3a70c17fdb8bf3311d/5C7CA2FA/t51.2885-15/e35/43914116_255439011807085_7591035289299141420_n.jpg
[0007] LazyUrl(https://www.instagram.com/p/Bp_uAsHngRI/) ---> https://scontent-yyz1-1.cdninstagram.com/vp/fe900c28bb1583972719e28cdb7c63fd/5C782AB2/t51.2885-15/e35/43709209_338862130211254_4975363750936897787_n.jpg

[Messages]
makedirs: hitomi_downloaded_insta\LEEHEE 이희은 (insta_leehee.eun)\
done : https://www.instagram.com/leehee.eun/

혹시 "valid: True" 부분에서 문제가 있는것인가요?

감사드립니다.

**Comment by KurtBestor** [comment]
비공개 계정이네요. 현재 비공개 계정 다운로드는 지원하지 않아요.

**Comment by an101** [comment]
안녕하세요, KurtBestor님.

그렇군요. 친절하게 답변을 보내주셔서 감사드립니다.

혹시 괜찮다면 왜 이름을 Hitomi 다운로더 라고 정하셨는지 여쭤봐도 될까요?

다시 한번 감사드립니다.


________________________________
보낸 사람: Kurt Bestor <notifications@github.com>
보낸 날짜: 2018년 11월 12일 월요일 오전 2:35
받는 사람: KurtBestor/Hitomi-Downloader-issues
참조: an101; Author
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 안녕하세요. 인스타그램 다운로드가 안되서 글을 남깁니다. (#284)


비공개 계정이네요. 현재 비공개 계정 다운로드는 지원하지 않아요.

**Comment by KurtBestor** [comment]
첨에 Hitomi.la 에서만 다운로드 하는 거라서 이름을 그렇게 지었다가 굳어졌어요.

**Comment by an101** [comment]
그랬었군요. 쓰면서 항상 궁금했어서 여쭤봤습니다.

답변 감사드리고 좋은 한 주 보내세요.


________________________________
보낸 사람: Kurt Bestor <notifications@github.com>
보낸 날짜: 2018년 11월 12일 월요일 오후 11:30
받는 사람: KurtBestor/Hitomi-Downloader-issues
참조: an101; Author
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 안녕하세요. 인스타그램 다운로드가 안되서 글을 남깁니다. (#284)


첨에 Hitomi.la 에서만 다운로드 하는 거라서 이름을 그렇게 지었다가 굳어졌어요.
