### ISSUE TITLE
히토미, 익헨 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by crosscount** [KurtBestor/Hitomi-Downloader-issues#291]
Invalid 라고 뜨면서 다운로드가 계속 실패하고 다운로드 정보에는 다음과 같이 뜹니다.
Traceback (most recent call last):
File "hitomi_downloader", line 1087, in download_hitomi
File "hitomi_downloader", line 136, in pop_img
File "downloader", line 287, in read_html
Exception: None

Traceback (most recent call last):
File "hitomi_downloader", line 1109, in download_hitomi
File "hitomi_downloader", line 179, in pop_img_hiyobi
File "downloader", line 287, in read_html
Exception: None

get imgs from e(x)hentai: 1310015
ehen_imgs(ex:False, url:1310015)
find_ehen(id:1310015, ex:False)
Traceback (most recent call last):
File "hitomi_downloader", line 1123, in download_hitomi
File "hitomi_downloader", line 1706, in ehen_imgs
File "hitomi_downloader", line 1574, in find_ehen
File "downloader", line 287, in read_html
Exception: None

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1135, in download_hitomi
Exception: None

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
