### ISSUE TITLE
유튜브 몇몇 영상이 다운이 안되네요

### ISSUE THREAD

**Issue by rlacks1237** [KurtBestor/Hitomi-Downloader-issues#306]
정보창 긁어왔습니다
Invalid : [youtube] https://www.youtube.com / watch?v=XmiDRrUSnKU

gal_num: https://www.youtube.com/watch?v=XmiDRrUSnKU
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=XmiDRrUSnKU
valid: False
done: False
range: None
range_p: None
single: True
time: 1542905781.06 (Nov 23)

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\冯提莫 《미려적 신화》 美丽的神话 성룡,김희선.mp4

[URLs]
[0001] https://r5---sn-ab02a0nfpgxapox-20ne.googlevideo.com/videoplayback?ei=t9_2W-fgFdXyqQHdlK_YAg&ip=115.138.114.93&usequic=no&id=o-AH3zpLyrxDKpP6osA5YSYSM-FDx5mlJbnVh1czGAQKCy&sparams=aitags,dur,ei,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,otf,otfp,pcm2cms,pl,requiressl,source,usequic,expire&expire=1542927383&fvip=2&pcm2cms=yes&pl=24&keepalive=yes&requiressl=yes&ipbits=0&mime=video/mp4&key=yt6&itag=136&otf=1&aitags=133,134,135,136,137,160&otfp=1&lmt=1542900558145653&initcwndbps=1262500&c=WEB&mm=31,29&source=yt_otf&mn=sn-ab02a0nfpgxapox-20ne,sn-ab02a0nfpgxapox-bh2r&mt=1542905662&mv=m&ms=au,rdu&dur=0.000&signature=6BE2F6AC36FCC81683CB24D4DE81A5EAA6ACA705.55F15AEDE0B4B2F87D618AD4D803B7730CA4EA34

[Messages]
Resolution: 720p

Fail : hitomi_downloaded_youtube\冯提莫 《미려적 신화》 美丽的神话 성룡,김희선.mp4
Traceback (most recent call last):
File "downloader", line 527, in download
File "urllib2", line 154, in urlopen
File "urllib2", line 435, in open
File "urllib2", line 548, in http_response
File "urllib2", line 473, in error
File "urllib2", line 407, in _call_chain
File "urllib2", line 556, in http_error_default
HTTPError: HTTP Error 404: Not Found

Download audio: https://r5---sn-ab02a0nfpgxapox-20ne.googlevideo.com/videoplayback?ei=t9_2W-fgFdXyqQHdlK_YAg&ip=115.138.114.93&usequic=no&id=o-AH3zpLyrxDKpP6osA5YSYSM-FDx5mlJbnVh1czGAQKCy&sparams=clen,dur,ei,gir,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,otfp,pcm2cms,pl,requiressl,source,usequic,expire&expire=1542927383&mt=1542905662&gir=yes&fvip=2&pcm2cms=yes&pl=24&keepalive=yes&requiressl=yes&ipbits=0&mime=audio/mp4&key=yt6&itag=140&otfp=1&lmt=1542900524960636&initcwndbps=1262500&c=WEB&mm=31,29&source=youtube&mn=sn-ab02a0nfpgxapox-20ne,sn-ab02a0nfpgxapox-bh2r&clen=4372351&mv=m&ms=au,rdu&txp=2211222&dur=270.117&signature=D5795A26DAA50792B6ADE33E283C1D4CE8F69D35.106DED3324ADC25D4000728E32F20B449B4F42D5
Convert: X:\Hobby\hitomi\hitomi_downloaded_youtube\冯提莫 《미려적 신화》 美丽的神话 성룡,김희선.mp4
stop
Traceback (most recent call last):
File "utils", line 403, in start
File "utils", line 522, in start_
File "youtube_downloader", line 109, in post_processing
File "ffmpeg", line 68, in merge
WindowsError: [Error 2] 

Fail: youtube

done : https://www.youtube.com/watch?v=XmiDRrUSnKU

**Comment by rlacks1237** [comment]
같은 내용같아서 다른건 생략했습니다

**Comment by KurtBestor** [comment]
720p 영상이 404 뜨는데, 다른 다운로더도 받지 못하네요. 그나마 좋은 영상으로 받게 했어요.
지금은 720p 영상도 다운로드 되네요. 일시적인 유튜브 서버 문제인 듯 해요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by rlacks1237** [comment]
방금막 테스트했습니다 안되던거 다 되네요!
감사합니다
