### ISSUE TITLE
2.5a 버전 오류 및 건의

### ISSUE THREAD

**Issue by 4w97euiosha** [KurtBestor/Hitomi-Downloader-issues#311]
1. 수동설치로 2.5a 실행하고 나서 종료 후 다시 실행이 안됩니다. 다시 2.5 버전으로 덮어 씌었는데도 안되고요.
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 5169, in <module>
  File "hitomi_downloader_GUI.py", line 2150, in set_slider
  File "MySlider.pyo", line 152, in setMaximum
TypeError: QAbstractSlider.setMaximum(int): argument 2 has unexpected type 'unicode'

2. 마침 2.2 버전 컴퓨터에 있어서 해보니깐 이건 실행은 되는데, 검색 데이터 다운로드가 안되네요.
Traceback (most recent call last):
  File "hitomi_searcher", line 149, in download_json
  File "hitomi_searcher", line 302, in download_json_
  File "downloader", line 151, in read_html
Exception: 404

3. 2.5a 버전 잠시 해보니
파일 다운로드 받고 나서, 그 받은 파일 폴더를 다른 곳으로 옮긴 뒤, 다시 그 파일을 폴더 열기 하면 '내 문서' 가 열립니다.
전에는 해당 파일이 다운로드 폴더에 없으면 아예 안열렸었는데, 자꾸 내 문서가 열어지니깐 개인적으로 불편해진 것 같습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by 4w97euiosha** [comment]
실행&종료, 검색 데이터 다운로드, 다운로드 잘 됩니다.
3번 문제는 크게 기대 안했는데 해결해주셨네요.
정말 감사합니다.
