### ISSUE TITLE
Log file에 이러한 오류가뜸 

### ISSUE THREAD

**Issue by LoveBlonde** [KurtBestor/Hitomi-Downloader-issues#320]
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 2672, in closeEvent
AttributeError: 'Thread' object has no attribute '_kill_accepted'
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 5169, in <module>
  File "hitomi_downloader_GUI.py", line 2150, in set_slider
  File "MySlider.pyo", line 152, in setMaximum
TypeError: QAbstractSlider.setMaximum(int): argument 2 has unexpected type 'unicode'

**Comment by LoveBlonde** [comment]
#311  에서 해결된거네요 closed 부탁드립니다
