### ISSUE TITLE
호두 사이트 스크립트 문의입니다.

### ISSUE THREAD

**Issue by vlvk3144** [KurtBestor/Hitomi-Downloader-issues#340]
호두 사이트 주소가 현재 https://hodu19.com 로바뀌었는데 

기존 스크립트는 12로 되어있습니다. 숫자를 바꿔수정해봤는데 작동하지 않네요

혹시 수정법을 배울수 있을까 문의드립니다.

**Comment by KurtBestor** [comment]
수정 안 해도 저는 잘 되네요. 실패한 작업 우클릭해서 `정보... (I)` 눌러서 나오는 내용 보여주세요.

**Comment by vlvk3144** [comment]
Invalid : [hodu] https://hodu19.com / webtoon / list / 30

gal_num: https://hodu19.com/webtoon/list/30
dir: 
zip: 
type: hodu
artist: None
url: https://hodu19.com/webtoon/list/30
valid: False
done: False
range: None
range_p: None
single: False
time: 1544133669.7 (Dec 7)


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 403, in start
File "utils", line 414, in start_
File "dynamic_module_3", line 84, in read
File "phantomjs", line 46, in start
File "selenium\webdriver\phantomjs\webdriver", line 52, in __init__
File "selenium\webdriver\common\service", line 93, in start
File "subprocess", line 200, in __init__
File "subprocess", line 375, in _execute_child
WindowsError: [Error 193] %1은(는) 올바른 Win32

Fail: hodu

done : https://hodu19.com/webtoon/list/30

**Comment by KurtBestor** [comment]
혹시 XP 쓰세요?

**Comment by vlvk3144** [comment]
윈도우 10 사용합니다 다른 스크립트는 모두 정상적으로 작동합니다 호두 사이트는 드래그가 안되서 윈도우 주소창 쳐서 복사 붙여넣기를 했습니다.

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 띄우고 `__import__('phantomjs').get()` 입력하고 `Enter` 친 다음 나오는 내용 알려주세요.

**Comment by vlvk3144** [comment]
재설치를 통해 해결했습니다. 답변감사합니다 ^^
