### ISSUE TITLE
인스타그램 다운로드이 되지 않아 질문을 드리고자 합니다.

### ISSUE THREAD

**Issue by an101** [KurtBestor/Hitomi-Downloader-issues#362]
안녕하세요.

프로그램을 계속해서 만들어주시는 것에 감사드립니다.

인스타그램 다운로드가 되지 않아서 질문을 드리고자 합니다.

작업 정보는 다음과 같습니다.

Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 182, in get_imgs
File "phantomjs", line 46, in start
File "selenium\webdriver\phantomjs\webdriver", line 52, in __init__
File "selenium\webdriver\common\service", line 93, in start
File "subprocess", line 200, in __init__
File "subprocess", line 375, in _execute_child
WindowsError: [Error 193] %1은(는) 올바른 Win32
- topjsj

gal_num: https://www.instagram.com/topjsj
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/topjsj
valid: True
done: True
range: None
range_p: None
single: False
time: 1545400160.66 (Dec 21)

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 182, in get_imgs
File "phantomjs", line 46, in start
File "selenium\webdriver\phantomjs\webdriver", line 52, in __init__
File "selenium\webdriver\common\service", line 93, in start
File "subprocess", line 200, in __init__
File "subprocess", line 375, in _execute_child
WindowsError: [Error 193] %1은(는) 올바른 Win32

Fail: insta

stop
done : https://www.instagram.com/topjsj

다시 한번 감사드립니다.

**Comment by KurtBestor** [comment]
윈도 어떤 것 쓰시나요?
실행파일과 같은 폴더에 phantomjs.exe가 있을텐데 지우고 다시 시도해보세요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/340#issuecomment-445045932

**Comment by an101** [comment]
안녕하세요.

윈도xp를 쓰고 있습니다.

말씀하신대로 phantomjs.exe를 지우고 다시 시도해 봤는데

다운로드는 되지 않았고 작업정보는 다음과 같습니다:


Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 182, in get_imgs
File "phantomjs", line 46, in start
File "selenium\webdriver\phantomjs\webdriver", line 52, in __init__
File "selenium\webdriver\common\service", line 93, in start
File "subprocess", line 200, in __init__
File "subprocess", line 375, in _execute_child
WindowsError: [Error 193] %1은(는) 올바른 Win32
- ya9579

gal_num: https://www.instagram.com/ya9579/
dir:
zip:
type: insta
artist: None
url: https://www.instagram.com/ya9579
valid: False
done: False
range: None
range_p: None
single: False
time: 1545458060.62 (Dec 22)


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 182, in get_imgs
File "phantomjs", line 46, in start
File "selenium\webdriver\phantomjs\webdriver", line 52, in __init__
File "selenium\webdriver\common\service", line 93, in start
File "subprocess", line 200, in __init__
File "subprocess", line 375, in _execute_child
WindowsError: [Error 193] %1은(는) 올바른 Win32

Fail: insta

stop
done : https://www.instagram.com/ya9579/

그리고 말씀해주신 링크에서 알려주신대로 콘솔을 띄우고
__import__('phantomjs').get() 입력하고 Enter를 친 후 나오는
내용은 다음과 같습니다:


'phantomjs.exe'


감사합니다.






________________________________
보낸 사람: Kurt Bestor <notifications@github.com>
보낸 날짜: 2018년 12월 21일 금요일 오후 8:51
받는 사람: KurtBestor/Hitomi-Downloader-issues
참조: an101; Author
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 인스타그램 다운로드이 되지 않아 질문을 드리고자 합니다. (#362)


윈도 어떤 것 쓰시나요?
실행파일과 같은 폴더에 phantomjs.exe가 있을텐데 지우고 다시 시도해보세요.

참고해주세요: #340 (comment)<https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/340#issuecomment-445045932>

**Comment by KurtBestor** [comment]
phantomjs.exe 더블클릭해서 실행해보세요. 어떻게 뜨나요?

**Comment by KurtBestor** [comment]
XP 쓰시나요?

**Comment by an101** [comment]
안녕하세요.

예, XP를 쓰고 있습니다.

감사드립니다.

________________________________
보낸 사람: Kurt Bestor <notifications@github.com>
보낸 날짜: 2018년 12월 22일 토요일 오전 4:30
받는 사람: KurtBestor/Hitomi-Downloader-issues
참조: an101; Author
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 인스타그램 다운로드이 되지 않아 질문을 드리고자 합니다. (#362)


XP 쓰시나요?

**Comment by KurtBestor** [comment]
인스타그램 긁을 때 [PhantomJS](https://ko.wikipedia.org/wiki/PhantomJS) v2.1.1 쓰는데 이게 XP를 지원 안해요..

v1.9.8 은 지원한다는데 어떻게 동작할진 모르겠네요.
아래 링크에서 다운로드해서 phantomjs.exe 파일을 교쳬해보세요:
https://repo1.maven.org/maven2/com/github/klieber/phantomjs/1.9.8/phantomjs-1.9.8-windows.zip

**Comment by an101** [comment]
안녕하세요.

그렇군요. 말씀하신 대로 PhantomJS v.1.9.8을 다운 받아서
교체해서 다운로드를 해봤는데 다운로드가 되지 않았습니다.
작업정보는 다음과 같습니다.


Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 248, in get_imgs
Exception: Too short
- ya9579

gal_num: https://www.instagram.com/ya9579
dir:
zip:
type: insta
artist: None
url: https://www.instagram.com/ya9579
valid: False
done: False
range: None
range_p: None
single: False
time: 1545490781.78 (Dec 22)


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "insta_downloader3", line 51, in read
File "insta_downloader3", line 248, in get_imgs
Exception: Too short

Fail: insta

stop
done : https://www.instagram.com/ya9579

감사합니다.

________________________________
보낸 사람: Kurt Bestor <notifications@github.com>
보낸 날짜: 2018년 12월 22일 토요일 오전 9:50
받는 사람: KurtBestor/Hitomi-Downloader-issues
참조: an101; Author
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 인스타그램 다운로드이 되지 않아 질문을 드리고자 합니다. (#362)


인스타그램 긁을 때 PhantomJS<https://ko.wikipedia.org/wiki/PhantomJS> v2.1.1 쓰는데 이게 XP를 지원 안해요..

v1.9.8 은 지원한다는데 어떻게 동작할진 모르겠네요.
아래 링크에서 다운로드해서 phantomjs.exe 파일을 교쳬해보세요:
https://repo1.maven.org/maven2/com/github/klieber/phantomjs/1.9.8/phantomjs-1.9.8-windows.zip

**Comment by an101** [comment]
안녕하세요.

그렇군요. 말씀해주신대로 테스트 해보도록 하겠습니다.

감사합니다.

________________________________
보낸 사람: Kurt Bestor <notifications@github.com>
보낸 날짜: 2018년 12월 23일 일요일 오전 12:23
받는 사람: KurtBestor/Hitomi-Downloader-issues
참조: an101; Author
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 인스타그램 다운로드이 되지 않아 질문을 드리고자 합니다. (#362)


4월 전까진 꽤 쉽게 긁어올 수 있었는데, 그 후부터 사이트 구조를 어렵게 꼬아 놓아서 분석하다가 지쳐서 결국 PhantomJS를 썼던 기억이 나네요: #83<https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/83>, #87<https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/87>

이번엔 분석에 성공해서, PhantomJS를 쓰지 않아도 되게 바꿨어요.
이제 XP에서도 동작할 거예요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
