### ISSUE TITLE
산카쿠에서 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader-issues#380]
다운로더 잘 쓰고 있는 유저입니다. 다름이 아니라

https://chan.sankakucomplex.com/?tags=jam-orbital

이상하게 어제까진 잘 된 것 같은데 오늘은 되지가 않아서 말씀드려봅니다.

+ 다른 키워드도 테스트 해봤지만 안 됩니다.

Invalid : [sankaku] https://chan.sankakucomplex.com / ?tags=jam-orbital

gal_num: https://chan.sankakucomplex.com/?tags=jam-orbital
dir: 
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/?tags=jam-orbital
valid: False
done: False
range: None
range_p: None
single: True
time: 1546324049.1 (Jan 1)

[Gallery]
None

[File Names]

[URLs]

[Messages]
login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 58, in login_
File "requests\api", line 112, in post
File "requests\api", line 58, in request
File "downloader", line 66, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 644, in send
File "requests\sessions", line 192, in resolve_redirects
File "requests\sessions", line 274, in rebuild_proxies
File "requests\utils", line 744, in should_bypass_proxies
File "requests\utils", line 93, in proxy_bypass
File "requests\utils", line 59, in proxy_bypass_registry
ValueError: invalid literal for int() with base 10: ''

stop
Traceback (most recent call last):
File "utils", line 304, in __init__
File "sankaku_downloader", line 53, in init
File "sankaku_login", line 42, in login
Exception: Failed to login

Fail: sankaku

stop
done : https://chan.sankakucomplex.com/?tags=jam-orbital

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 열고 다음과 같이 입력한 후에 `Enter` 눌러서 나온 내용 보여주세요:
```
downloader.requests.utils.get_environ_proxies('https://sankakucomplex.com')

exec '''import _winreg as winreg\nsetting=winreg.OpenKey(winreg.HKEY_CURRENT_USER, r'Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings')\ns=u''\ntry: s+=u'{}\\n'.format(winreg.QueryValueEx(setting, 'ProxyEnable'))\nexcept Exception as e: s+=print_error(e)[-1]+'\\n'\ntry: s+=u'{}'.format(winreg.QueryValueEx(setting, 'ProxyOverride'))\nexcept Exception as e: s+=print_error(e)[-1]\nprint s'''
```

**Comment by chbk256** [comment]
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]

print downloader.requests.utils.get_environ_proxies('https://sankakucomplex.com') exec '''import _winreg as winreg\nsetting=winreg.OpenKey(winreg.HKEY_CURRENT_USER, r'Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings')\ns=u''\ntry: s+=u'{}\\n'.format(winreg.QueryValueEx(setting, 'ProxyEnable'))\nexcept Exception as e: s+=print_error(e)[-1]+'\\n'\ntry: s+=u'{}'.format(winreg.QueryValueEx(setting, 'ProxyOverride'))\nexcept Exception as e: s+=print_error(e)[-1]\nprint s''' 

{}
('\x00\x00\x00\x00', 3)
Traceback (most recent call last):
  File "<string>", line 6, in <module>
WindowsError: [Error 2]

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by chbk256** [comment]
정상적으로 받아집니다. 일단 끝까지 한 키워드로 다 받은 것은 아니니, 차후 문제가 생긴다면 다시 말씀드리겠습니다. 그러고 보니 새해군요. 새해 복 많이 받으시기 바랍니다.
