### ISSUE TITLE
유튜브 연령제한 영상은 안되는건가요?

### ISSUE THREAD

**Issue by juddem002** [KurtBestor/Hitomi-Downloader-issues#425]
4k 유튜브 다운로더에서 안되길래 혹시나해서 만드신 프로그램으로도 해봤는데

안되더라구요;;; 연령제한 영상은 안되는건가요?

**Comment by juddem002** [comment]
Invalid : [youtube] https://www.youtube.com / watch?v=ptHNxxr6p9I

version: 2.5c
gal_num: https://www.youtube.com/watch?v=ptHNxxr6p9I
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=ptHNxxr6p9I
valid: False
done: False
range: None
range_p: None
single: True
time: 1547899864.18 (Jan 19)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 437, in start
File "utils", line 481, in start_
File "youtube_downloader", line 83, in read
File "youtube_downloader", line 214, in get_videos
File "FUUUUCK\__main__", line 87, in __init__
File "FUUUUCK\__main__", line 96, in prefetch_init
File "FUUUUCK\__main__", line 134, in init
File "FUUUUCK\extract", line 126, in js_url
File "FUUUUCK\extract", line 176, in get_ytplayer_config
File "FUUUUCK\helpers", line 39, in regex_search
RegexMatchError: regex pattern (;yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})(,'EXPERIMENT_FLAGS'|;)) had zero matches

Fail: youtube

done : https://www.youtube.com/watch?v=ptHNxxr6p9I

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

1080p는 변환이 필요한데 영상이 길어서 그런지 변환하는데 1시간 정도 걸리네요.
720p로 받으면 빨라요.

**Comment by juddem002** [comment]
720으로 받으니까 금방되는데 1080은 제 시피유가 구려서 그런지 2시간이 넘었는데도 아직도 변환중이네요 ㅠㅠ.. 어찌되었든 다운은 잘되었습니다 감사합니다!

**Comment by KurtBestor** [comment]
1080p도 빠르게 되게 수정했어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
