### ISSUE TITLE
특정 계정 인스타그램 다운이 안됩니다

### ISSUE THREAD

**Issue by siwkd2** [KurtBestor/Hitomi-Downloader-issues#429]
안녕하세요 커트베스터님 

인스타그램 다운로드 도중 오류가 발생해서 문의드려봅니다

비공개 계정은 아닙니다

https://www.instagram.com/1and1_lash/

버젼은 2.5c 최신버젼이구요

Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 268, in get_imgs
File "insta_downloader3", line 184, in get_urls
Exception: Too short
- 1and1_lash

version: 2.5c
gal_num: https://www.instagram.com/1and1_lash/
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/1and1_lash
valid: False
done: False
range: None
range_p: None
single: False
time: 1548067256.05 (Jan 21)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
try v4
Traceback (most recent call last):
File "insta_downloader3", line 259, in get_imgs
File "insta_downloader4", line 69, in get_urls
AttributeError: 'NoneType' object has no attribute 'get'

try v3
stop
Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 268, in get_imgs
File "insta_downloader3", line 184, in get_urls
Exception: Too short

Fail: insta

stop
done : https://www.instagram.com/1and1_lash/

오류해결해주시면 감사하겠습니다

* 확인된건 2001장이 넘어가는건 읽기도중 멈췄다가 다시 2000장으로 한도가 제한되어 다시읽기를 시도하다가 빨간글씨가 뜨면서 오류표시가 나는것으로 확인되었습니다 ex: (860/2607)->(4/2000)

또한 게시글 2천개가 넘어가지않는 경우도 해당 오류가 발생된것으로 확인되었습다

*다시 다운로드시도를 해보니 다운이 되네요 ㄷㄷ 다만 게시글 2천개가 넘는 계정과 동시 다운을 하다보니 막히는 계정이 몇개 있는거같아요 

다시정리하자면 게시글 2천개가 넘는 인스타계정은 오류로 인해 확실히 다운로드가 안되는상황이고

게시글 2천개가 넘는 인스타계정과 다른계정을 동시에 가동시켰을경우 오류가 겹쳐서 다른계정도 다운로드가 안되는 그런상황인거같습니다

1. 게시글 2천개넘는 인스타계정 다운로드시도 ( 버그발생)

2. 게시글 2천개넘는 인스타계정 + 2천개 이하 인스타계정 (버그발생)

3. 2천개 이하 인스타계정들만 다운로드시도 (정상작동)

**Comment by KurtBestor** [comment]
다음 테스트 버전으로 실행해서 나오는 작업 정보 보여주세요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by siwkd2** [comment]
테스트계정은 

https://www.instagram.com/aubezest (정상작동)

https://www.instagram.com/jimmychoo (에러발생)

https://www.instagram.com/jooyoni_ (정상작동)

https://www.instagram.com/skuukzky(에러발생)

https://www.instagram.com/su_h0312(에러발생)

전부 게시글 2천개 이하 계정들입니다 전부 한꺼번에 작동시켰으며


 에러가 발생한 계정중에 

https://www.instagram.com/jimmychoo (에러발생)

오류정보를 올렸습니다

(게시글 2천개 이상 테스트 결과물은 아랫 댓글에 있습니다)

-------------------------------------------------

Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 268, in get_imgs
File "insta_downloader3", line 184, in get_urls
Exception: Too short
- jimmychoo

version: 2.5c
gal_num: https://www.instagram.com/jimmychoo
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/jimmychoo
valid: False
done: False
range: None
range_p: None
single: False
time: 1548134035.7 (Jan 22)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
try v4
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Traceback (most recent call last):
File "insta_downloader3", line 259, in get_imgs
File "insta_downloader4", line 76, in get_urls
Exception: no media

try v3
stop
Traceback (most recent call last):
File "insta_downloader3", line 52, in read
File "insta_downloader3", line 268, in get_imgs
File "insta_downloader3", line 184, in get_urls
Exception: Too short

Fail: insta

stop
done : https://www.instagram.com/jimmychoo

-------------------------------------------


확인해보니 게시글 2천개 계정말고도

900개 1200개 800개 게시글을 올린 계정을 한꺼번에 작동시켰을 경우 다음과 같은 에러가 발생하며

한개씩 작동시켜서 한개 작업이 끝난후  다시 다른작업을 작동시켜서 순차적으로 다운받은 결과는 아무 이상없이 전부 정상 작동이 되었습니다

이로써 다시 정리하자면 

1. 대량의 게시글을 가진 계정들을 한꺼번에 작동시키면 오류가 생김

2. 2천개이상 게시글을 가진 계정은 별도로 작동시켜도 오류가 생김

3. 2천개 이하 계정을 한개씩 작동시켰을때는 정상다운로드

(아마 200 156개 324개 게시글을 가진 계정들을 동시에 돌린 경우가 아닌

960 1562 1254 895 같은 대량의 게시글을 가진 계정들을 동시 구동했을때 나타나는 오류로 추정됩니다)

**Comment by siwkd2** [comment]
2천개이상 테스트 계정입니다


https://www.instagram.com/kate_yangll/

게시글 2603개입니다


-------------------------------
Kate Eunjung Yang (insta_kate_yangll)

version: 2.5c
gal_num: https://www.instagram.com/kate_yangll
dir: F:\Users\family9\Desktop\whats_insta\Kate Eunjung Yang (insta_kate_yangll)
zip: 
type: insta
artist: None
url: https://www.instagram.com/kate_yangll
valid: True
done: True
range: None
range_p: None
single: False
time: 1548134664.6 (Jan 22)
tags: []


[Gallery]
None


[File Names]
[0001] F:\Users\family9\Desktop\whats_insta\Kate Eunjung Yang (insta_kate_yangll)\[19-01-22] Bs7IRIvBT0q_p0.jpg
[0002] F:\Users\family9\Desktop\whats_insta\Kate Eunjung Yang (insta_kate_yangll)\[19-01-22] Bs7IRIvBT0q_p1.jpg

~(이건 제가 쓴겁니다 1~부터 2274까지 있는데 맨위 맨 아래 두개만 긁었습니다)

[2273] LazyUrl(https://www.instagram.com/p/BZz0Kltgk4k/) ---> https://scontent-icn1-1.cdninstagram.com/vp/af946beb94d5f1badce117031d2f927c/5CC1446C/t51.2885-15/e35/20633607_486146961766057_2007608116631306240_n.jpg?_nc_ht=scontent-icn1-1.cdninstagram.com
[2274] LazyUrl(https://www.instagram.com/p/BZx743kAPhM/) ---> https://scontent-icn1-1.cdninstagram.com/vp/4ed9e1d96c577626d02af7bfaaad0ad9/5CCB73C3/t51.2885-15/e35/22157238_275035436340127_1788011068761571328_n.jpg?_nc_ht=scontent-icn1-1.cdninstagram.com



[Messages]
try v4
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

no media.. retry
Traceback (most recent call last):
File "insta_downloader4", line 68, in get_urls
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Traceback (most recent call last):
File "insta_downloader3", line 259, in get_imgs
File "insta_downloader4", line 76, in get_urls
Exception: no media

try v3
done : https://www.instagram.com/kate_yangll
-------------------------------------



테스트 결과 2603개 게시글중 1800개까지만 읽고(1802/2603) 다시 (245/2000)으로 되더니 좀있다 (62/1263)으로 줄어드는 현상이 보였습니다

아마 읽는도중 일부 게시글을 읽지않고 그대로 넘긴것으로 보입니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

2000 장 이상은 다음을 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/382#issuecomment-450846793

**Comment by siwkd2** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
> 
> 2000 장 이상은 다음을 참고해주세요: [#382 (comment)](https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/382#issuecomment-450846793)

작동결과 잘됩니다 버그수정해주셔서 정말 감사합니다
