### ISSUE TITLE
만들어주신 유튜브 19세 영상 테스트버전에서

### ISSUE THREAD

**Issue by completelee** [KurtBestor/Hitomi-Downloader-issues#437]
영상을 다운받으면

주황색으로 100%에서 초록색 완료 표시가 뜨지는 않는데

이거 주황색이여도 다 다운받아진거 맞죠??

항상 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
다운로드나 변환 중에 실패 했을 때 주황색으로 떠요.

다음 테스트 버전으로 다시 시도해서 실패하면 해당 작업 `마우스 우클릭 - 정보... (I)` 눌러서 나온 내용 보여주세요:
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by completelee** [comment]
180623 메이퀸(MayQueen) 하연 직캠 - 댄스 & 버블팝(현아) [여의도 윙카공연 비키니특집] fancam

version: 2.5c
gal_num: https://www.youtube.com/watch?v=9Y9h89VWIlg&t=74s
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=9Y9h89VWIlg&t=74s
valid: False
done: True
range: None
range_p: None
single: True
time: 1548436194.97 (Jan 26)
tags: []


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\180623 메이퀸(MayQueen) 하연 직캠 - 댄스 & 버블팝(현아) [여의도 윙카공연 비키니특집] fancam.mp4


[URLs]
[0001] https://r7---sn-ab02a0nfpgxapox-bh2ez.googlevideo.com/videoplayback?clen=28703729&requiressl=yes&txp=5432432&initcwndbps=1662500&mime=video%2Fmp4&mt=1548436104&ipbits=0&c=WEB&usequic=no&fvip=2&itag=137&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cusequic%2Cexpire&expire=1548457796&gir=yes&key=yt6&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2ez%2Csn-n4v7snee&id=o-AK4Fjsszl066YYgtIpUd13hDVbqbnZpak9nWEg645Vs1&source=youtube&mv=m&ei=40JLXKLILYmDrQTU45Zo&keepalive=yes&ms=au%2Conr&ip=112.151.232.97&lmt=1542109444993603&dur=194.127&pl=19&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315&signature=2570FC1F02960BD91E709ECC56342BCD85E06FDF.073385253583EC304B2A37AF283058BA8374BD03&ratebypass=yes


[Messages]
[None][50kbps] webm
[None][70kbps] webm
[None][128kbps] m4a
[None][160kbps] webm
[None][128kbps] webm
[144p][None] webm
[144p][None] mp4
[240p][None] webm
[240p][None] mp4
[360p][None] webm
[360p][None] mp4
[480p][None] webm
[480p][None] mp4
[720p][None] webm
[720p][None] mp4
[720p][None] webm
[1080p][None] webm
[720p][None] mp4
[1080p][None] mp4
[1080p][None] webm
[1080p][None] mp4
[1440p][None] webm
[1440p][None] webm
[1920p][None] webm
[1920p][None] webm
[144p][24kbps] 3gp
[240p][None] 3gp
[360p][96kbps] mp4
[720p][192kbps] mp4
[360p][128kbps] webm


# stream_final <youtube_dl_test.Video object at 0x2290B1D0> 1080p None
# stream_final <youtube_dl_test.Video object at 0x2290B190> 1080p None
Resolution: 1080p
Codec: avc1.64001f / None
Abr: None
Subtype: mp4

Download audio: https://r7---sn-ab02a0nfpgxapox-bh2ez.googlevideo.com/videoplayback?clen=1523027&requiressl=yes&txp=5411222&initcwndbps=1662500&mime=audio%2Fwebm&mt=1548436104&ipbits=0&c=WEB&usequic=no&fvip=2&itag=250&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cusequic%2Cexpire&expire=1548457796&gir=yes&key=yt6&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2ez%2Csn-n4v7snee&id=o-AK4Fjsszl066YYgtIpUd13hDVbqbnZpak9nWEg645Vs1&source=youtube&mv=m&ei=40JLXKLILYmDrQTU45Zo&keepalive=yes&ms=au%2Conr&ip=112.151.232.97&lmt=1542110607598586&dur=194.141&pl=19&signature=25210A206C73BDCA33FB7B47A711FFC8FF9A8BB1.B8821E099BF6BB7150D21ADF3B32AF3EE0CCEFEA&ratebypass=yes
Convert: C:\Users\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\180623 메이퀸(MayQueen) 하연 직캠 - 댄스 & 버블팝(현아) [여의도 윙카공연 비키니특집] fancam.mp4
Traceback (most recent call last):
File "utils", line 594, in start_
File "youtube_downloader", line 122, in post_processing
File "ffmpeg", line 119, in merge
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 9: ordinal not in range(128)

done : https://www.youtube.com/watch?v=9Y9h89VWIlg&t=74s

요겁니다

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 열고 아래 내용을 입력하고 `Enter` 눌러서 나오는 내용 알려주세요:
```
__import__('ffmpeg').dir 
```

**Comment by completelee** [comment]
> `Ctrl + Alt + C` 눌러서 콘솔 열고 아래 내용을 입력하고 `Enter` 눌러서 나오는 내용 알려주세요:
> 
> ```
> __import__('ffmpeg').dir 
> ```

Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]

__import__('ffmpeg').dir 

'c:\\users\\\xb1\xe8\xbc\xba\xbf\xcf\\appdata\\local\\temp'


제가 컴알못이라 잘 모르지만 이거 맞나요?

**Comment by KurtBestor** [comment]
네, 맞아요. 아래 내용 입력하고 `Enter` 눌러서 나오는 내용 알려주세요:
```
fucking_encoding.encodings, __import__('locale').getdefaultlocale()[1], sys.getfilesystemencoding()
```

**Comment by completelee** [comment]
> 네, 맞아요. 아래 내용 입력하고 `Enter` 눌러서 나오는 내용 알려주세요:
> 
> ```
> fucking_encoding.encodings, __import__('locale').getdefaultlocale(), sys.getfilesystemencoding()
> ```

(['cp949', 'mbcs', 'ascii', 'utf-8', 'ascii'], ('ko_KR', 'cp949'), 'mbcs')



이겁니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by completelee** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

와 이제됐네요 초록색이 뜹니다.

변환에서 3~5분 걸리는 것 같은데 그래도 초록색으로 되네요 진짜 감사합니다 .잘 쓰겠습니다.!!!!
