### ISSUE TITLE
검색기 데이터 다운로드 오류가 뜹니다.

### ISSUE THREAD

**Issue by SsanMa** [KurtBestor/Hitomi-Downloader-issues#476]
항상 감사한 마음을 가지고 다운로더를 사용하고 있습니다. 
다름이 아니라 어느 순간부터 기본데이터를 다운받는데 오류가 발생하여 구버젼으로도 해보고 
백신도 끄고 해보아도 오류가 떠서 기본 데이터 다운이 안돼더라구요..

혹시 해결해주실수 있을까 싶어 글을 올립니다. 감사합니다

---------------------------
Hitomi Downloader
---------------------------
데이터를 다운로드하는 중에 실패했습니다.
---------------------------
확인   자세한 정보 숨기기...   
---------------------------
traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 378, in download_json_
  File "<string>", line 1, in <module>
NameError: name 'domain' is not defined

**Comment by MOKISAN** [comment]
저도 똑같은 오류뜹니다. 연휴후 즐딸라이프를 즐기려고 했건만...

Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 378, in download_json_
  File "<string>", line 1, in <module>
NameError: name 'domain' is not defined

**Comment by KurtBestor** [comment]
참고해주세요: #463
