### ISSUE TITLE
쇼미 다운 오류가 납니다  invalid: ~~

### ISSUE THREAD

**Issue by iaray3112** [KurtBestor/Hitomi-Downloader-issues#488]
다운로드를 몇번 시도하면 되는 것도 있고, 계속 안 되는 것도 있습니다.

파일 잘 쓰고 있습니다. 항상 건강하세요!

Invalid : [mangashow] https://mangashow.me / bbs / page.php?hid=manga_detail&manga_name=%EC%82%AC%EC%8B%A0+%EB%8F%84%EB%A0%A8%EB%8B%98%EA%B3%BC+%EA%B2%80%EC%9D%80+%EB%A9%94%EC%9D%B4%EB%93%9C

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%82%AC%EC%8B%A0+%EB%8F%84%EB%A0%A8%EB%8B%98%EA%B3%BC+%EA%B2%80%EC%9D%80+%EB%A9%94%EC%9D%B4%EB%93%9C
dir: 
zip: 
type: mangashow
artist: 이노우에 코하루
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%82%AC%EC%8B%A0+%EB%8F%84%EB%A0%A8%EB%8B%98%EA%B3%BC+%EA%B2%80%EC%9D%80+%EB%A9%94%EC%9D%B4%EB%93%9C
valid: False
done: False
range: None
range_p: [72]
single: False
time: 1549639078.74 (Feb 9)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
stop
Traceback (most recent call last):
File "utils", line 480, in start
File "utils", line 524, in start_
File "mangashow_downloader", line 110, in read
File "mangashow_downloader", line 240, in get_imgs
File "constants", line 578, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 563, in wrapper
File "mangashow_downloader", line 270, in get_imgs_page
File "capture", line 24, in capture
File "selenium\webdriver\remote\webdriver", line 323, in get
File "selenium\webdriver\remote\webdriver", line 309, in execute
File "selenium\webdriver\remote\remote_connection", line 460, in execute
File "selenium\webdriver\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

Fail: mangashow

done : https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EC%82%AC%EC%8B%A0+%EB%8F%84%EB%A0%A8%EB%8B%98%EA%B3%BC+%EA%B2%80%EC%9D%80+%EB%A9%94%EC%9D%B4%EB%93%9C

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by iaray3112** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

정상 작동되네요 늦은 시간에 감사합니다 ^^
