### ISSUE TITLE
test 버전도 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by 17171715** [KurtBestor/Hitomi-Downloader-issues#499]
데이터를 다운로드에 실패하여 검색한 뒤 test 버전을 받았지만

Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 428, in download_json_
Exception: https://ltn.hitomi.la/galleries0.json
WTF

이렇게 나오면서 다운로드가 안됩니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/498
