### ISSUE TITLE
기본 데이터 다운로드 시 ValueError: Expected object or value 가 뜹니다.

### ISSUE THREAD

**Issue by 1597531217** [KurtBestor/Hitomi-Downloader-issues#500]
Traceback (most recent call last):
  File "hitomi_searcher", line 211, in download_json
  File "hitomi_searcher", line 371, in download_json_
ValueError: Expected object or value

위와 같은 메세지가 뜨며 기본 데이터 다운로드가 안 되고 있습니다.
#498의 테스트 파일을 받아봤지만 해결이 되지 않습니다.

**Comment by KurtBestor** [comment]
해결중이에요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/498
