### ISSUE TITLE
뉴토끼가 도메인 이동을 했네요 스크립트 부탁드려요

### ISSUE THREAD

**Issue by ourload** [KurtBestor/Hitomi-Downloader-issues#505]
기존 뉴토끼 주소에서 일본만화용https://newtoki2.net/ 과 웹툰용인 https://newtoki2.com/으로 바꼈습니다
이거 스크립트 수정 가능할련지요
그리고 지금 크롬으로 vpn 사용시 망가쇼미가 접속이 되긴 합니다만 이렇게 연결이 되더라도
다운은 안 되는거 같네요 ㅠㅠ

**Comment by ourload** [comment]
Invalid : [mangashow] https://mangashow.me / bbs / page.php?hid=manga_detail&manga_name=%EB%B0%A9%EA%B3%BC+%ED%9B%84%EC%9D%98+%EA%B3%A0%EB%AC%B8%EC%86%8C%EB%85%80

version: 2.5d
platform: Windows-7-6.1.7601-SP1
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EB%B0%A9%EA%B3%BC+%ED%9B%84%EC%9D%98+%EA%B3%A0%EB%AC%B8%EC%86%8C%EB%85%80
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EB%B0%A9%EA%B3%BC+%ED%9B%84%EC%9D%98+%EA%B3%A0%EB%AC%B8%EC%86%8C%EB%85%80
valid: False
done: False
range: None
range_p: None
single: False
time: 1549906152.37 (Feb 12)
tags: []


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Traceback (most recent call last):
File "utils", line 480, in start
File "utils", line 524, in start_
File "mangashow_downloader", line 106, in read
File "mangashow_downloader", line 88, in name
File "mangashow_downloader", line 83, in soup
File "constants", line 578, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 563, in wrapper
File "mangashow_downloader", line 143, in get_soup
File "requests\sessions", line 525, in get
File "downloader", line 70, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 622, in send
File "requests\adapters", line 496, in send
ConnectionError: ('Connection aborted.', error(10054, ''))


Fail: mangashow

done : https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EB%B0%A9%EA%B3%BC+%ED%9B%84%EC%9D%98+%EA%B3%A0%EB%AC%B8%EC%86%8C%EB%85%80

이러면서 안되네요

**Comment by KurtBestor** [comment]
스크립트 수정했어요: https://drive.google.com/drive/folders/1FP0YZp7QyGDyOQ1nwILRIVT3kd58NYxo

**Comment by KurtBestor** [comment]
망가쇼미는 다음 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/513
