### ISSUE TITLE
쇼미 invalid 버그

### ISSUE THREAD

**Issue by iaray3112** [KurtBestor/Hitomi-Downloader-issues#507]
시크릿디엔에스 키면 다운로드가 되는데
그 중 일부가 다운로드 오류뜨네요
확인 해주시면 감사하겠습니다 ( _ _ )

Invalid : [mangashow] https://mangashow.me / bbs / page.php?hid=manga_detail&manga_name=%EA%B0%80%EC%B1%A0%EB%A5%BC+%EB%8F%8C%EB%A0%A4+%EB%8F%99%EB%A3%8C%EB%A5%BC+%EB%8A%98%EB%A6%AC%EA%B3%A0+%EC%B5%9C%EA%B0%95%EC%9D%98+%EB%AF%B8%EC%86%8C%EB%85%80+%EA%B5%B0%EB%8B%A8%EC%9D%84+%EB%A7%8C%EB%93%A4%EC%9E%90

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EA%B0%80%EC%B1%A0%EB%A5%BC+%EB%8F%8C%EB%A0%A4+%EB%8F%99%EB%A3%8C%EB%A5%BC+%EB%8A%98%EB%A6%AC%EA%B3%A0+%EC%B5%9C%EA%B0%95%EC%9D%98+%EB%AF%B8%EC%86%8C%EB%85%80+%EA%B5%B0%EB%8B%A8%EC%9D%84+%EB%A7%8C%EB%93%A4%EC%9E%90
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EA%B0%80%EC%B1%A0%EB%A5%BC+%EB%8F%8C%EB%A0%A4+%EB%8F%99%EB%A3%8C%EB%A5%BC+%EB%8A%98%EB%A6%AC%EA%B3%A0+%EC%B5%9C%EA%B0%95%EC%9D%98+%EB%AF%B8%EC%86%8C%EB%85%80+%EA%B5%B0%EB%8B%A8%EC%9D%84+%EB%A7%8C%EB%93%A4%EC%9E%90
valid: False
done: False
range: None
range_p: [7]
single: False
time: 1549913481.08 (Feb 12)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 563, in wrapper
File "mangashow_downloader", line 143, in get_soup
File "requests\sessions", line 525, in get
File "downloader", line 70, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 622, in send
File "requests\adapters", line 496, in send
ConnectionError: ('Connection aborted.', error(10054, ''))

stop
Traceback (most recent call last):
File "utils", line 480, in start
File "utils", line 524, in start_
File "mangashow_downloader", line 107, in read
File "mangashow_downloader", line 89, in name
File "mangashow_downloader", line 84, in soup
File "constants", line 578, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 563, in wrapper
File "mangashow_downloader", line 143, in get_soup
File "requests\sessions", line 525, in get
File "downloader", line 70, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 622, in send
File "requests\adapters", line 496, in send
ConnectionError: ('Connection aborted.', error(10054, ''))

Fail: mangashow

done : https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EA%B0%80%EC%B1%A0%EB%A5%BC+%EB%8F%8C%EB%A0%A4+%EB%8F%99%EB%A3%8C%EB%A5%BC+%EB%8A%98%EB%A6%AC%EA%B3%A0+%EC%B5%9C%EA%B0%95%EC%9D%98+%EB%AF%B8%EC%86%8C%EB%85%80+%EA%B5%B0%EB%8B%A8%EC%9D%84+%EB%A7%8C%EB%93%A4%EC%9E%90

**Comment by KurtBestor** [comment]
다음 프로그램 키고 다운로드해주세요: https://github.com/ValdikSS/GoodbyeDPI

**Comment by iaray3112** [comment]
> 다음 프로그램 키고 다운로드해주세요: https://github.com/ValdikSS/GoodbyeDPI

정말정말 감사합니다!
