### ISSUE TITLE
망가쇼미 다운로드가 안되요.. ㅠㅠ

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader-issues#511]
안녕하세요. 어제부터 갑자기 다운로드가 안되네요.

https차단 들어갔다는 건 알고 있는데 크롬확장 vpn을 써서 사이트에는 들어가지는데

히토미 다운로더로 다운은 안되네요..

뭔가 이미지 긁어오는 배치확장 파일로도 이미지가 안나타나고..

https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/506 글에서

pitchlatte님이 댓글로 vpn 쓰면 잘 다운 된다는데 확장이 아니라 프로그램으로 따로 써야 되는건가요..

누가 알려주실분 ㅠㅠ

Invalid : [mangashow] https://mangashow.me / bbs / board.php?bo_table=msm_manga&wr_id=597969

version: 2.5d
platform: Windows-10-10.0.17134
gal_num: https://mangashow.me/bbs/board.php?bo_table=msm_manga&wr_id=597969
dir: 
zip: 
type: mangashow
artist: None
url: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EB%82%A8%EA%B3%A0%EC%83%9D%EC%9D%84+%EA%B8%B0%EB%A5%B4%EA%B3%A0+%EC%8B%B6%EC%9D%80+%EB%88%84%EB%82%98%EC%9D%98+%EC%9D%B4%EC%95%BC%EA%B8%B0
valid: False
done: False
range: None
range_p: None
single: False
time: 1549941046.7 (Feb 12)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://mangashow.me/bbs/page.php?hid=manga_detail&manga_name=%EB%82%A8%EA%B3%A0%EC%83%9D%EC%9D%84+%EA%B8%B0%EB%A5%B4%EA%B3%A0+%EC%8B%B6%EC%9D%80+%EB%88%84%EB%82%98%EC%9D%98+%EC%9D%B4%EC%95%BC%EA%B8%B0
stop
Traceback (most recent call last):
File "utils", line 480, in start
File "utils", line 524, in start_
File "mangashow_downloader", line 106, in read
File "mangashow_downloader", line 88, in name
File "mangashow_downloader", line 83, in soup
File "constants", line 578, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 563, in wrapper
File "mangashow_downloader", line 143, in get_soup
File "requests\sessions", line 525, in get
File "downloader", line 70, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 622, in send
File "requests\adapters", line 496, in send
ConnectionError: ('Connection aborted.', error(10054, ''))

Fail: mangashow

**Comment by KurtBestor** [comment]
다음 프로그램 키고 다운로드 해주세요: https://github.com/ValdikSS/GoodbyeDPI
