### ISSUE TITLE
기본 데이터 다운로드

### ISSUE THREAD

**Issue by kikinet88** [KurtBestor/Hitomi-Downloader-issues#542]
오늘차 크롤러 업데이트 (업로드) 가 완료된후

다운로더로 데이터를 받고자 하는대..

음.. 안받아지는군요

Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 370, in download_json_
IndexError: list index out of range

**Comment by KurtBestor** [comment]
테스트 버전 써주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
