### ISSUE TITLE
v2.5d 기본 데이터 다운로드 오류

### ISSUE THREAD

**Issue by Aleady-taken** [KurtBestor/Hitomi-Downloader-issues#564]
이렇게 뜨면서 다운로드가 안 되네요

자세한 정보
Traceback (most recent call last):
  File "hitomi_searcher", line 203, in download_json
  File "hitomi_searcher", line 370, in download_json_
IndexError: list index out of range

**Comment by KurtBestor** [comment]
참고해주세요: #498
