### ISSUE TITLE
항상 고생많으십니다.. 니코니코동화 다운로드관련 문의입니다.

### ISSUE THREAD

**Issue by zeldin001** [KurtBestor/Hitomi-Downloader-issues#597]
이전에 수정해주신 테스트파일 감사히쓰고있습니다.

급작스럽게 몇몇영상이 다운로드가 안되어 문의드립니다. (_ _)

Invalid : [nico] https://www.nicovideo.jp / watch / sm34711165

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://www.nicovideo.jp/watch/sm34711165
dir: 
zip: 
type: nico
artist: None
url: https://www.nicovideo.jp/watch/sm34711165
valid: False
done: False
range: None
range_p: None
single: True
time: 1551528546.14 (Mar 2)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
'http'
stop
Traceback (most recent call last):
File "utils", line 493, in start
File "utils", line 537, in start_
File "nico_downloader4", line 66, in read
File "nico_downloader4", line 84, in get_video
File "nndownload", line 222, in request_video
File "nndownload", line 470, in perform_api_request
KeyError: 'http'

Fail: nico 

언제나 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by zeldin001** [comment]
구동 확인했습니다. 감사합니다!
