### ISSUE TITLE
유튜브에서 60프레임영상을 받았는데 받고나니 30프레임입니다

### ISSUE THREAD

**Issue by stayss** [KurtBestor/Hitomi-Downloader-issues#620]
해결법이 없을까요?

옵션엔 화질선택만 있어서요

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by stayss** [comment]
> 해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

2018 16th BEAT-TRIBE CUP CUT

version: 2.6
platform: Windows-7-6.1.7601-SP1
gal_num: https://youtu.be/NA1NliLRP9A
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: None
url: https://youtu.be/NA1NliLRP9A
valid: True
done: True
range: None
range_p: None
single: True
time: 1552389200.16 (Mar 12)
tags: []


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\2018 16th BEAT-TRIBE CUP CUT.mp4


[URLs]
[0001] https://r8---sn-3u-nf0l.googlevideo.com/videoplayback?txp=5431432&key=yt6&source=youtube&mime=video%2Fmp4&pcm2cms=yes&pl=22&ratebypass=yes&fvip=8&signature=440751D9C5150941AF21C5531DA4D43B4906AF4B.8F8C7EB79B6E5A328FF357F95F14FDA082099762&ei=UZSHXLeuKsHL4QLc4pq4Dw&itag=22&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&initcwndbps=1472500&id=o-ALVLkpZCdoCZJCyLrLI9Qfg4XxGX5puc06OEUbPaIs1n&mm=31%2C29&ipbits=0&c=WEB&mn=sn-3u-nf0l%2Csn-3u-bh2e7&ms=au%2Crdu&mt=1552389173&dur=16787.237&mv=m&ip=211.248.44.195&lmt=1540740546163142&requiressl=yes&expire=1552410801


[Messages]
[None][50kbps] webm opus
[None][70kbps] webm opus
[None][128kbps] webm vorbis
[None][160kbps] webm opus
[None][128kbps] m4a mp4a.40.2
[144p][None] mp4 None
[144p][None] webm None
[240p][None] mp4 None
[240p][None] webm None
[360p][None] webm None
[360p][None] mp4 None
[480p][None] webm None
[480p][None] mp4 None
[720p][None] webm None
[720p][None] mp4 None
[720p][None] webm None
[720p][None] mp4 None
[360p][128kbps] webm vorbis
[360p][96kbps] mp4 mp4a.40.2
[720p][192kbps] mp4 mp4a.40.2


# stream_final <youtube_dl_test.Video object at 0x235F9530> 720p webm None
# stream_final <youtube_dl_test.Video object at 0x235F9570> 720p mp4 None
# stream_final <youtube_dl_test.Video object at 0x235F97F0> 720p mp4 mp4a.40.2
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192kbps
Subtype: mp4

downloader_v3 fail... p[199 / 3875]
Traceback (most recent call last):
File "downloader_v3", line 54, in run
File "requests\sessions", line 525, in get
File "downloader", line 72, in session_request
File "requests\sessions", line 512, in request
File "requests\sessions", line 622, in send
File "requests\adapters", line 514, in send
ConnectionError: HTTPSConnectionPool(host='r8---sn-3u-nf0l.googlevideo.com', port=443): Max retries exceeded with url: /videoplayback?txp=5431432&key=yt6&source=youtube&mime=video%2Fmp4&pcm2cms=yes&pl=22&ratebypass=yes&fvip=8&signature=440751D9C5150941AF21C5531DA4D43B4906AF4B.8F8C7EB79B6E5A328FF357F95F14FDA082099762&ei=UZSHXLeuKsHL4QLc4pq4Dw&itag=22&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&initcwndbps=1472500&id=o-ALVLkpZCdoCZJCyLrLI9Qfg4XxGX5puc06OEUbPaIs1n&mm=31%2C29&ipbits=0&c=WEB&mn=sn-3u-nf0l%2Csn-3u-bh2e7&ms=au%2Crdu&mt=1552389173&dur=16787.237&mv=m&ip=211.248.44.195&lmt=1540740546163142&requiressl=yes&expire=1552410801 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x246964F0>: Failed to establish a new connection: [Errno 10060] \xbf\xac\xb0\xe1\xb5\xc8 \xb1\xb8\xbc\xba\xbf\xf8\xc0\xb8\xb7\xce\xba\xce\xc5\xcd \xc0\xc0\xb4\xe4\xc0\xcc \xbe\xf8\xbe\xee \xbf\xac\xb0\xe1\xc7\xcf\xc1\xf6 \xb8\xf8\xc7\xdf\xb0\xc5\xb3\xaa,',))

done : https://youtu.be/NA1NliLRP9A

**Comment by stayss** [comment]
> 해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

요것이고 유튜브에선 정상적으로 60프레임으로 보입니다

다운받은것은 30이네요
