### ISSUE TITLE
망가쇼미 다운이 안됩니다.

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader-issues#624]
망가쇼미 다운자체가 안되네요.
mangashow3.me 에서 다음으로 넘어갔나 싶어서 다음주소 확인해서 주소 바꿔봐도 안되네요.
위쪽은 mangashow3.me 일때 에러고
아래쪽은 mangashow5.me 쪽 에러입니다.

Invalid : [mangashow] https://mangashow3.me / bbs / page.php?hid=manga_detail&manga_name=199X

version: 2.6
platform: Windows-7-6.1.7601-SP1
gal_num: https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=199X
dir: hitomi_downloaded_mangashow\[N／A] 199X
zip: 
type: mangashow
artist: None
url: https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=199X
valid: False
done: False
range: None
range_p: None
single: False
time: 1552389718.88 (Mar 12)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 129, in get_soup
File "mangashow_downloader", line 377, in read_html
File "downloader", line 234, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10054, ''))

stop
Traceback (most recent call last):
File "utils", line 493, in start
File "utils", line 537, in start_
File "mangashow_downloader", line 110, in read
File "mangashow_downloader", line 92, in name
File "mangashow_downloader", line 87, in soup
File "constants", line 581, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 129, in get_soup
File "mangashow_downloader", line 377, in read_html
File "downloader", line 234, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10054, ''))

Fail: mangashow

done : https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=199X

Invalid : [mangashow] https://mangashow5.me / bbs / page.php?hid=manga_detail&manga_name=199X

version: 2.6
platform: Windows-7-6.1.7601-SP1
gal_num: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=199X
dir: hitomi_downloaded_mangashow\[N／A] 199X
zip: 
type: mangashow
artist: None
url: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=199X
valid: False
done: False
range: None
range_p: None
single: False
time: 1552389326.19 (Mar 12)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 133, in get_soup
Exception: Cloudflare protection

stop
Traceback (most recent call last):
File "utils", line 493, in start
File "utils", line 537, in start_
File "mangashow_downloader", line 110, in read
File "mangashow_downloader", line 92, in name
File "mangashow_downloader", line 87, in soup
File "constants", line 581, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 133, in get_soup
Exception: Cloudflare protection

Fail: mangashow

done : https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=199X

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이미지 서버도 같이 바뀌어서, https://mangashow5.me 로 하셔야해요.

**Comment by cocoman1111** [comment]
안녕하세요. 테스트버전 해봤는데.. 읽는중...으로만 계속 로딩만 되네요..
다운은 안됩니다 ㅠ_ㅠ

**Comment by jinjins7** [comment]
오 감사합니다. 확인이 좀 늦었네요. 테스트 버전으로 해보니 잘 됩니다.

**Comment by KurtBestor** [comment]
@cocoman1111 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
