### ISSUE TITLE
만화 제목에 특수문자가 들어간 경우 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by daenan** [KurtBestor/Hitomi-Downloader-issues#641]
읽는 중... [유키노] 1／10의 신부 / 1／10의 신부 1화 (1 / 1)

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=1%2F10%EC%9D%98+%EC%8B%A0%EB%B6%80
dir: 
zip: 
type: mangashow
artist: 유키노
url: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=1%2F10%EC%9D%98+%EC%8B%A0%EB%B6%80
valid: True
done: False
range: None
range_p: None
single: False
time: 1553045494.49 (Mar 20)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
[seed] 1/10의 신부 1화 398560
wait... 1/10의 신부 1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 1/10의 신부 1화 398560
wait... 1/10의 신부 1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 1/10의 신부 1화 398560
wait... 1/10의 신부 1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 1/10의 신부 1화 398560
wait... 1/10의 신부 1화

만화 제목에 폴더, 파일명에 쓸 수 없는 / 가 들어가서 계속 로딩만 하는 것 같습니다
다운로드 받을때 폴더명을 임의로 바꿀 수 있는 기능 또는
특수문자에 있는 슬래시 ／ 로 자동 변환해서 다운로드 받을 수 있게 할 수 있을까요?

슬래시( / ) 콜론( : ) 물음표( ? ) 버티컬바( | )
따옴표( " )
소 괄호( < > )
원 사인( \ ) 
곱하기( * )

**Comment by daenan** [comment]
다시 시도를 계속 하다보니 망가쇼미 서버문제였네요.. 이슈 닫겠습니다
