### ISSUE TITLE
vpn키면 익헨에 보이는작품 2개가 다운이 되지 않습니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader-issues#643]
2.3~2.4버젼일때는 다운이 되었는데 지금은 다운이 안됩니다 

해당 작품 링크고 vpn 안키면 unvailable 로 뜰겁니다

https://exhentai.org/g/1340616/0889a71fd0/

https://exhentai.org/g/1382484/bf890cba33/

vpn안킨 상태에서 다운이 안되길레 vpn키고 다운 받는데도 안되고 결국에는 스샷처럼 뜨네요

![223](https://user-images.githubusercontent.com/41049446/54680173-8ad01080-4b4c-11e9-9235-ac1330941301.PNG)

해당 링크들 정보입니다
1. 

Invalid : [hitomi] https://exhentai.org / g / 1340616 / 0889a71fd0 / 

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://exhentai.org/g/1340616/0889a71fd0/
dir: 
zip: 
type: exhen
artist: None
url: https://exhentai.org/g/1340616/0889a71fd0/
valid: False
done: False
range: None
range_p: None
single: False
time: 1553080005.58 (Mar 20)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
********************************
Gallery number : 1340616
Number of Threads : 64
********************************
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 1340616
ehen_imgs(ex:False, url:https://exhentai.org/g/1340616/0889a71fd0/)
#### None ----> https://e-hentai.org/g/1340616/0889a71fd0
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
File "hitomi_downloader", line 1653, in ehen_imgs
Exception: no images

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1204, in download_hitomi
Exception: no images

Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 1340616
ehen_imgs(ex:True, url:https://exhentai.org/g/1340616/0889a71fd0/)
#### https://exhentai.org/g/1340616/0889a71fd0/?p=19 ----> https://exhentai.org/g/1340616/0889a71fd0/?p=20
FINAL SERVER : ehen
ehen_url : https://exhentai.org/g/1340616/0889a71fd0
imgs: 836
get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (1)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (2)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (3)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (4)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (5)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (6)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (7)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

get_title_ehen: https://exhentai.org/g/1340616/0889a71fd0
TITLE FAILED : ehen (8)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

Traceback (most recent call last):
File "hitomi_downloader", line 1221, in download_hitomi
File "gallery", line 208, in get_gal
File "gallery", line 295, in get_gal_ehen
Exception: Cant get title - ehen (https://exhentai.org/g/1340616/0889a71fd0)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

Traceback (most recent call last):
File "hitomi_downloader", line 1221, in download_hitomi
File "gallery", line 208, in get_gal
File "gallery", line 295, in get_gal_ehen
Exception: Cant get title - ehen (https://exhentai.org/g/1340616/0889a71fd0)
Traceback (most recent call last):
File "gallery", line 286, in get_gal_ehen
File "gallery", line 372, in get_gal__ehen
AttributeError: 'NoneType' object has no attribute 'attrs'

Fail: hitomi

done : https://exhentai.org/g/1340616/0889a71fd0/

2.
404 Not Found : 1382484

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://exhentai.org/g/1382484/bf890cba33/
dir: 
zip: 
type: exhen
artist: None
url: https://exhentai.org/g/1382484/bf890cba33/
valid: False
done: False
range: None
range_p: None
single: True
time: 1553079806.11 (Mar 20)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
********************************
Gallery number : 1382484
Number of Threads : 64
********************************
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 1382484
ehen_imgs(ex:False, url:https://exhentai.org/g/1382484/bf890cba33/)
#### None ----> https://e-hentai.org/g/1382484/bf890cba33
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
File "hitomi_downloader", line 1653, in ehen_imgs
Exception: no images

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1204, in download_hitomi
Exception: no images

Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 1382484
ehen_imgs(ex:True, url:https://exhentai.org/g/1382484/bf890cba33/)
#### None ----> https://exhentai.org/g/1382484/bf890cba33
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
File "hitomi_downloader", line 1641, in ehen_imgs
File "downloader", line 234, in read_html
File "urllib3\poolmanager", line 170, in urlopen
File "urllib3\poolmanager", line 170, in urlopen
File "urllib3\poolmanager", line 170, in urlopen
File "urllib3\poolmanager", line 161, in urlopen
File "urllib3\util\retry", line 171, in increment
MaxRetryError: HTTPSConnectionPool(host='exhentai.org', port=443): Max retries exceeded with url: https://exhentai.org/ (Caused by ResponseError('too many redirects',))

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1204, in download_hitomi
MaxRetryError: HTTPSConnectionPool(host='exhentai.org', port=443): Max retries exceeded with url: https://exhentai.org/ (Caused by ResponseError('too many redirects',))

Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 1382484
ehen_imgs(ex:False, url:https://exhentai.org/g/1382484/bf890cba33/)
#### None ----> https://e-hentai.org/g/1382484/bf890cba33
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
File "hitomi_downloader", line 1653, in ehen_imgs
Exception: no images

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1204, in download_hitomi
Exception: no images

Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

get imgs from e(x)hentai: 1382484
ehen_imgs(ex:True, url:https://exhentai.org/g/1382484/bf890cba33/)
#### None ----> https://exhentai.org/g/1382484/bf890cba33
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
File "hitomi_downloader", line 1641, in ehen_imgs
File "downloader", line 234, in read_html
File "urllib3\poolmanager", line 170, in urlopen
File "urllib3\poolmanager", line 170, in urlopen
File "urllib3\poolmanager", line 170, in urlopen
File "urllib3\poolmanager", line 161, in urlopen
File "urllib3\util\retry", line 171, in increment
MaxRetryError: HTTPSConnectionPool(host='exhentai.org', port=443): Max retries exceeded with url: https://exhentai.org/ (Caused by ResponseError('too many redirects',))

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1204, in download_hitomi
MaxRetryError: HTTPSConnectionPool(host='exhentai.org', port=443): Max retries exceeded with url: https://exhentai.org/ (Caused by ResponseError('too many redirects',))

Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 141, in pop_img
File "downloader", line 247, in read_html
Exception: 404

Fail: hitomi

done : https://exhentai.org/g/1382484/bf890cba33/

**Comment by whgmlqja12** [comment]
저도 이와같은 비슷한 증상 뜹니다. vpn 통해서 다운로더에 넣고 받는건 vpn풀고 하는데 안되는게 몇개 보이네요... 그러다가 히토미에 올라올때쯤 되야 다운로드가 됩니다. 히토미에 없고 익헨에 있는건 안된다는거 같기도 하구...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lekim56** [comment]
아주 잘 됩니다. 정말 감사합니다!

**Comment by jaejunghan** [comment]
근데 히요비를 통해서 다운이 됩니다

**Comment by KurtBestor** [comment]
@jaejunghan 

`옵션` - `설정` - `히토미 설정` - `서버` 참고해주세요.
