### ISSUE TITLE
망가쇼미 다운이 막혔나봐요

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader-issues#662]
망가쇼미 다운방식이 바뀐건지 어떤건진 모르겠지만 다운이 안됩니다.
주소를 통해 들어가면 들어는가지는데 다운만 안되네요.
망가쇼3미
망가쇼5미
직통ip주소
다 해봐도 안되네요

Invalid : [mangashow] https://mangashow3.me / bbs / page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84

version: 2.6
platform: Windows-7-6.1.7601-SP1
gal_num: https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84
dir: 
zip: 
type: mangashow
artist: 아쿠타미 게게
url: https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84
valid: False
done: False
range: None
range_p: None
single: False
time: 1553712293.72 (Mar 28)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
Skip: 주술회전 1화
Skip: 주술회전 2화
Skip: 주술회전 3화
Skip: 주술회전 4화
Skip: 주술회전 5화
Skip: 주술회전 6화
Skip: 주술회전 7화
Skip: 주술회전 8화
Skip: 주술회전 9화
Skip: 주술회전 10화
Skip: 주술회전 11화
Skip: 주술회전 12화
Skip: 주술회전 13화
Skip: 주술회전 14화
Skip: 주술회전 15화
Skip: 주술회전 16화
Skip: 주술회전 17화
Skip: 주술회전 18화
Skip: 주술회전 19화
Skip: 주술회전 20화
Skip: 주술회전 21화
Skip: 주술회전 22화
Skip: 주술회전 23화
Skip: 주술회전 24화
Skip: 주술회전 25화
Skip: 주술회전 26화
Skip: 주술회전 27화
Skip: 주술회전 28화
Skip: 주술회전 29화
Skip: 주술회전 30화
Skip: 주술회전 31화
Skip: 주술회전 32화
Skip: 주술회전 33화
Skip: 주술회전 34화
Skip: 주술회전 35화
Skip: 주술회전 36화
Skip: 주술회전 37화
Skip: 주술회전 38화
Skip: 주술회전 39화
Skip: 주술회전 40화
Skip: 주술회전 41화
Skip: 주술회전 42화
Skip: 주술회전 43화
Skip: 주술회전 44화
Skip: 주술회전 45화
Skip: 주술회전 46화
Skip: 주술회전 47화
Skip: 주술회전 48화
Skip: 주술회전 49화
Skip: 주술회전 50화
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 35, in capture
File "FUCK(5)\remote\webdriver", line 587, in page_source
File "FUCK(5)\remote\webdriver", line 309, in execute
File "FUCK(5)\remote\remote_connection", line 460, in execute
File "FUCK(5)\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

stop
Traceback (most recent call last):
File "utils", line 504, in start
File "utils", line 548, in start_
File "mangashow_downloader", line 112, in read
File "mangashow_downloader", line 236, in get_imgs
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 35, in capture
File "FUCK(5)\remote\webdriver", line 587, in page_source
File "FUCK(5)\remote\webdriver", line 309, in execute
File "FUCK(5)\remote\remote_connection", line 460, in execute
File "FUCK(5)\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

Fail: mangashow

done : https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84

Invalid : [mangashow] https://mangashow5.me / bbs / page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84

version: 2.6
platform: Windows-7-6.1.7601-SP1
gal_num: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84
dir: 
zip: 
type: mangashow
artist: 아쿠타미 게게
url: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84
valid: False
done: False
range: None
range_p: None
single: False
time: 1553712276.9 (Mar 28)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
Skip: 주술회전 1화
Skip: 주술회전 2화
Skip: 주술회전 3화
Skip: 주술회전 4화
Skip: 주술회전 5화
Skip: 주술회전 6화
Skip: 주술회전 7화
Skip: 주술회전 8화
Skip: 주술회전 9화
Skip: 주술회전 10화
Skip: 주술회전 11화
Skip: 주술회전 12화
Skip: 주술회전 13화
Skip: 주술회전 14화
Skip: 주술회전 15화
Skip: 주술회전 16화
Skip: 주술회전 17화
Skip: 주술회전 18화
Skip: 주술회전 19화
Skip: 주술회전 20화
Skip: 주술회전 21화
Skip: 주술회전 22화
Skip: 주술회전 23화
Skip: 주술회전 24화
Skip: 주술회전 25화
Skip: 주술회전 26화
Skip: 주술회전 27화
Skip: 주술회전 28화
Skip: 주술회전 29화
Skip: 주술회전 30화
Skip: 주술회전 31화
Skip: 주술회전 32화
Skip: 주술회전 33화
Skip: 주술회전 34화
Skip: 주술회전 35화
Skip: 주술회전 36화
Skip: 주술회전 37화
Skip: 주술회전 38화
Skip: 주술회전 39화
Skip: 주술회전 40화
Skip: 주술회전 41화
Skip: 주술회전 42화
Skip: 주술회전 43화
Skip: 주술회전 44화
Skip: 주술회전 45화
Skip: 주술회전 46화
Skip: 주술회전 47화
Skip: 주술회전 48화
Skip: 주술회전 49화
Skip: 주술회전 50화
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

Traceback (most recent call last):
File "mangashow_downloader", line 255, in get_imgs_page
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 300, in get_imgs_page_legacy
File "mangashow_downloader", line 375, in read_html
File "downloader", line 239, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10053, ''))

fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 35, in capture
File "FUCK(5)\remote\webdriver", line 587, in page_source
File "FUCK(5)\remote\webdriver", line 309, in execute
File "FUCK(5)\remote\remote_connection", line 460, in execute
File "FUCK(5)\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

stop
Traceback (most recent call last):
File "utils", line 504, in start
File "utils", line 548, in start_
File "mangashow_downloader", line 112, in read
File "mangashow_downloader", line 236, in get_imgs
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 35, in capture
File "FUCK(5)\remote\webdriver", line 587, in page_source
File "FUCK(5)\remote\webdriver", line 309, in execute
File "FUCK(5)\remote\remote_connection", line 460, in execute
File "FUCK(5)\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

Fail: mangashow

done : https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84

Invalid : [mangashow] https://93.115.27.87 / bbs / page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84

version: 2.6
platform: Windows-7-6.1.7601-SP1
gal_num: https://93.115.27.87/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84
dir: 
zip: 
type: mangashow
artist: 아쿠타미 게게
url: https://93.115.27.87/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84
valid: False
done: False
range: None
range_p: None
single: False
time: 1553712343.87 (Mar 28)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
Skip: 주술회전 1화
Skip: 주술회전 2화
Skip: 주술회전 3화
Skip: 주술회전 4화
Skip: 주술회전 5화
Skip: 주술회전 6화
Skip: 주술회전 7화
Skip: 주술회전 8화
Skip: 주술회전 9화
Skip: 주술회전 10화
Skip: 주술회전 11화
Skip: 주술회전 12화
Skip: 주술회전 13화
Skip: 주술회전 14화
Skip: 주술회전 15화
Skip: 주술회전 16화
Skip: 주술회전 17화
Skip: 주술회전 18화
Skip: 주술회전 19화
Skip: 주술회전 20화
Skip: 주술회전 21화
Skip: 주술회전 22화
Skip: 주술회전 23화
Skip: 주술회전 24화
Skip: 주술회전 25화
Skip: 주술회전 26화
Skip: 주술회전 27화
Skip: 주술회전 28화
Skip: 주술회전 29화
Skip: 주술회전 30화
Skip: 주술회전 31화
Skip: 주술회전 32화
Skip: 주술회전 33화
Skip: 주술회전 34화
Skip: 주술회전 35화
Skip: 주술회전 36화
Skip: 주술회전 37화
Skip: 주술회전 38화
Skip: 주술회전 39화
Skip: 주술회전 40화
Skip: 주술회전 41화
Skip: 주술회전 42화
Skip: 주술회전 43화
Skip: 주술회전 44화
Skip: 주술회전 45화
Skip: 주술회전 46화
Skip: 주술회전 47화
Skip: 주술회전 48화
Skip: 주술회전 49화
Skip: 주술회전 50화
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
[seed] 주술회전 52화 337870
fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 35, in capture
File "FUCK(5)\remote\webdriver", line 587, in page_source
File "FUCK(5)\remote\webdriver", line 309, in execute
File "FUCK(5)\remote\remote_connection", line 460, in execute
File "FUCK(5)\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

stop
Traceback (most recent call last):
File "utils", line 504, in start
File "utils", line 548, in start_
File "mangashow_downloader", line 112, in read
File "mangashow_downloader", line 236, in get_imgs
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 35, in capture
File "FUCK(5)\remote\webdriver", line 587, in page_source
File "FUCK(5)\remote\webdriver", line 309, in execute
File "FUCK(5)\remote\remote_connection", line 460, in execute
File "FUCK(5)\remote\remote_connection", line 522, in _request
File "urllib2", line 429, in open
File "urllib2", line 447, in _open
File "urllib2", line 407, in _call_chain
File "urllib2", line 1228, in http_open
File "urllib2", line 1201, in do_open
File "httplib", line 719, in getresponse
File "httplib", line 271, in begin
File "httplib", line 234, in _read_status
File "socket", line 373, in readline
timeout: timed out

Fail: mangashow

done : https://93.115.27.87/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84

https://188.214.128.5/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84, https://93.115.27.87/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84, https://mangashow3.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84, https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=%EC%A3%BC%EC%88%A0%ED%9A%8C%EC%A0%84

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/55133433-08a5a480-5169-11e9-8ae9-7397674ec4e8.png)

제 쪽에서 재현할 수 없네요.

**Comment by jinjins7** [comment]
> ![영상](https://user-images.githubusercontent.com/14768120/55133433-08a5a480-5169-11e9-8ae9-7397674ec4e8.png)
> 
> 제언 서 재현 할 수 없습니다.

아 지금은 또 다운로드가 됩니다. 그냥 일시적 장애였나보네요... 다행..ㅠㅠ
