### ISSUE TITLE
망가쇼미 일부 만화가 다운이 안 됩니다.

### ISSUE THREAD

**Issue by i20191243r3263754** [KurtBestor/Hitomi-Downloader-issues#666]
망가쇼미 '고블린 슬레이어 외전 이어 원',  '이 세계는 운이 좋다' 등 일부 만화 다운이 안 됩니다. 오래전에 올라온 UQ HOLDER 같은 만회도 잘 저장되는데 일부 만화가 왜 저장이 안 되는지 잘 모르겠네요..
일단 다른건 저장이 잘 되니 네트워크 문제는 아닌 것 같아요.

Invalid : [mangashow] https://mangashow5.me / bbs / page.php?hid=manga_detail&manga_name=%EC%9D%B4%20%EC%84%B8%EA%B3%84%EB%8A%94%20%EC%9A%B4%EC%9D%B4%20%EC%A2%8B%EB%8B%A4

version: 2.6
platform: Windows-10-10.0.17134
gal_num: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=%EC%9D%B4%20%EC%84%B8%EA%B3%84%EB%8A%94%20%EC%9A%B4%EC%9D%B4%20%EC%A2%8B%EB%8B%A4
dir: 
zip: 
type: mangashow
artist: 이부키 유
url: https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=%EC%9D%B4%20%EC%84%B8%EA%B3%84%EB%8A%94%20%EC%9A%B4%EC%9D%B4%20%EC%A2%8B%EB%8B%A4
valid: False
done: False
range: None
range_p: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
single: True
time: 1553864471.37 (Mar 29)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

[seed] 이 세계는 운이 좋다 1-1화 12380
wait... 이 세계는 운이 좋다 1-1화
Traceback (most recent call last):
File "capture", line 110, in capture
Exception: Timeout

fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 120, in capture
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 504, in start
File "utils", line 548, in start_
File "mangashow_downloader", line 112, in read
File "mangashow_downloader", line 236, in get_imgs
File "constants", line 583, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 566, in wrapper
File "mangashow_downloader", line 263, in get_imgs_page
File "capture", line 120, in capture
Exception: Timeout

Fail: mangashow

done : https://mangashow5.me/bbs/page.php?hid=manga_detail&manga_name=%EC%9D%B4%20%EC%84%B8%EA%B3%84%EB%8A%94%20%EC%9A%B4%EC%9D%B4%20%EC%A2%8B%EB%8B%A4

**Comment by KurtBestor** [comment]
서버가 죽었네요
