### ISSUE TITLE
유튜브 다운로드가 안되네요

### ISSUE THREAD

**Issue by knife9707** [KurtBestor/Hitomi-Downloader-issues#690]
````
【メイプルストーリー】Black Mage第一弾「英雄集結」アニメーションPV

version: 2.6
platform: Windows-10-10.0.17763
gal_num: https://www.youtube.com/watch?v=i5fo8GhCv_g
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: メイプルストーリー公式チャンネル
url: https://www.youtube.com/watch?v=i5fo8GhCv_g
valid: False
done: True
range: None
range_p: None
single: True
time: 1554581695.55 (Apr 7)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\【メイプルストーリー】Black Mage第一弾「英雄集結」アニメーションPV.mp4


[URLs]
[0001] https://r4---sn-3u-bh2le.googlevideo.com/videoplayback?keepalive=yes&c=WEB&mime=video%2Fmp4&txp=5432432&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&pl=17&mt=1554581599&mv=m&ei=vwipXKnpOtHMgAPKuY34CQ&ms=au%2Conr&requiressl=yes&gir=yes&itag=137&clen=98763308&mn=sn-3u-bh2le%2Csn-i3b7kn7r&source=youtube&initcwndbps=1825000&fvip=5&id=o-ABNJy_E1B8f3RcpRoKwqN5wSsOfxh6TNoGsIqrZ747CB&mm=31%2C26&ip=61.73.82.159&key=yt6&lmt=1544600614615834&dur=327.249&expire=1554603296&signature=72EBC23DAA70528DAC60994F5FDACA8D5093D579.7CE06A352F390E8745467BAA4ACB237A7BAAE2ED&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[144p][0fps][None] webm None ─ 278 - 256x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][0fps][None] webm None ─ 242 - 426x240 (240p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][0fps][None] webm None ─ 243 - 640x360 (360p)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] webm None ─ 244 - 854x480 (480p)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)


# stream_final <youtube_dl_test.Video object at 0x27B80570> 248 - 1920x1080 (1080p) 1080p webm None 0fps
# stream_final <youtube_dl_test.Video object at 0x27B80230> 137 - 1920x1080 (1080p) 1080p mp4 None 0fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)

# stream_audio 128kbps m4a mp4a.40.2
https://r4---sn-3u-bh2le.googlevideo.com/videoplayback?keepalive=yes&c=WEB&mime=audio%2Fmp4&txp=5432432&itag=140&pl=17&mt=1554581599&mv=m&ei=vwipXKnpOtHMgAPKuY34CQ&ms=au%2Conr&requiressl=yes&gir=yes&clen=5297835&mn=sn-3u-bh2le%2Csn-i3b7kn7r&source=youtube&initcwndbps=1825000&fvip=5&id=o-ABNJy_E1B8f3RcpRoKwqN5wSsOfxh6TNoGsIqrZ747CB&mm=31%2C26&ip=61.73.82.159&key=yt6&lmt=1544600494068466&dur=327.308&expire=1554603296&signature=B4C0671FE24AFA9C2598446871040F0B016D7852.C725AA9D9A04D564E2D30EFD4268D2B469088232&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&ratebypass=yes
Resolution: 1080p
Codec: avc1.640028 / None
Abr: None
Subtype: mp4
FPS: 0

Download audio: https://r4---sn-3u-bh2le.googlevideo.com/videoplayback?keepalive=yes&c=WEB&mime=audio%2Fmp4&txp=5432432&itag=140&pl=17&mt=1554581599&mv=m&ei=vwipXKnpOtHMgAPKuY34CQ&ms=au%2Conr&requiressl=yes&gir=yes&clen=5297835&mn=sn-3u-bh2le%2Csn-i3b7kn7r&source=youtube&initcwndbps=1825000&fvip=5&id=o-ABNJy_E1B8f3RcpRoKwqN5wSsOfxh6TNoGsIqrZ747CB&mm=31%2C26&ip=61.73.82.159&key=yt6&lmt=1544600494068466&dur=327.308&expire=1554603296&signature=B4C0671FE24AFA9C2598446871040F0B016D7852.C725AA9D9A04D564E2D30EFD4268D2B469088232&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&ratebypass=yes
Convert: E:\nhentai-master\테스트\hitomi_downloaded_youtube\【メイプルストーリー】Black Mage第一弾「英雄集結」アニメーションPV.mp4
rename (1): hitomi_downloaded_youtube\ED16EC01_a.tmp -> E:\nhentai-master\테스트\hitomi_downloaded_youtube\tmp719F0ECD_a.weba
rename (1): E:\nhentai-master\테스트\hitomi_downloaded_youtube\【メイプルストーリー】Black Mage第一弾「英雄集結」アニメーションPV.mp4 -> E:\nhentai-master\테스트\hitomi_downloaded_youtube\tmp719F0ECD_v.mp4
-y -i tmp719F0ECD_a.weba -i tmp719F0ECD_v.mp4 -c copy -strict experimental -preset ultrafast -shortest tmp719F0ECD_o.mp4
[code]
-1073741515
[out]

Failed to convert
-y -i tmp719F0ECD_a.weba -i tmp719F0ECD_v.mp4 -c copy -strict experimental tmp719F0ECD_o.mp4
[code]
-1073741515
[out]

Failed to convert
-y -i tmp719F0ECD_a.weba -i tmp719F0ECD_v.mp4 -c copy -strict experimental tmp719F0ECD_o.mkv
[code]
-1073741515
[out]

Failed to convert
Convert success: False
Traceback (most recent call last):
File "utils", line 644, in start_
File "youtube_downloader", line 214, in post_processing
File "ffmpeg", line 196, in merge
Exception: Failed to convert; no output

done : https://www.youtube.com/watch?v=i5fo8GhCv_g
````

100%에서 계속 실패합니다
+
사용자가 youtube dl을 업데이트 할 수는 없나여?

**Comment by KurtBestor** [comment]
youtube-dl 은 문제 없고, ffmpeg를 이용해서 영상 + 음성을 합치는 중 오류가 뜨네요.

ffmpeg가 켜지긴 하나요?

**Comment by knife9707** [comment]
켜지긴 했었는데..
업데이트 후인지 포맷후인지 갑자기 잘되네용
