### ISSUE TITLE
히토미 대신 익헨이나 히요비 링크로 넘어가서 다운되고 있습니다.

### ISSUE THREAD

**Issue by yoysh** [KurtBestor/Hitomi-Downloader-issues#706]
히토미로 받으려고 했더니 이상하게도 대체 사이트인 히요비나 익헨으로 넘어가 다운되면서 다운이 중단되거나 아예 다운로드가 안되는 사태가 발생하고 있습니다.

**Comment by wpfhfpr** [comment]
Invalid : [hitomi] [Zeno] 芳香ちゃんとえっち (1288748)

version: 2.6a
platform: Windows-7-6.1.7601-SP1
gal_num: [Zeno] 芳香ちゃんとえっち (1288748)
dir: J:\hitomi\[N／A (Zeno)] 芳香ちゃんとえっち (1288748)
zip: 
type: hitomi
artist: None
url: 1288748
valid: False
done: False
range: None
range_p: None
single: True
time: 1554857412.99 (Apr 10)
tags: []
goodbyedpi: False
lock: False


[Gallery]
갤러리 넘버: 1288748

제목: 芳香ちゃんとえっち

작가: zeno

그룹: N/A

타입: artistcg

시리즈: touhou project

캐릭터: yoshika miyako

태그: female:sole female, variant set

언어: N/A


[File Names]



[URLs]



[Messages]
********************************
Gallery number : 1288748
Number of Threads : 64
********************************
Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hiyobi_downloader", line 11, in pop_img_hiyobi
IndexError: list index out of range

Read reader FAILED - hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 1170, in download_hitomi
IndexError: list index out of range

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
Exception

Traceback (most recent call last):
File "hitomi_downloader", line 1178, in download_hitomi
Exception

Fail: hitomi

done : #-*- [Zeno] 芳香ちゃんとえっち (1288748)

**Comment by wpfhfpr** [comment]
[에러 2.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3061533/2.txt)
[에러 1.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3061534/1.txt)

같은 내용일 거같으니 이쪽에 그냥 에러 내용올리겠습니다.
에러 1의 경우 빨간색의 글자로 에러가 발생하고
에러2의 경우 주황색의 글자로 에러라기보단 진행이 안되네요.

**Comment by affinityDrops** [comment]
현재 히요비는 자체 이미지 서버 대신 히토미 이미지 url 끌어다 쓰고 있습니다. 일부 갤러리가 잘못된 히토미 서버를 가리키고 있어서 이미지 다운로드가 안되는 것처럼 보입니다...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/700
