### ISSUE TITLE
마루마루 다운이 안되네요

### ISSUE THREAD

**Issue by Eztarget99** [KurtBestor/Hitomi-Downloader-issues#72]
고오급 설정에서 reCaptcha 뚫기 옵션을 활성화 했으나 에러 메시지가 나오네요.
메시지 내용을 아래에 붙여봅니다.

----------------------------------------------------------------

Invalid : [maru] https://marumaru.in / b / manga / 209424

gal_num: https://marumaru.in/b/manga/209424
dir: 
zip: 
type: maru
artist: None
url: http://marumaru.in/b/manga/209424
valid: False
done: False
range: None
range_p: None

[File Names]

[URLs]

[Messages]
[1] 이세계 미궁에서 하렘을 1화: http://wasabisyrup.com/archives/MzbO9Smo0zk
[2] 이세계 미궁에서 하렘을 2화: http://wasabisyrup.com/archives/HVyfHNVRjXA
[3] 이세계 미궁에서 하렘을 3화: http://wasabisyrup.com/archives/V6zrbDF3_Iw
[4] 이세계 미궁에서 하렘을 3-2화: http://wasabisyrup.com/archives/HSZw7x0i0uQ
[5] 이세계 미궁에서 하렘을 4화: http://wasabisyrup.com/archives/aAOxmozHAYs
[6] 이세계 미궁에서 하렘을 4-2화: http://wasabisyrup.com/archives/fwYnrLsm8iM
[7] 이세계 미궁에서 하렘을 5화: http://wasabisyrup.com/archives/AuyHQQsS5Nc
[8] 이세계 미궁에서 하렘을 5-2화: http://wasabisyrup.com/archives/no-Za05NouE
[9] 이세계 미궁에서 하렘을 5-3화: http://wasabisyrup.com/archives/bvEPHE3tng4
[10] 이세계 미궁에서 하렘을 6화: http://wasabisyrup.com/archives/qwfd1zFTm4w
[11] 이세계 미궁에서 하렘을 6-2화: http://wasabisyrup.com/archives/WMDMv0UbJDk
[12] 이세계 미궁에서 하렘을 6-3화: http://wasabisyrup.com/archives/6iIyaOTwtag
Traceback (most recent call last):
File "recaptcha.pyo", line 120, in get
File "recaptcha.pyo", line 74, in start_driver
File "selenium\webdriver\chrome\webdriver.pyo", line 68, in __init__
File "selenium\webdriver\common\service.pyo", line 114, in start
WebDriverException: Message: Can not connect to the Service chromedriver.exe

Traceback (most recent call last):
File "recaptcha.pyo", line 120, in get
File "recaptcha.pyo", line 74, in start_driver
File "selenium\webdriver\chrome\webdriver.pyo", line 68, in __init__
File "selenium\webdriver\common\service.pyo", line 114, in start
WebDriverException: Message: Can not connect to the Service chromedriver.exe

Traceback (most recent call last):
File "maru_downloader", line 85, in read
File "maru_downloader", line 279, in get_imgs_all
File "bs4\__init__", line 192, in __init__
TypeError: object of type 'NoneType' has no len()

stop
Traceback (most recent call last):
File "maru_downloader", line 85, in read
File "maru_downloader", line 279, in get_imgs_all
File "bs4\__init__", line 192, in __init__
TypeError: object of type 'NoneType' has no len()

Fail: maru

stop
done : https://marumaru.in/b/manga/209424

**Comment by KurtBestor** [comment]
실행파일 폴더에 chromedriver.exe 가 만들어 졌나요?

**Comment by Eztarget99** [comment]
네, 크롬드라이버 실행화일도 생성되었고, 인터넷 엑세스 허용 팝업이 뜨길래 허용도 해줬는데 그러네여

**Comment by KurtBestor** [comment]
chromedriver.exe랑 chrome_data 폴더 지우고 다시 해보실래요?

**Comment by Eztarget99** [comment]
chromedriver.exe 를 지우고 다시 실행했더니 다운로드가 정상적으로 되네요!
감사합니다.
