### ISSUE TITLE
mangarock 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by TAKE-401** [KurtBestor/Hitomi-Downloader-issues#732]
Invalid : [mangarock] https://mangarock.com / manga / mrs-serie-198699

version: 2.6a
platform: Windows-10-10.0.17763
gal_num: https://mangarock.com/manga/mrs-serie-198699
dir: 
zip: 
type: mangarock
artist: None
url: https://mangarock.com/manga/mrs-serie-198699
valid: False
done: False
range: None
range_p: None
single: False
time: 1555213515.56 (Apr 14)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "mangarock_downloader", line 99, in get_soup
File "mangarock_downloader", line 105, in get_title
AttributeError: 'NoneType' object has no attribute 'attrs'

stop
Traceback (most recent call last):
File "utils", line 506, in start
File "utils", line 550, in start_
File "mangarock_downloader", line 49, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "mangarock_downloader", line 99, in get_soup
File "mangarock_downloader", line 105, in get_title
AttributeError: 'NoneType' object has no attribute 'attrs'

Fail: mangarock

done : https://mangarock.com/manga/mrs-serie-198699

작업정보에선 이렇게 나오는데 확인부탁드립니다.

**Comment by KurtBestor** [comment]
Manga Rock에서 아시아 IP는 접근 못하도록 막았어요.

아시아에 계시나요?

**Comment by TAKE-401** [comment]
p{margin-top:0;margin-bottom:0}
    


    VPN을 따로 키고 받아보도록하겠습니다.
