### ISSUE TITLE
기본 데이터를 다운로드 하면 오류가 발생하네요.

### ISSUE THREAD

**Issue by vpvp100** [KurtBestor/Hitomi-Downloader-issues#753]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2109, in dataDownload
  File "hitomi_searcher", line 309, in download_json
ValueError: Could not reserve memory block

일단 이슈 글중에는 같은 증상이 안보이는거 같아서 올려봅니다.

**Comment by KurtBestor** [comment]
다시 시도해도 안 되나요?

**Comment by vpvp100** [comment]
네, 여러번 시도 해봤는데 계속 안되네요.
그리고 특이하게도 좀 오래 켜놓으면 기본 브라우저를 크롬으로 사용하는데
크롬이 안켜지고 익스플로어로 켜질때도 있네요.
