### ISSUE TITLE
마나모아 다운이 되지않습니다.

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#767]
![0002](https://user-images.githubusercontent.com/47558641/56469295-f7ec0400-6472-11e9-829c-d4f2303facec.png)

Invalid : [manamoa] https://manamoa2.net / bbs / board.php?bo_table=manga&wr_id=936080

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://manamoa2.net/bbs/board.php?bo_table=manga&wr_id=936080
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa2.net/bbs/board.php?bo_table=manga&wr_id=936080
valid: False
done: False
range: None
range_p: None
single: True
time: 1555845458.54 (Apr 21)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 397, in __init__
File "manamoa_downloader", line 67, in init
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "manamoa_downloader", line 134, in get_soup
File "manamoa_downloader", line 401, in read_html
File "downloader", line 240, in read_html
File "urllib3\poolmanager", line 146, in urlopen
File "urllib3\connectionpool", line 258, in urlopen
File "urllib3\util\retry", line 132, in increment
File "urllib3\connectionpool", line 240, in urlopen
File "urllib3\connectionpool", line 147, in _make_request
File "urllib3\connectionpool", line 363, in _validate_conn
File "urllib3\connection", line 186, in connect
File "urllib3\util\ssl_", line 196, in ssl_wrap_socket
File "ssl", line 369, in wrap_socket
File "ssl", line 617, in __init__
File "ssl", line 846, in do_handshake
ProtocolError: ('Connection aborted.', error(10054, ''))

Fail: manamoa

stop
done : https://manamoa2.net/bbs/board.php?bo_table=manga&wr_id=936080

잘 되다가 안되는거같은데 아래의 히토미 애니 관련 버전은 권한이 없다하여 실행이 안되네요.

확인 부탁드립니다. 항상 감사합니다.

**Comment by KurtBestor** [comment]
설정에서 `DPI 우회`를 키세요.
