### ISSUE TITLE
히토미 다운이 안 되네요 invalid #bug

### ISSUE THREAD

**Issue by iaray3112** [KurtBestor/Hitomi-Downloader-issues#775]
잘 부탁드리겠습니다

Invalid : [hitomi] https://hitomi.la / galleries / 1402983.html

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://hitomi.la/galleries/1402983.html
dir: 
zip: 
type: hitomi
artist: None
url: https://hitomi.la/galleries/1402983.html
valid: False
done: False
range: None
range_p: None
single: True
time: 1556013001.73 (Apr 23)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
********************************
Gallery number : 1402983
Number of Threads : 64
********************************
get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:False)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

get imgs from e(x)hentai: 1402983
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1402983.html)
Find_ehen(id:1402983, ex:True)
Find in heroku...
not found in heroku
Traceback (most recent call last):
File "hitomi_downloader", line 1156, in download_hitomi
File "hitomi_downloader", line 1607, in ehen_imgs
Exception: URL not found

Read reader FAILED - ehen
Traceback (most recent call last):
File "hitomi_downloader", line 1181, in download_hitomi
Exception: URL not found

Traceback (most recent call last):
File "hitomi_downloader", line 1189, in download_hitomi
Exception

Traceback (most recent call last):
File "hitomi_downloader", line 1189, in download_hitomi
Exception

Fail: hitomi

done : https://hitomi.la/galleries/1402983.html

**Comment by KurtBestor** [comment]
언제부터 안됐나요?

**Comment by iaray3112** [comment]
> 언제부터 안됐나요?

시간대는 기억이 안나고, 오늘 저녁이었어요.
마나모아는 다운 잘 되구요, 히토미도 처음엔 잘 됐는데 갑자기 오류났었어요

**Comment by KurtBestor** [comment]
설정에서 `DPI 우회` 키고 시도해보세요. 어떻게 되나요?

**Comment by iaray3112** [comment]
> 설정에서 `DPI 우회` 키고 시도해보세요. 어떻게 되나요?

이번엔 0/1100 이런식으로 다운이 안되네요

**Comment by iaray3112** [comment]
히토미에서 파일 수가 많은 게임 cg를 다운 받았는데 다운 출처가 익헨이라 그런지
일정시간 익헨 밴을 당한것 같아요 ㅠㅠ
다운로더의 dpi우회나 vpn 우회해봐도 익헨 접속이 안 되네요
