### ISSUE TITLE
유튜브 다운로드 실패

### ISSUE THREAD

**Issue by Lahet** [KurtBestor/Hitomi-Downloader-issues#780]
유튜브 영상 다운로드를 시도했는데 "token" parameter not in video info for unknown reason; 으로 다운로드가 불가능하네요. yt-dl 들어가보니 관련된 최신글에 새 버전에서 해결되었다고 하네요. 

항상 감사합니다.

-------로그-------

Invalid : [youtube] https://www.youtube.com / watch?v=1U0Ji6JooH0

version: 2.6b
platform: Windows-10-10.0.17134
gal_num: https://www.youtube.com/watch?v=1U0Ji6JooH0
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=1U0Ji6JooH0
valid: False
done: False
range: None
range_p: None
single: True
time: 1556109347.98 (Apr 24)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1U0Ji6JooH0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1U0Ji6JooH0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1U0Ji6JooH0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

------중략------

fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1U0Ji6JooH0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 507, in start
File "utils", line 551, in start_
File "youtube_downloader", line 163, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 1U0Ji6JooH0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Fail: youtube

done : https://www.youtube.com/watch?v=1U0Ji6JooH0

**Comment by jaejunghan** [comment]
Invalid : [youtube] https://www.youtube.com / watch?v=o7MfoOwS8aU

version: 2.6b
platform: Windows-10-10.0.17134
gal_num: https://www.youtube.com/watch?v=o7MfoOwS8aU
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=o7MfoOwS8aU
valid: False
done: False
range: None
range_p: None
single: True
time: 1556094956.53 (Apr 24)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 507, in start
File "utils", line 551, in start_
File "youtube_downloader", line 163, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: o7MfoOwS8aU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Fail: youtube

done : https://www.youtube.com/watch?v=o7MfoOwS8aU

**Comment by jaejunghan** [comment]
저도 마찬가지로 이러합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Lahet** [comment]
영상/음성only 정상적으로 다운로드 됩니다. 감사합니다.
