### ISSUE TITLE
일주일 전부터 유튜브 다운로드 안됩니다

### ISSUE THREAD

**Issue by norado** [KurtBestor/Hitomi-Downloader-issues#799]
맛상무 유튜브 조은도너츠편 까지 다운로드 해서 봤었구요. 약 일주일 전부터 유튜브 다운로드 안됩니다.

Invalid : [youtube] https://www.youtube.com / watch?v=x06ZWsPAWwI

version: 2.6b
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=x06ZWsPAWwI
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=x06ZWsPAWwI
valid: False
done: False
range: None
range_p: None
single: True
time: 1556547408.92 (Apr 29)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 507, in start
File "utils", line 551, in start_
File "youtube_downloader", line 163, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: x06ZWsPAWwI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Fail: youtube

done : https://www.youtube.com/watch?v=x06ZWsPAWwI

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/780
