### ISSUE TITLE
큰파일 다운중 작동 중지

### ISSUE THREAD

**Issue by ghjg5556** [KurtBestor/Hitomi-Downloader-issues#8]
큰파일을 받거나 한번에 많이 받으면 작동중지되여

Traceback (most recent call last):
  File "customWidget.pyo", line 380, in showMenu
RuntimeError: wrapped C/C++ object of type QToolButton has been deleted
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 2213, in clip_timer_event
  File "hitomi_downloader_GUI.py", line 775, in downButton
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 2213, in clip_timer_event
  File "hitomi_downloader_GUI.py", line 775, in downButton
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by KurtBestor** [comment]
해당 문제 고쳤습니다. 다음 링크에서 패치판을 다운로드할 수 있습니다:

> [Link](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview)

확인해주시면 감사하겠습니다.
