### ISSUE TITLE
마나모아 다운이 안되요

### ISSUE THREAD

**Issue by soulk123** [KurtBestor/Hitomi-Downloader-issues#826]
아까까지만 해도 됐는데

갑자기 안되네요;;

Invalid : [manamoa] https://manamoa3.net / bbs / board.php?bo_table=manga&wr_id=1049054

version: 2.6b
platform: Windows-10-10.0.17134
gal_num: https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1049054
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1049054
valid: False
done: False
range: None
range_p: None
single: True
time: 1557321942.66 (May 8)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Cloudflare protection
Cloudflare protection
Cloudflare protection
Cloudflare protection
stop
Traceback (most recent call last):
File "utils", line 397, in __init__
File "manamoa_downloader", line 67, in init
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "manamoa_downloader", line 143, in get_soup
File "manamoa_downloader", line 401, in read_html
File "downloader", line 307, in read_html
Exception: 503

Fail: manamoa

stop
done : https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1049054

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by soulk123** [comment]
오류였나봐요 어제 , 오늘 아주 잘되용
