### ISSUE TITLE
유튜브 플레이리스트 통째로 다운 받을순 없나요 

### ISSUE THREAD

**Issue by inchaos4315** [KurtBestor/Hitomi-Downloader-issues#827]
유튜브 플레이 리스트에 

수록된 동영상이 많아

일일히 하기 어려워서 

영상들을 전부 한번에 받고 싶은데

혹시 관련 기능은 없는건가요?

시도해 봤더니 오류가 나오진 않고

몇시간째 읽는중 표시만 나오고 있습니다

**Comment by wkd284** [comment]
엄청 많으신가보네요. 전 300개 정도 되는 플레이리스트 받아지던데요.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by inchaos4315** [comment]
Invalid : [youtube] https://www.youtube.com / playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt
valid: False
done: False
range: None
range_p: None
single: True
time: 1557473298.2 (May 10)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 507, in start
File "utils", line 551, in start_
File "youtube_downloader", line 167, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 804, in extract_info
File "FUCK(3)\YoutubeDL", line 1003, in process_ie_result
File "FUCK(3)\YoutubeDL", line 865, in process_ie_result
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: nkwf2R5Z8H4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Fail: youtube

done : https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt

**Comment by inchaos4315** [comment]
150곡 정도인데 ㅜ 안되네요 실패메세지를 받기는 했습니다

**Comment by inchaos4315** [comment]
#780 이슈 참고해서 테스트 버전 받아서 했는데 읽는중 표시만 나오네요 여전히

**Comment by inchaos4315** [comment]
읽는 중... https://www.youtube.com / playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt
valid: True
done: False
range: None
range_p: None
single: True
time: 1557480485.72 (May 10)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

**Comment by inchaos4315** [comment]
Invalid : [youtube] https://www.youtube.com / playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt
valid: False
done: False
range: None
range_p: None
single: True
time: 1557480485.72 (May 10)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 807, in extract_info
File "FUCK(3)\YoutubeDL", line 1006, in process_ie_result
File "FUCK(3)\YoutubeDL", line 868, in process_ie_result
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:726)> (caused by URLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:726)'),))

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 807, in extract_info
File "FUCK(3)\YoutubeDL", line 1006, in process_ie_result
File "FUCK(3)\YoutubeDL", line 868, in process_ie_result
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:726)> (caused by URLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:726)'),))

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 807, in extract_info
File "FUCK(3)\YoutubeDL", line 1006, in process_ie_result
File "FUCK(3)\YoutubeDL", line 868, in process_ie_result
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:726)> (caused by URLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:726)'),))

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'

stop
Traceback (most recent call last):
File "utils", line 520, in start
File "utils", line 564, in start_
File "youtube_downloader", line 167, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 57, in __init__
KeyError: 'formats'


Fail: youtube

done : https://www.youtube.com/playlist?list=PLoG6biQNZQ_MB1C9RpCNwLyqkEPXrrPYt

**Comment by inchaos4315** [comment]
#780 이슈 참고해서 테스트 버전 받아서 해서 나온 실패 결과입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by inchaos4315** [comment]
잘되네요 감사합니다!
