### ISSUE TITLE
유튜브 다운로드가 안됨니다 

### ISSUE THREAD

**Issue by wlsgh5286** [KurtBestor/Hitomi-Downloader-issues#828]
스크렙트는 이거 입니다 왜 나운로드가 안되나요 ㅠㅠ 

Invalid : [youtube] https://www.youtube.com / watch?v=5w_gXMlJBf8

version: 2.6b
platform: Windows-10-10.0.18362
gal_num: https://www.youtube.com/watch?v=5w_gXMlJBf8
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=5w_gXMlJBf8
valid: False
done: False
range: None
range_p: None
single: True
time: 1557467133.81 (May 10)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 507, in start
File "utils", line 551, in start_
File "youtube_downloader", line 163, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: 5w_gXMlJBf8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Fail: youtube

done : https://www.youtube.com/watch?v=5w_gXMlJBf8

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/780
