### ISSUE TITLE
유튜브 다운로드 안됨

### ISSUE THREAD

**Issue by GH6** [KurtBestor/Hitomi-Downloader-issues#836]
업로더가 다른 사이트에서의 재생을 하지 못하게 하면 재생을 할 수가 없나요?
Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by ShizuKR** [comment]
Invalid : [youtube] https://www.youtube.com / watch?v=UymjSZKZjuc

version: 2.6b
platform: Windows-10-10.0.17763
gal_num: https://www.youtube.com/watch?v=UymjSZKZjuc
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=UymjSZKZjuc
valid: False
done: False
range: None
range_p: None
single: True
time: 1557976986.0 (May 16)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

stop
Traceback (most recent call last):
File "utils", line 507, in start
File "utils", line 551, in start_
File "youtube_downloader", line 163, in read
File "constants", line 611, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 594, in wrapper
File "youtube_downloader", line 314, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 816, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: UymjSZKZjuc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Fail: youtube

done : https://www.youtube.com/watch?v=UymjSZKZjuc

**Comment by KurtBestor** [comment]
참고해주세요: #780

**Comment by GH6** [comment]
아니 왜 이 글에 전혀 다른 에러내용을 쓰신다냐

Invalid : [youtube] https://www.youtube.com / watch?v=_kttC_6dgyM

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=_kttC_6dgyM
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=_kttC_6dgyM
valid: False
done: False
range: None
range_p: None
single: True
time: 1557996423.42 (May 16)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "youtube_downloader", line 164, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.


Fail: youtube

done : https://www.youtube.com/watch?v=_kttC_6dgyM

**Comment by KurtBestor** [comment]
@GH6 
유튜브 로그인이 필요한 동영상인데, 현재는 지원하지 않아요.

**Comment by GH6** [comment]
다른 성인인증 동영상도 정상적으로 다운로드가 되던데요.


2019년 5월 16일 (목) 오후 6:31, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by KurtBestor** [comment]
성인인증 필요한 동영상 중에서도 로그인이 필요한 영상이 있어요.
이런 건 성인인증이 필요 없는 국가에서도 로그인을 필요로 해요.
