### ISSUE TITLE
마나모아 다운이 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader-issues#854]
어제부터 다운이 안됩니다
Invalid : [manamoa] https://manamoa3.net / bbs / board.php?bo_table=manga&wr_id=1112226

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1112226
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1112226
valid: False
done: False
range: None
range_p: None
single: True
time: 1558136102.9 (May 18)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Cloudflare protection
Cloudflare protection
Cloudflare protection
Cloudflare protection
stop
Traceback (most recent call last):
File "utils", line 412, in __init__
File "manamoa_downloader", line 80, in init
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 151, in get_soup
File "clf", line 62, in session
File "clf", line 11, in wait
File "chrome", line 124, in start
File "chrome", line 59, in __init__
File "FUCK(5)\chrome\webdriver", line 81, in __init__
File "FUCK(5)\remote\webdriver", line 157, in __init__
File "FUCK(5)\remote\webdriver", line 252, in start_session
File "FUCK(5)\remote\webdriver", line 321, in execute
File "FUCK(5)\remote\errorhandler", line 242, in check_response
WebDriverException: Message: unknown error: cannot find Chrome binary
(Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.17763 x86_64)

Fail: manamoa

stop
done : https://manamoa3.net/bbs/board.php?bo_table=manga&wr_id=1112226

진짜로 프로그램 읽어오는 방식이 바뀐건가요? 
이전 버전방식은 이제 못쓰나요?
암튼 지금은 마나모아 다운이 안됩니다ㅠㅠ

**Comment by mita5549** [comment]
아래 글 한번 찾아보세요.
.6c 버전은 뭔가 오류가 있고, 테스트 버전은 잘 작동하고 있습니다. 
근데 속도가 많이 느려서 50개 정도 받는데 창을 열었다 닫았다 하며 한참을 받고 있네요; ㄷㄷ

**Comment by geniussjt** [comment]
전 테스트 버전도 아예 안되는데..요

**Comment by iaray3112** [comment]
다운 속도가 엄청 느려졌네요. mita님 말대로 인터넷이 열렸다 닫혔다 반복되고 ;;

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/853

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/853

**Comment by iaray3112** [comment]
> 참고해주세요: #853

감사합니다 ^^

**Comment by mita5549** [comment]
왜 그럴까요..ㅠㅠ.. 
저도 리스트 중에 간혹 빨간색으로 글씨 색이 입혀지며 작동 안하는게 있긴 했는데, 다시 시도하면 정상적으로 작동 하긴 했어요!
