### ISSUE TITLE
미리보기가 안보여요

### ISSUE THREAD

**Issue by 23222322** [KurtBestor/Hitomi-Downloader-issues#856]
플로팅 미리보기도 마찬가지고...검색했을때 제일왼쪽에 숫자만 보이고 미리보기 자체가 안보입니다. 2.5b, 2.5c 둘다그렇네요

**Comment by KurtBestor** [comment]
다운로드 목록에서 하나 선택한 뒤 `Ctrl + Alt + C` 눌러서 콘솔 띄우고 다음 내용 입력하고 `Enter` 눌러서 나온 내용 알려주세요:
```
cw=ui.listWidget.currentItem().customWidget;p=QtGui.QPixmap();p.loadFromData(cw.str_pixmap);print(p.size(),len(cw.str_pixmap))
```

**Comment by wherejm39** [comment]
Traceback (most recent call last):
      File "console\Console.pyo", line 157, in execSingle
      File "<string>", line 1, in <module>
    AttributeError: 'NoneType' object has no attribute 'customWidget'
마찬가지로 미리보기 가 뜨지않아 알려주신 방법대로 했을때 다음과 같은 문자가 출력됩니다.

**Comment by KurtBestor** [comment]
@wherejm39 다운로드 목록에서 작업 하나 선택한 것 맞나요?

**Comment by SianJeon** [comment]
(PyQt4.QtCore.QSize(), 0)

**Comment by wherejm39** [comment]
@KurtBestor 하나만 선택된 상태가 아니였네요;;  (PyQt4.QtCore.QSize(227, 320), 133716) 위와 같은 메시지가 출력됩니다.

**Comment by KurtBestor** [comment]
목록에서 하나 선택하고 콘솔에 다음 내용 입력해서 나온 내용 알려주세요:
```
cw=ui.listWidget.currentItem().customWidget;print(cw.iconLabel.logicalDpiX());print(cw.imgs[0]);p=image_reader.QPixmap(cw.imgs[0]);print(p);print(p.size())
```

**Comment by wherejm39** [comment]
@KurtBestor  
96
<image_reader.LoadPixmap object at 0x26730E90>
<PyQt4.QtGui.QPixmap object at 0x25170CF0>
PyQt4.QtCore.QSize(227, 320)

**Comment by KurtBestor** [comment]
미리보기가 어떻게 안 뜨는지 스크린샷 찍어서 보여주세요.

**Comment by wherejm39** [comment]
![asdf](https://user-images.githubusercontent.com/50871012/58100706-1cc1cb80-7c19-11e9-9803-6f2b37660be4.jpg)

깃헙에 이미지 올리는건 처음이라 이렇게 하는게 맞는지 잘 모르겠네요... 흰색 에 해당 작품의 번호만 출력됩니다.

**Comment by KurtBestor** [comment]
검색기 말고 다운로더 목록에서 미리보기는 제대로 보이나요?

**Comment by wherejm39** [comment]
네 다운로드 완료시 목록에서는 정상적으로 출력됩니다.

**Comment by KurtBestor** [comment]
다운로더 메인 창에서 `Shift + Esc` 누르면 어떻게 뜨나요?

**Comment by wherejm39** [comment]
![제목 없음](https://user-images.githubusercontent.com/50871012/58101174-13852e80-7c1a-11e9-9df3-698510519437.png)
다운로드 받은 항목 없이 누른 경우입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by SianJeon** [comment]
안되네요

**Comment by SianJeon** [comment]
![123123213](https://user-images.githubusercontent.com/43112004/58110095-d0cb5280-7c29-11e9-992d-b40cd3fed42d.png)

**Comment by KurtBestor** [comment]
검색기 목록에서 하나 선택하고 콘솔에 다음 내용 입력해서 나오는 내용 알려주세요:
```
customWidget2.preview(ui_searcher.listWidget.currentItem().customWidget)
```

**Comment by SianJeon** [comment]
customWidget2 fail: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
Traceback (most recent call last):
  File "downloader", line 273, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Traceback (most recent call last):
  File "downloader", line 273, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

    Traceback (most recent call last):
      File "console\Console.pyo", line 153, in execSingle
      File "<string>", line 1, in <module>
      File "customWidget2.pyo", line 170, in preview
      File "customWidget2.pyo", line 155, in get_thumbs
      File "hiyobi_downloader.pyo", line 20, in pop_img_hiyobi
      File "downloader.pyo", line 273, in read_html
      File "urllib3\poolmanager.pyo", line 326, in urlopen
      File "urllib3\connectionpool.pyo", line 641, in urlopen
      File "urllib3\util\retry.pyo", line 344, in increment
      File "urllib3\connectionpool.pyo", line 603, in urlopen
      File "urllib3\connectionpool.pyo", line 344, in _make_request
      File "urllib3\connectionpool.pyo", line 843, in _validate_conn
      File "urllib3\connection.pyo", line 350, in connect
      File "urllib3\util\ssl_.pyo", line 356, in ssl_wrap_socket
      File "urllib3\contrib\pyopenssl.pyo", line 478, in wrap_socket
    SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
    

customWidget2.preview(ui_searcher.listWidget.currentItem().customWidget) 

customWidget2 fail: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
Traceback (most recent call last):
  File "downloader", line 273, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Traceback (most recent call last):
  File "downloader", line 273, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

    Traceback (most recent call last):
      File "console\Console.pyo", line 153, in execSingle
      File "<string>", line 1, in <module>
      File "customWidget2.pyo", line 170, in preview
      File "customWidget2.pyo", line 155, in get_thumbs
      File "hiyobi_downloader.pyo", line 20, in pop_img_hiyobi
      File "downloader.pyo", line 273, in read_html
      File "urllib3\poolmanager.pyo", line 326, in urlopen
      File "urllib3\connectionpool.pyo", line 641, in urlopen
      File "urllib3\util\retry.pyo", line 344, in increment
      File "urllib3\connectionpool.pyo", line 603, in urlopen
      File "urllib3\connectionpool.pyo", line 344, in _make_request
      File "urllib3\connectionpool.pyo", line 843, in _validate_conn
      File "urllib3\connection.pyo", line 350, in connect
      File "urllib3\util\ssl_.pyo", line 356, in ssl_wrap_socket
      File "urllib3\contrib\pyopenssl.pyo", line 478, in wrap_socket
    SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

**Comment by KurtBestor** [comment]
콘솔에 다음 입력해서 나온 내용 알려주세요:
```
__import__('urllib2').build_opener().open('https://hitomi.la', timeout=30).read()[:1000]
```

**Comment by SianJeon** [comment]
Traceback (most recent call last):
      File "console\Console.pyo", line 153, in execSingle
      File "<string>", line 1, in <module>
      File "urllib2.pyo", line 429, in open
      File "urllib2.pyo", line 447, in _open
      File "urllib2.pyo", line 407, in _call_chain
      File "urllib2.pyo", line 1241, in https_open
      File "urllib2.pyo", line 1198, in do_open
    URLError: <urlopen error [Errno 10053] >

**Comment by KurtBestor** [comment]
다음 입력해서 나오는 내용 알려주세요:
```
downloader.read_html('https://hitomi.la')[:1000]
```

**Comment by SianJeon** [comment]
Traceback (most recent call last):
  File "downloader", line 273, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

    Traceback (most recent call last):
      File "console\Console.pyo", line 153, in execSingle
      File "<string>", line 1, in <module>
      File "downloader.pyo", line 273, in read_html
      File "urllib3\poolmanager.pyo", line 326, in urlopen
      File "urllib3\connectionpool.pyo", line 641, in urlopen
      File "urllib3\util\retry.pyo", line 344, in increment
      File "urllib3\connectionpool.pyo", line 603, in urlopen
      File "urllib3\connectionpool.pyo", line 344, in _make_request
      File "urllib3\connectionpool.pyo", line 843, in _validate_conn
      File "urllib3\connection.pyo", line 350, in connect
      File "urllib3\util\ssl_.pyo", line 356, in ssl_wrap_socket
      File "urllib3\contrib\pyopenssl.pyo", line 478, in wrap_socket
    SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

**Comment by KurtBestor** [comment]
다운로드는 제대로 되나요?

**Comment by SianJeon** [comment]
다운로드는 제대로 되는데 지금 EH에서 받는거 같아요 

처음 다운받기위해 이니셜라이즈? 하는 시간이 길고 다운받은뒤 아이콘이 H가아닌 EH로 뜹니다

다운로드는 느리지만 되요

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by SianJeon** [comment]
갤러리정보요?

**Comment by KurtBestor** [comment]
검색기 말고 메인 창 목록에서요.

**Comment by SianJeon** [comment]
[Yd] XX ROM (1338620)

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: [Yd] XX ROM (1338620)
dir: DownLoad\[Yd] XX ROM (1338620)
zip: 
type: ehen
artist: Yd
url: https://e-hentai.org/g/1338620/7a5b181cfc
valid: True
done: True
range: None
range_p: None
single: False
time: 1558081923.46 (May 17)
tags: []
goodbyedpi: False
lock: False


[Gallery]
갤러리 넘버: 1338620

제목: XX ROM

작가: yd

그룹: orangemaru

타입: doujinshi

시리즈: fate grand order

캐릭터: mysterious heroine x

태그: full color, group, female:anal, female:bikini, female:swimsuit

언어: Korean


[File Names]
[0001] DownLoad\[Yd] XX ROM (1338620)\IM067_.jpg
[0002] DownLoad\[Yd] XX ROM (1338620)\IM068_.jpg
[0003] DownLoad\[Yd] XX ROM (1338620)\IM069_.jpg
[0004] DownLoad\[Yd] XX ROM (1338620)\IM070_.jpg
[0005] DownLoad\[Yd] XX ROM (1338620)\IM071_.jpg
[0006] DownLoad\[Yd] XX ROM (1338620)\IM072_.jpg
[0007] DownLoad\[Yd] XX ROM (1338620)\IM073_.jpg
[0008] DownLoad\[Yd] XX ROM (1338620)\IM074_.jpg
[0009] DownLoad\[Yd] XX ROM (1338620)\IM075_.jpg
[0010] DownLoad\[Yd] XX ROM (1338620)\IM076_.jpg
[0011] DownLoad\[Yd] XX ROM (1338620)\IM077_.jpg
[0012] DownLoad\[Yd] XX ROM (1338620)\IM078_.jpg
[0013] DownLoad\[Yd] XX ROM (1338620)\IM079_.jpg
[0014] DownLoad\[Yd] XX ROM (1338620)\IM080_.jpg
[0015] DownLoad\[Yd] XX ROM (1338620)\IM081_.jpg
[0016] DownLoad\[Yd] XX ROM (1338620)\IM082_.jpg
[0017] DownLoad\[Yd] XX ROM (1338620)\IM083_.jpg
[0018] DownLoad\[Yd] XX ROM (1338620)\IM084_.jpg
[0019] DownLoad\[Yd] XX ROM (1338620)\IM085_.jpg
[0020] DownLoad\[Yd] XX ROM (1338620)\IM086_.jpg
[0021] DownLoad\[Yd] XX ROM (1338620)\IM087_.jpg
[0022] DownLoad\[Yd] XX ROM (1338620)\IM088_.jpg
[0023] DownLoad\[Yd] XX ROM (1338620)\IM089_.jpg
[0024] DownLoad\[Yd] XX ROM (1338620)\IM090_.jpg
[0025] DownLoad\[Yd] XX ROM (1338620)\IM091_.jpg
[0026] DownLoad\[Yd] XX ROM (1338620)\IM092_.jpg


[URLs]
[0001] https://e-hentai.org/s/687238d29d/1338620-1 ---> http://58.141.61.26:55555/h/42386a89da73adc80c164edeeed4186c669da184-350000-1280-1820-jpg/keystamp=1558082400-2731753ab7;fileindex=66148565;xres=1280/IM067_.jpg
[0002] https://e-hentai.org/s/7fa8345162/1338620-2 ---> http://182.227.202.156:1024/h/f28f38a8a8a6ed6a6f5555a5bd771a29c6955965-390466-1280-1826-jpg/keystamp=1558082400-c1ea4c25b8;fileindex=66148566;xres=1280/IM068_.jpg
[0003] https://e-hentai.org/s/1c8337a21b/1338620-3 ---> http://96.9.85.20:5000/h/d77ace15abd6795a9c2ac5b229fb151dbdd33863-326839-1280-1829-jpg/keystamp=1558082400-bc56d41d04;fileindex=66148567;xres=1280/IM069_.jpg
[0004] https://e-hentai.org/s/c21e655250/1338620-4 ---> http://112.119.211.3:61003/h/d342a8eaf2e9e7374326c16464906bc319ddb1f2-381945-1280-1828-jpg/keystamp=1558082400-7bf9053f79;fileindex=66148568;xres=1280/IM070_.jpg
[0005] https://e-hentai.org/s/5ce8d60b15/1338620-5 ---> http://116.121.215.138:59394/h/5635f2848a0ce980a8541ffb5be3cdd24682da77-320194-1280-1820-jpg/keystamp=1558082400-4d07482627;fileindex=66148569;xres=1280/IM071_.jpg
[0006] https://e-hentai.org/s/8e25a03004/1338620-6 ---> http://112.166.75.182:56702/h/672eb76d01f5dab7bdff5231445c36351151ebbf-362426-1280-1821-jpg/keystamp=1558082400-95cbde5377;fileindex=66148570;xres=1280/IM072_.jpg
[0007] https://e-hentai.org/s/15f81ae55c/1338620-7 ---> http://96.9.85.20:5000/h/7a69a4d5927898ee4aca373b9c0c1957390ad63d-384272-1280-1824-jpg/keystamp=1558082400-9fc13f19ce;fileindex=66148571;xres=1280/IM073_.jpg
[0008] https://e-hentai.org/s/c9762951ff/1338620-8 ---> http://125.182.25.224:2024/h/0479446105285a80b387b44065601d6335f9c307-434057-1280-1823-jpg/keystamp=1558082400-22825611a0;fileindex=66148572;xres=1280/IM074_.jpg
[0009] https://e-hentai.org/s/105c68c0a8/1338620-9 ---> http://14.49.100.116:58198/h/30c934233cffbf2d7ff147853cd8e9119f790cc7-382692-1280-1826-jpg/keystamp=1558082400-ff7fe4f970;fileindex=66148573;xres=1280/IM075_.jpg
[0010] https://e-hentai.org/s/0c752c5971/1338620-10 ---> http://59.115.0.109:55687/h/3814e6899ca185417580998dceb794b2f7283956-405202-1280-1815-jpg/keystamp=1558082400-b1b855e267;fileindex=66148574;xres=1280/IM076_.jpg
[0011] https://e-hentai.org/s/df043d1035/1338620-11 ---> http://218.146.214.230:7775/h/501bde607bb46fb5c64b4fcba55cd419b1f55143-426721-1280-1824-jpg/keystamp=1558082400-36c33ec3ed;fileindex=66148575;xres=1280/IM077_.jpg
[0012] https://e-hentai.org/s/b7adbf3a2b/1338620-12 ---> http://182.227.202.156:1024/h/4f859a3432687c43b9e8736500000d494f35bd01-370125-1280-1816-jpg/keystamp=1558082400-f282fee812;fileindex=66148576;xres=1280/IM078_.jpg
[0013] https://e-hentai.org/s/66a4a05504/1338620-13 ---> http://125.182.25.224:2024/h/72c3e5932eda98034864d40df8afa8d0ece21ab4-412000-1280-1822-jpg/keystamp=1558082400-b37a7f3074;fileindex=66148577;xres=1280/IM079_.jpg
[0014] https://e-hentai.org/s/9d695f4f56/1338620-14 ---> http://112.166.75.182:56702/h/670345c6b3fd3dcfbc5107b8353b344adb966476-487894-1280-1815-jpg/keystamp=1558082400-fac51856fd;fileindex=66148578;xres=1280/IM080_.jpg
[0015] https://e-hentai.org/s/eedbc5d294/1338620-15 ---> http://222.106.186.171:8888/h/b4549aa0561986c351a01c92d3dba82407fd6ab7-465554-1280-1816-jpg/keystamp=1558082400-c6e3368982;fileindex=66148579;xres=1280/IM081_.jpg
[0016] https://e-hentai.org/s/6fbf29c363/1338620-16 ---> http://112.166.75.182:56702/h/1e958263b215a4e00b12ac30d9cdea230079c801-433320-1280-1814-jpg/keystamp=1558082400-fbeeadb4b5;fileindex=66148580;xres=1280/IM082_.jpg
[0017] https://e-hentai.org/s/db769a99ec/1338620-17 ---> http://220.92.54.121:1024/h/486077717736d61430fcd57237965a7b59d3156e-400094-1280-1822-jpg/keystamp=1558082400-6a7146ba09;fileindex=66148581;xres=1280/IM083_.jpg
[0018] https://e-hentai.org/s/745fed7045/1338620-18 ---> http://220.92.54.121:1024/h/c25ce71bfcaeb7b9c80e936e82aa614671713436-413179-1280-1813-jpg/keystamp=1558082400-6453188194;fileindex=66148582;xres=1280/IM084_.jpg
[0019] https://e-hentai.org/s/8a625c5cfd/1338620-19 ---> http://210.183.34.195:55980/h/7e29fe7f8b250be6bb380c5783dddfe4e5e94953-457429-1280-1826-jpg/keystamp=1558082400-d8c2dfb3d5;fileindex=66148583;xres=1280/IM085_.jpg
[0020] https://e-hentai.org/s/5e11f32c6d/1338620-20 ---> http://220.93.198.85:37279/h/63cb05e2c28c6ab6f10be3af1b6fe2d09f1cf78f-421358-1280-1817-jpg/keystamp=1558082400-155b878da8;fileindex=66148584;xres=1280/IM086_.jpg
[0021] https://e-hentai.org/s/0a4469d264/1338620-21 ---> http://220.93.198.85:37279/h/a3f6a4b3ca53efade21434b80a12913d456cf104-405778-1280-1824-jpg/keystamp=1558082400-cc76a4f43c;fileindex=66148585;xres=1280/IM087_.jpg
[0022] https://e-hentai.org/s/c244506460/1338620-22 ---> http://182.227.202.156:1024/h/5b038b0fb62e921feba70ca5a1cdbd98b2772742-423566-1280-1814-jpg/keystamp=1558082400-2e27c015a4;fileindex=66148586;xres=1280/IM088_.jpg
[0023] https://e-hentai.org/s/b95ac223fb/1338620-23 ---> http://220.92.54.121:1024/h/b7348c6e9befadf0293ced0c363d11319d590923-390405-1280-1826-jpg/keystamp=1558082400-b5786527f3;fileindex=66148587;xres=1280/IM089_.jpg
[0024] https://e-hentai.org/s/91b1bc5b7e/1338620-24 ---> http://211.95.63.115:56630/h/32bbb166e3da9f3745e0af45fabb203070418d2e-360505-1280-1835-jpg/keystamp=1558082400-ef9e0be823;fileindex=66148588;xres=1280/IM090_.jpg
[0025] https://e-hentai.org/s/1defa152f5/1338620-25 ---> http://59.7.225.248:1024/h/fddd74e4b1e1f19bbea5b5c2a30ecfd080365917-128074-1280-1806-jpg/keystamp=1558082400-dc0a18ec02;fileindex=66148589;xres=1280/IM091_.jpg
[0026] https://e-hentai.org/s/3d28b2439f/1338620-26 ---> http://220.92.54.121:1024/h/3e25cc2ec8f9bb8119eaa3ce087130168ea31d42-97082-1280-1817-jpg/keystamp=1558082400-31f671b366;fileindex=66148590;xres=1280/IM092_.jpg

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정` - `고급 설정` 에서 `DPI 우회` 켜보세요.

**Comment by SianJeon** [comment]
완료

**Comment by KurtBestor** [comment]
아직 문제 그대로인가요?

**Comment by SianJeon** [comment]
dpi우회 옵션 설정후 정상 작동되는거 확인 했습니다. 
히토미에서 다운로드 되는거 같구영 미리보기도 정상 작동합니다.
