### ISSUE TITLE
요즘 히토미에서 다운할떄 목록엔 일단 히토미로 뜨는데

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader-issues#860]
막상 다운 시작되면 E헨타이로 바뀝니다.
이게 히토미에서 다운이 안되면 백업으로 E헨에서 다운하는 그런 기능이었던거같은데 예외없이 전부 E헨타이에서 다운하는것으로 바뀌는것은 히토미와의 연결에 문제가 있는건가요?

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by supermekadeathstalin** [comment]
[Tamagoro][Funi Funi Lab] Chibikko Bitch XY (decensored) ([Pokemon] ： 1234486)

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: [Tamagoro] Chibikko Bitch XY (decensored) (1234486)
dir: C:\Users\kdss9\Downloads\manga\[Tamagoro][Funi Funi Lab] Chibikko Bitch XY (decensored) ([Pokemon] ： 1234486)
zip: 
type: ehen
artist: Tamagoro
url: https://exhentai.org/g/1234486/a7620060cd
valid: True
done: False
range: None
range_p: None
single: False
time: 1558285626.87 (May 20)
tags: []
goodbyedpi: False
lock: False


[Gallery]
갤러리 넘버: 1234486

제목: Chibikko Bitch XY (decensored)

작가: tamagoro

그룹: funi funi lab

타입: doujinshi

시리즈: pokemon

캐릭터: serena, shauna

태그: full color, uncensored, female:ahegao, female:dark skin, female:loli, female:nakadashi, female:prostitution, male:dilf

언어: Korean

[URLs]
[0001] https://exhentai.org/s/33c4db5dab/1234486-1 ---> https://ehgt.org/g/509.gif
[0002] https://exhentai.org/s/5ea3a85861/1234486-2 ---> https://ehgt.org/g/509.gif
[0003] https://exhentai.org/s/7a7ae75d79/1234486-3
[0004] https://exhentai.org/s/adcb4cbcdb/1234486-4
[0005] https://exhentai.org/s/76cd854d50/1234486-5
[0006] https://exhentai.org/s/b99089f9e7/1234486-6
[0007] https://exhentai.org/s/5a13a39dd0/1234486-7
[0008] https://exhentai.org/s/60df7f9b14/1234486-8
[0009] https://exhentai.org/s/3dc001cd78/1234486-9
[0010] https://exhentai.org/s/ac91eb9191/1234486-10
[0011] https://exhentai.org/s/cf673f2831/1234486-11
[0012] https://exhentai.org/s/65bb98588d/1234486-12
[0013] https://exhentai.org/s/533a5803e5/1234486-13
[0014] https://exhentai.org/s/245c9dc193/1234486-14
[0015] https://exhentai.org/s/d0ac0f8840/1234486-15
[0016] https://exhentai.org/s/3dcbedffe7/1234486-16
[0017] https://exhentai.org/s/cf24e1fd9b/1234486-17
[0018] https://exhentai.org/s/093dcc03e5/1234486-18
[0019] https://exhentai.org/s/cecfaee0c6/1234486-19
[0020] https://exhentai.org/s/d71de41ed3/1234486-20
[0021] https://exhentai.org/s/f833732a78/1234486-21
[0022] https://exhentai.org/s/2a5e3f93d6/1234486-22
[0023] https://exhentai.org/s/1140d4bd3b/1234486-23
[0024] https://exhentai.org/s/1ac5b4c1a5/1234486-24
[0025] https://exhentai.org/s/3829b90bd9/1234486-25
[0026] https://exhentai.org/s/415249ed20/1234486-26
[0027] https://exhentai.org/s/c621c2432f/1234486-27
[0028] https://exhentai.org/s/ad939eedfb/1234486-28
[0029] https://exhentai.org/s/302c09e377/1234486-29
[0030] https://exhentai.org/s/cede46b49b/1234486-30
[0031] https://exhentai.org/s/74fb5098ce/1234486-31
[0032] https://exhentai.org/s/bfebb1f6eb/1234486-32
[0033] https://exhentai.org/s/07d4fb462c/1234486-33
[0034] https://exhentai.org/s/fcf8595b68/1234486-34
[0035] https://exhentai.org/s/e5d9b325b1/1234486-35
[0036] https://exhentai.org/s/10638aea3b/1234486-36


[Messages]
********************************
Gallery number : 1234486
Number of Threads : 64
********************************
Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 272, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 350, in connect
File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

get imgs from e(x)hentai: 1234486
ehen_imgs(ex:False, url:1234486)
Find_ehen(id:1234486, ex:False)
Find in heroku...
Found in heroku: a7620060cd
#### https://e-hentai.org/g/1234486/a7620060cd ----> https://e-hentai.org/g/1234486/a7620060cd
Traceback (most recent call last):
File "hitomi_downloader", line 1167, in download_hitomi
File "hitomi_downloader", line 1642, in ehen_imgs
File "downloader", line 339, in read_html
Exception: 404

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 272, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 350, in connect
File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

get imgs from e(x)hentai: 1234486
ehen_imgs(ex:True, url:1234486)
Find_ehen(id:1234486, ex:True)
Find in heroku...
Found in heroku: a7620060cd
#### https://exhentai.org/g/1234486/a7620060cd ----> https://exhentai.org/g/1234486/a7620060cd
#### https://exhentai.org/g/1234486/a7620060cd ----> https://exhentai.org/g/1234486/a7620060cd/?p=1
FINAL SERVER : ehen
ehen_url : https://exhentai.org/g/1234486/a7620060cd
imgs: 36
E-Hentai: https://exhentai.org/g/1234486/a7620060cd

Title :
[Tamagoro][Funi Funi Lab] Chibikko Bitch XY (decensored) ([Pokemon] ： 1234486)

skip zip
ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

Retry ehen...https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

Retry ehen...https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

Retry ehen...https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/7a7ae75d79/1234486-3
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

ehen retry... https://exhentai.org/s/adcb4cbcdb/1234486-4
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/33c4db5dab/1234486-1
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/76cd854d50/1234486-5
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

Retry ehen...https://exhentai.org/s/5ea3a85861/1234486-2
Traceback (most recent call last):
File "hitomi_downloader", line 283, in run
File "ntpath", line 120, in splitext
File "genericpath", line 75, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'

ehen retry... https://exhentai.org/s/b99089f9e7/1234486-6
Traceback (most recent call last):
File "ehen_downloader", line 48, in get_img
Exception: 509.gif

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 열고 다음 입력하고 `Enter` 눌러서 나온 내용 알려주세요:
```
downloader.read_html('https://hitomi.la')[:1000]
```

**Comment by supermekadeathstalin** [comment]
Traceback (most recent call last):
  File "downloader", line 272, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Traceback (most recent call last):
  File "downloader", line 272, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

User(2742770, 6042be35e994fed920ee7dd11180b65f)
########## https://exhentai.org/g/1341922/38cd014faa https://exhentai.org {'ipb_member_id': '2742770', 'ipb_pass_hash': '6042be35e994fed920ee7dd11180b65f'}
Traceback (most recent call last):
  File "downloader", line 272, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 350, in connect
  File "urllib3\util\ssl_", line 356, in ssl_wrap_socket
  File "urllib3\contrib\pyopenssl", line 478, in wrap_socket
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

Traceback (most recent call last):
  File "downloader", line 270, in read_html
Exception: urllib3 not in methods

    Traceback (most recent call last):
      File "console\Console.pyo", line 153, in execSingle
      File "<string>", line 1, in <module>
      File "downloader.pyo", line 270, in read_html
    Exception: urllib3 not in methods

**Comment by KurtBestor** [comment]
다음 입력해서 나온 내용 알려주세요:
```
__import__('urllib2').build_opener().open('https://hitomi.la', timeout=30).read()[:1000]
```

**Comment by supermekadeathstalin** [comment]
Traceback (most recent call last):
      File "console\Console.pyo", line 153, in execSingle
      File "<string>", line 1, in <module>
      File "urllib2.pyo", line 429, in open
      File "urllib2.pyo", line 447, in _open
      File "urllib2.pyo", line 407, in _call_chain
      File "urllib2.pyo", line 1241, in https_open
      File "urllib2.pyo", line 1198, in do_open
    URLError: <urlopen error [Errno 10054] >

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/856#issuecomment-494457402
