### ISSUE TITLE
인스타그램 다운 안되는데 방법 없을까요? 

### ISSUE THREAD

**Issue by kitknowhowno40** [KurtBestor/Hitomi-Downloader-issues#87]
밑에 인스타관련글 보고 링크가서 테스트파일 다운받아 봤는데 
이런 문구가 나오고 실행이 안되네요
see the logfile

'D:\hitomi_downloader_GUI_test\hitomi_downloader_GUI.exe.log'for details

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 79, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "psutil\__init__.pyo", line 99, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "psutil\_pswindows.pyo", line 12, in <module>
  File "zipextimporter.pyo", line 63, in load_module
ImportError: MemoryLoadLibrary failed loading psutil\_psutil_windows.pyd

버전 2.2b사용하고 있습니다. 그걸로 실행 하면 이렇게 나오네요 

Reading error: insta_official.twice

gal_num: https://www.instagram.com/official.twice/
dir: 
zip: 
type: insta
artist: TWICE 트와이스
url: https://www.instagram.com/official.twice
valid: False
done: False
range: None
range_p: None

[File Names]

[URLs]

[Messages]
Traceback (most recent call last):
File "hitomi_downloader", line 1031, in download_instagram
File "insta_downloader", line 115, in get_nodes
Exception: can not download json! None

Fail: insta

done : https://www.instagram.com/official.twice/

무슨 유틸이나 이런걸로 손봐 줘야 하나요?
제가 할 줄 몰라서 그런건지 ㅜㅜ 방법 있으면 부탁드립니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by kitknowhowno40** [comment]
답변 주셔서 감사드리구요.
OS는 윈도우7 쓰고 있구요 노트북사용중입니다.
테스트 다운받아서 실행했는데 똑같이 나오네요 덮어씌워야 하는건가요?

see the logfile

'D:\hitomi_downloader_GUI_test\hitomi_downloader_GUI.exe.log'for details
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 80, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "psutil\__init__.pyo", line 145, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "psutil\_pswindows.pyo", line 17, in <module>
  File "zipextimporter.pyo", line 63, in load_module
ImportError: MemoryLoadLibrary failed loading psutil\_psutil_windows.pyd


이렇게 나옵니다.

**Comment by kitknowhowno40** [comment]
윈7 32비트입니다

여전히 똑같이 나오네요 

다시 적어봅니다 로그정보

소스코드는 안받아도 되는거죠? 받아봤는데 같은 폴더 깔아도 다른 효과가 없던데 말이죠

Errors occurred
see the logfile

'D:\hitomi_downloader_GUI_test\hitomi_downloader_GUI.exe.log'for details

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 80, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "psutil\__init__.pyo", line 145, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "psutil\_pswindows.pyo", line 17, in <module>
  File "zipextimporter.pyo", line 63, in load_module
ImportError: MemoryLoadLibrary failed loading psutil\_psutil_windows.pyd

**Comment by KurtBestor** [comment]
네, 실행파일 하나만 받으시면 돼요.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

최근에 Win10으로 업데이트했더니 말썽이네요ㅠ

**Comment by kitknowhowno40** [comment]
아닙니다 제가 ㅜㅜ 윈7 편하니까 쓰는거지 
이렇게 신경써주시는 것도 너무 감사합니다.
하지만 위와 똑같은 로그결과가 나오네요 
안되면 어쩔수 없죠.. 제가 괜히 미안하네요..

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by kitknowhowno40** [comment]
실행은 역시 안되고 
로그 결과는 내용은 다르네요

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 127, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "maru_downloader.pyo", line 8, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "recaptcha.pyo", line 1, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "selenium\webdriver\__init__.pyo", line 18, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "selenium\webdriver\firefox\webdriver.pyo", line 42, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "selenium\webdriver\firefox\service.pyo", line 18, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "selenium\webdriver\common\service.pyo", line 28, in <module>
  File "zipextimporter.pyo", line 46, in load_module

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by kitknowhowno40** [comment]
이번에는 실행되긴 했는데 동시에 에러 창까지 뜨네요
![htd](https://user-images.githubusercontent.com/38932017/39606122-aa1a88ce-4f6e-11e8-9be7-67e9134dc629.jpg)


Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 2889, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "hitomi_downloader.pyo", line 833, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "insta_downloader2.pyo", line 54, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "instalooter\looters.pyo", line 18, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "fake_useragent\__init__.pyo", line 4, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "fake_useragent\fake.pyo", line 7, in <module>
  File "zipextimporter.pyo", line 46, in load_module
  File "fake_useragent\settings.pyo", line 12, in <module>
  File "ntpath.pyo", line 59, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 7: ordinal not in range(128)

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by kitknowhowno40** [comment]
실행되고 난 후 처음 1번 다운로드 된 후에
다시 실행 시켜봐도 이런 문구가 나오네요

Query rate exceeded (wait before next run): 

로그정보
No handlers could be found for logger "root"

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by kitknowhowno40** [comment]
처음 실행했을때는 1번 다운되다가 2개 3개 연속으로 목록추가 시키니
메모리 점유율이 너무 커지더니 응답 없음으로 나오고 다운되어서 
컴퓨터를 재부팅후 하니 3개까지 다운되다가 그 이후로는 이전과 같은 메시지가 나오네요

Query rate exceeded (wait before next run):

로그정보 
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 939, in run
  File "hitomi_downloader.pyo", line 1932, in download_hitomi
  File "hitomi_downloader.pyo", line 892, in download_instagram
KeyError: u'https://scontent-icn1-1.cdninstagram.com/vp/dba9e6ea6b30449bd0adfa3397557dd2/5B8C942E/t51.2885-15/e35/31023930_981894945301929_7475407114312089600_n.jpg'

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by kitknowhowno40** [comment]
실행은 되었고 추가 시켰더니
아래 문구가 나오고 다운 안되네요

PhantomsJS를 설치해주세요

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

이건 어떤가요?

**Comment by kitknowhowno40** [comment]
몇백장대의 사진은 여러개 추가하는 건 문제가 없고
몇천장대의 사진은 동시에 추가 하면 TOO SHORT 이란 문장이 나오면서 
안되었는데 하나씩 다시 시작하니 받아졌습니다. 
하지만 이 문제는 다시 종료후 재실행 시키면 쓰는데는 아무 문제 없을거 같습니다.

정말 고맙습니다. 덕분에 잘 쓰겠습니다.

그리고 이번에는 로그가 ghostdriver.log가 남고
실행시킬때 방화벽 윈도우 보안경고가 뜨던데 
별 문제가 있는 건 아니겠죠? ^^
