### ISSUE TITLE
마나모아 몇가지 자료 다운이 안됩니다.

### ISSUE THREAD

**Issue by ronady** [KurtBestor/Hitomi-Downloader-issues#888]
Invalid : [manamoa] https://manamoa.net / bbs / board.php?bo_table=manga&wr_id=557376

version: 2.6c
platform: Windows-8.1-6.3.9600
gal_num: https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=557376
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2111
valid: False
done: False
range: None
range_p: None
single: False
time: 1559137480.02 (May 29)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
redirect: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2111
dirFormat: [artist] title
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
[seed] 고블린 슬레이어 외전 : 이어 원 20-2화 98840
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 281, in get_imgs_page
File "capture", line 29, in capture
File "phantomjs", line 162, in start
File "phantomjs", line 63, in __init__
File "FUCK(5)\phantomjs\webdriver", line 56, in __init__
File "FUCK(5)\common\service", line 84, in start
WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "manamoa_downloader", line 128, in read
File "manamoa_downloader", line 254, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 281, in get_imgs_page
File "capture", line 29, in capture
File "phantomjs", line 162, in start
File "phantomjs", line 63, in __init__
File "FUCK(5)\phantomjs\webdriver", line 56, in __init__
File "FUCK(5)\common\service", line 84, in start
WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 

Fail: manamoa

done : https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=557376

-
https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2111

https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2110

https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=2127

찾고있는 고블린 슬레이어 관련 자료들중 몇가지가 한참동안 로딩만 하다가 다운이 안됩니다.
어떻게 해야되죠?

**Comment by KurtBestor** [comment]
실행파일 경로에 `phantomjs.exe` 파일이 있나요?

**Comment by ronady** [comment]
아니요, 그런 파일은 없네요. 실행에 필요한 중요 파일인가요?

**Comment by KurtBestor** [comment]
네, 원래대로라면 자동으로 생성돼야해요.
실행파일이 있는 곳에 파일 생성이 금지되어있나요?

**Comment by ronady** [comment]
himider_GUI_test 폴더 속성에서 읽기전용 되어있는걸 해제하고
다시 만화 다운로드 실행해도 phantomjs.exe 라는게 다시 생성되거나 하진 않네요.
바탕화면에 최신버전 압축해제해서 실행해도 여전히 안되고요.
그 phantomjs 라는 자료를 올려주실수 없나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ronady** [comment]
역시 안되네요.
dpi우회 실패했다는거 계속 다시 시도하고, 재실행 시켜도 안되고요.
링크에 있는 소스코드 라는것 2개 까지 포함해서 3개 파일 전부 다운받아야 되는건가요?

**Comment by KurtBestor** [comment]
`Ctrl + Alt + C` 눌러서 콘솔 창 열고 `__import__('phantomjs').DIR` 입력하고 `Enter` 눌러서 나온 내용 보여주세요.

**Comment by ronady** [comment]
[Desktop.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3245408/Desktop.zip)

**Comment by KurtBestor** [comment]
`__import__('phantomjs').get()` 입력해서 나온 내용 보여주세요.

**Comment by ronady** [comment]
![00](https://user-images.githubusercontent.com/51165254/58798933-ed5e8600-863e-11e9-97b2-94e2bf6da696.png)
[00.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3247333/00.txt)
-------
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]

__import__('phantomjs').get() 

phantomjs get size...
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/phantomjs.exe Traceback (most recent call last):
  File "downloader", line 398, in get_size
  File "urllib2", line 154, in urlopen
  File "urllib2", line 429, in open
  File "urllib2", line 447, in _open
  File "urllib2", line 407, in _call_chain
  File "urllib2", line 1241, in https_open
  File "urllib2", line 1198, in do_open
URLError: <urlopen error [Errno 10013] >

<urllib3.connection.VerifiedHTTPSConnection object at 0x22BAE9F0>: Failed to establish a new connection: [Errno 10013] 
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/phantomjs.exe Traceback (most recent call last):
  File "downloader", line 398, in get_size
  File "urllib2", line 154, in urlopen
  File "urllib2", line 429, in open
  File "urllib2", line 447, in _open
  File "urllib2", line 407, in _call_chain
  File "urllib2", line 1241, in https_open
  File "urllib2", line 1198, in do_open
URLError: <urlopen error [Errno 10013] >

<urllib3.connection.VerifiedHTTPSConnection object at 0x2077FA90>: Failed to establish a new connection: [Errno 10013] 
phantomjs size: 0
phantomjs size mismatch

 Fail : \\?\c:\users\[]\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
  File "downloader", line 692, in download
Exception: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/phantomjs.exe
Traceback (most recent call last):
  File "downloader", line 688, in download
  File "urllib3\request", line 68, in request
  File "urllib3\request", line 89, in request_encode_url
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 305, in connect
  File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2077FA50>: Failed to establish a new connection: [Errno 10013] 



 Fail : \\?\c:\users\[]\appdata\local\temp\goodbyedpi.zip
Traceback (most recent call last):
  File "downloader", line 692, in download
Exception: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/goodbyedpi_64.zip
Traceback (most recent call last):
  File "downloader", line 688, in download
  File "urllib3\request", line 68, in request
  File "urllib3\request", line 89, in request_encode_url
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 305, in connect
  File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2077F8F0>: Failed to establish a new connection: [Errno 10013] 



 Fail : \\?\c:\users\[]\appdata\local\temp\phantomjs.exe
Traceback (most recent call last):
  File "downloader", line 692, in download
Exception: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/phantomjs.exe
Traceback (most recent call last):
  File "downloader", line 688, in download
  File "urllib3\request", line 68, in request
  File "urllib3\request", line 89, in request_encode_url
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 305, in connect
  File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x236BF0F0>: Failed to establish a new connection: [Errno 10013] 


extract goodbyedpi.exe
extract WinDivert.dll
extract WinDivert64.sys
goodbyedpi loaded
0 41
41 40
phantomjs loaded
u'c:\\users\\[]\\appdata\\local\\temp\\phantomjs.exe'

**Comment by KurtBestor** [comment]
백신이 다운로드를 막고있는 것 같은데, 어떤 백신 쓰시나요?

**Comment by ronady** [comment]
아뇨, 딱히 백신이라 할 만한건 사용하지 않는데요.
![000](https://user-images.githubusercontent.com/51165254/58803597-dde53a00-864a-11e9-8c16-2a451ee3bf7c.png)

아마 피어블록이 뭔가를 차단하고 있을수도 있지만,
지금까지 마나모아 사이트 주소 변경이니 뭐니 때문에 못받은 적은 있어도
피어블록 때문에 다운 못받은 적은 없고요.

**Comment by KurtBestor** [comment]
[여기서](https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/phantomjs.exe) `phantomjs.exe` 다운로드해서 `%temp%` 폴더에 넣어주세요.

**Comment by ronady** [comment]
안돼네요..
다운받아서 C:\Users\[]\AppData\Local\Temp 경로에 넣어둬도
프로그램 실행해서 로딩하다보면 어느샌가 삭제되어버려요. 몇 번이나.
phantomjs.exe 파일이 휴지통에 들어가는 것도 아니고, 아예 없어져버리네요.

**Comment by KurtBestor** [comment]
백신 때문에 삭제되는 것 같아요.
그냥 `phantomjs.exe` 실행하면 어떻게 되나요?

**Comment by ronady** [comment]
피어블록 잠시 해제시킨 상태에서 시도하니까
![제목 없음](https://user-images.githubusercontent.com/51165254/58806123-6e724900-8650-11e9-9b93-9e87750a7883.png)
이렇게 등록되고, 제거안되는 상태까지는 왔지만, 
그래도 피어블록을 키고 끄건 간에, 여전히 다운은 안되네요.

**Comment by ronady** [comment]
![1111](https://user-images.githubusercontent.com/51165254/58806976-33711500-8652-11e9-8ab3-5176c7035811.png)

다른 자료는 정상적으로 받아지는건 변함 없고요.

**Comment by KurtBestor** [comment]
temp 폴더에서 실행시키면 어떻게 되나요?

**Comment by ronady** [comment]
윗 스크린샷이 임시폴더에서 실핸시킨 거고,
어디에 팬텀 을 받아서 실핸시키건 phantomjs>
저것 한 줄로 끝나는건 동일합니다.
그런데 정상적으로 (자료가 받아지는 순간) 임시폴더에서 팬텀이 삭제되더군요.

**Comment by ronady** [comment]
솔직히, 오래된 자료 일부만 못 받을 뿐.
다름기능은 정산이긴 하고..
제작자님 계속 성가시게 해서 죄송하기도 하고..
포기해도 딱히 상관은 없다고 생각되요.
