### ISSUE TITLE
마론마론 그룹의 몇몇 삭제작품들을 다운 할 수 없습니다.

### ISSUE THREAD

**Issue by lamiha** [KurtBestor/Hitomi-Downloader-issues#891]
#676 의 해결방법도 시도해봤는데 전혀 되질 않네요..

**Comment by KurtBestor** [comment]
해당 작업 `마우스 우 클릭` - `정보... (I)` 눌러서 나온 내용 보여주세요.

**Comment by lamiha** [comment]
Invalid : [hitomi] https://히요비.asia / reader / 1097000

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://히요비.asia/reader/1097000
dir: 
zip: 
type: hiyobi
artist: None
url: https://히요비.asia/reader/1097000
valid: False
done: False
range: None
range_p: None
single: False
time: 1559916560.25 (Jun 7)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
********************************
Gallery number : 1097000
Number of Threads : 64
********************************
Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 285, in read_html
Exception: 404

get imgs from e(x)hentai: 1097000
ehen_imgs(ex:False, url:https://히요비.asia/reader/1097000)
Find_ehen(id:1097000, ex:False)
Find in heroku...
Found in heroku: f5e6830989
#### https://e-hentai.org/g/1097000/f5e6830989 ----> https://e-hentai.org/g/1097000/f5e6830989
Traceback (most recent call last):
File "hitomi_downloader", line 1167, in download_hitomi
File "hitomi_downloader", line 1642, in ehen_imgs
File "downloader", line 339, in read_html
Exception: 404

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 285, in read_html
Exception: 404

get imgs from e(x)hentai: 1097000
ehen_imgs(ex:True, url:https://히요비.asia/reader/1097000)
Find_ehen(id:1097000, ex:True)
Find in heroku...
Found in heroku: f5e6830989
#### https://exhentai.org/g/1097000/f5e6830989 ----> https://exhentai.org/g/1097000/f5e6830989
Traceback (most recent call last):
File "hitomi_downloader", line 1167, in download_hitomi
File "hitomi_downloader", line 1654, in ehen_imgs
Exception: no images

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1192, in download_hitomi
Exception: no images

Traceback (most recent call last):
File "hitomi_downloader", line 1144, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 285, in read_html
Exception: 404

get imgs from e(x)hentai: 1097000
ehen_imgs(ex:False, url:https://히요비.asia/reader/1097000)
Find_ehen(id:1097000, ex:False)
Find in heroku...
Found in heroku: f5e6830989
#### https://e-hentai.org/g/1097000/f5e6830989 ----> https://e-hentai.org/g/1097000/f5e6830989
Traceback (most recent call last):
File "hitomi_downloader", line 1167, in download_hitomi
File "hitomi_downloader", line 1642, in ehen_imgs
File "downloader", line 339, in read_html
Exception: 404

FINAL SERVER : hiyobi
ehen_url : None
imgs: 579
Traceback (most recent call last):
File "hitomi_downloader", line 1209, in download_hitomi
File "gallery", line 210, in get_gal
File "gallery", line 231, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'string'

Traceback (most recent call last):
File "hitomi_downloader", line 1209, in download_hitomi
File "gallery", line 210, in get_gal
File "gallery", line 231, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'string'

Fail: hitomi

done : https://히요비.asia/reader/1097000

**Comment by KurtBestor** [comment]
`옵션 (Options)` - `설정 (Preferences)...` - `고급 설정` - `DPI 우회` 키세요.

**Comment by lamiha** [comment]
우회 켜져있는 상태입니다 ㅠ

**Comment by KurtBestor** [comment]
작업 정보 상으론 꺼져있네요.

**Comment by lamiha** [comment]
Invalid : [hitomi] https://히요비.asia / reader / 1097000

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://히요비.asia/reader/1097000
dir: 
zip: 
type: hiyobi
artist: None
url: https://히요비.asia/reader/1097000
valid: False
done: False
range: None
range_p: None
single: False
time: 1560852241.96 (Jun 18)
tags: []
goodbyedpi: True
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
********************************
Gallery number : 1097000
Number of Threads : 64
********************************
Traceback (most recent call last):
File "hitomi_downloader", line 1145, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 286, in read_html
Exception: 404

get imgs from e(x)hentai: 1097000
ehen_imgs(ex:False, url:https://히요비.asia/reader/1097000)
Find_ehen(id:1097000, ex:False)
Find in heroku...
Found in heroku: f5e6830989
#### https://e-hentai.org/g/1097000/f5e6830989 ----> https://e-hentai.org/g/1097000/f5e6830989
Traceback (most recent call last):
File "hitomi_downloader", line 1168, in download_hitomi
File "hitomi_downloader", line 1643, in ehen_imgs
File "downloader", line 340, in read_html
Exception: 404

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1193, in download_hitomi
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1145, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 286, in read_html
Exception: 404

get imgs from e(x)hentai: 1097000
ehen_imgs(ex:True, url:https://히요비.asia/reader/1097000)
Find_ehen(id:1097000, ex:True)
Find in heroku...
Found in heroku: f5e6830989
#### https://exhentai.org/g/1097000/f5e6830989 ----> https://exhentai.org/g/1097000/f5e6830989
Traceback (most recent call last):
File "hitomi_downloader", line 1168, in download_hitomi
File "hitomi_downloader", line 1643, in ehen_imgs
File "downloader", line 340, in read_html
Exception: 404

Read reader FAILED - auto
Traceback (most recent call last):
File "hitomi_downloader", line 1193, in download_hitomi
Exception: 404

Traceback (most recent call last):
File "hitomi_downloader", line 1145, in download_hitomi
File "hitomi", line 19, in pop_img
File "downloader", line 286, in read_html
Exception: 404

get imgs from e(x)hentai: 1097000
ehen_imgs(ex:False, url:https://히요비.asia/reader/1097000)
Find_ehen(id:1097000, ex:False)
Find in heroku...
Found in heroku: f5e6830989
#### https://e-hentai.org/g/1097000/f5e6830989 ----> https://e-hentai.org/g/1097000/f5e6830989
Traceback (most recent call last):
File "hitomi_downloader", line 1168, in download_hitomi
File "hitomi_downloader", line 1643, in ehen_imgs
File "downloader", line 340, in read_html
Exception: 404

FINAL SERVER : hiyobi
ehen_url : None
imgs: 579
Traceback (most recent call last):
File "hitomi_downloader", line 1210, in download_hitomi
File "gallery", line 210, in get_gal
File "gallery", line 231, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'string'

Traceback (most recent call last):
File "hitomi_downloader", line 1210, in download_hitomi
File "gallery", line 210, in get_gal
File "gallery", line 231, in get_gal_hiyobi
AttributeError: 'NoneType' object has no attribute 'string'

Fail: hitomi

done : https://히요비.asia/reader/1097000

**Comment by lamiha** [comment]
우회 껏다가 다시 켜보고 시도해봤습니다

**Comment by lamiha** [comment]
혹시 제 아이피 문제인가 싶어서(해외거주중 입니다.)  vpn으로 한국아이피로 바꾸고 시도해봤더니 정상적으로 다운로드 되네요
