### ISSUE TITLE
마나모아 다운오류

### ISSUE THREAD

**Issue by fortheempoer** [KurtBestor/Hitomi-Downloader-issues#899]
모든작품들이 다운 안되면서 보니
Invalid : [manamoa] https://manamoa4.net / bbs / page.php?hid=manga_detail&manga_id=483

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://manamoa4.net/bbs/page.php?hid=manga_detail&manga_id=483
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa4.net/bbs/page.php?hid=manga_detail&manga_id=483
valid: False
done: False
range: None
range_p: None
single: False
time: 1559578925.47 (Jun 4)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Cloudflare protection
Cloudflare protection
Cloudflare protection
Cloudflare protection
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 151, in get_soup
File "clf", line 56, in session
File "clf", line 48, in wait
Exception: Recaptcha

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "manamoa_downloader", line 125, in read
File "manamoa_downloader", line 111, in name
File "manamoa_downloader", line 97, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 151, in get_soup
File "clf", line 56, in session
File "clf", line 48, in wait
Exception: Recaptcha

Fail: manamoa

done : https://manamoa4.net/bbs/page.php?hid=manga_detail&manga_id=483

이렇게 되어있네요...

**Comment by KurtBestor** [comment]
참고해주세요: #848
