### ISSUE TITLE
마나모아 다운로드 오류가 있습니다

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader-issues#908]
![0001](https://user-images.githubusercontent.com/47558641/59043321-fce80400-88b6-11e9-8f6d-7df4600e46ed.png)

Invalid : [manamoa] https://manamoa4.net / bbs / board.php?bo_table=manga&wr_id=1249737

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://manamoa4.net/bbs/board.php?bo_table=manga&wr_id=1249737
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa4.net/bbs/page.php?hid=manga_detail&manga_id=9661
valid: False
done: False
range: None
range_p: None
single: False
time: 1559830305.12 (Jun 6)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Cloudflare protection
redirect: https://manamoa4.net/bbs/page.php?hid=manga_detail&manga_id=9661
Cloudflare protection
Cloudflare protection
Cloudflare protection
Cloudflare protection
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 151, in get_soup
File "clf", line 64, in session
File "clf", line 11, in wait
File "chrome", line 124, in start
File "chrome", line 59, in __init__
File "FUCK(5)\chrome\webdriver", line 81, in __init__
File "FUCK(5)\remote\webdriver", line 157, in __init__
File "FUCK(5)\remote\webdriver", line 252, in start_session
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 397, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=1935): Read timed out. (read timeout=<object object at 0x025584A0>)

stop
Traceback (most recent call last):
File "utils", line 529, in start
File "utils", line 573, in start_
File "manamoa_downloader", line 125, in read
File "manamoa_downloader", line 111, in name
File "manamoa_downloader", line 97, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "manamoa_downloader", line 151, in get_soup
File "clf", line 64, in session
File "clf", line 11, in wait
File "chrome", line 124, in start
File "chrome", line 59, in __init__
File "FUCK(5)\chrome\webdriver", line 81, in __init__
File "FUCK(5)\remote\webdriver", line 157, in __init__
File "FUCK(5)\remote\webdriver", line 252, in start_session
File "FUCK(5)\remote\webdriver", line 319, in execute
File "FUCK(5)\remote\remote_connection", line 374, in execute
File "FUCK(5)\remote\remote_connection", line 397, in _request
File "urllib3\request", line 72, in request
File "urllib3\request", line 150, in request_encode_body
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 368, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 389, in _make_request
File "urllib3\connectionpool", line 307, in _raise_timeout
ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=1935): Read timed out. (read timeout=<object object at 0x025584A0>)

Fail: manamoa

done : https://manamoa4.net/bbs/board.php?bo_table=manga&wr_id=1249737

크롬이 대량으로 켜지면서 다운로드가 안되는 경우도 생기고 간혹 다른건 다운되는데 한두개정도 삑사리가 납니다. 다시 다운로드하면 또 되긴 하지만 그렇게되면 다운로드 순서 정렬이 뒤죽박죽이 되어버려서 흠 ... 해결방법 없을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
