### ISSUE TITLE
유튜브 초장편 영상 다운로드 안 됨

### ISSUE THREAD

**Issue by listandtag** [KurtBestor/Hitomi-Downloader-issues#910]
https://www.youtube.com/watch?v=2bm4fqf9cqU
3시간짜리 영상인데요
영상 읽고 다운 시작하더니 0%에서 갑자기 완료로 넘어가네요.

보더랜드 2 모든 보스전 모음

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=2bm4fqf9cqU
dir: C:\Users\User\Desktop\FH
zip: 
type: youtube
artist: 파이가
url: https://www.youtube.com/watch?v=2bm4fqf9cqU
valid: False
done: True
range: None
range_p: None
single: True
time: 1559856665.35 (Jun 7)
tags: []
goodbyedpi: False
lock: False

[Gallery]
None

[File Names]
[0001] C:\Users\User\Desktop\FH\보더랜드 2 모든 보스전 모음.mp4

[URLs]
[0001] https://manifest.googlevideo.com/api/manifest/dash/requiressl/yes/source/youtube/id/d9b9b87ea7fd72a5/itag/0/ei/roX5XKjlMorNqAGNw7OADg/playback_host/r8---sn-n3cgv5qc5oq-bh2sz.googlevideo.com/mm/31%2C26/mn/sn-n3cgv5qc5oq-bh2sz%2Csn-i3beln7k/ms/au%2Conr/mv/m/pl/19/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1567500/mt/1559856469/fvip/5/ip/210.94.110.79/ipbits/0/expire/1559878158/sparams/ip%2Cipbits%2Cexpire%2Crequiressl%2Csource%2Cid%2Citag%2Cei%2Cplayback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Chfr%2Cas%2Cinitcwndbps/signature/6EECC20A1C420BF2F4F842EF1272184A7450FDA1.467C2FF2214C0D69D79493C6BE37181030EBEF9F/key/yt8

[Messages]
[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[144p][0fps][None] webm None ─ 278 - 256x144 (DASH video)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (DASH video)
[240p][0fps][None] webm None ─ 242 - 426x240 (DASH video)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (DASH video)
[360p][0fps][None] webm None ─ 243 - 640x360 (DASH video)
[480p][0fps][None] webm None ─ 244 - 854x480 (DASH video)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (DASH video)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (DASH video)
[720p][0fps][None] webm None ─ 247 - 1280x720 (DASH video)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (DASH video)
[720p][0fps][None] webm None ─ 302 - 1280x720 (DASH video)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (DASH video)
[720p][0fps][None] mp4 None ─ 298 - 1280x720 (DASH video)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (DASH video)
[1080p][0fps][None] webm None ─ 303 - 1920x1080 (DASH video)
[1080p][0fps][None] mp4 None ─ 299 - 1920x1080 (DASH video)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

# stream_final <youtube_dl_test.Video object at 0x20CD6BD0> 248 - 1920x1080 (DASH video) 1080p webm None 0fps
# stream_final <youtube_dl_test.Video object at 0x20CD6E90> 137 - 1920x1080 (DASH video) 1080p mp4 None 0fps
[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

[None][0fps][48kbps] m4a mp4a.40.5 ─ 139 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)

# stream_audio 128kbps m4a mp4a.40.2
https://manifest.googlevideo.com/api/manifest/dash/requiressl/yes/source/youtube/id/d9b9b87ea7fd72a5/itag/0/ei/roX5XKjlMorNqAGNw7OADg/playback_host/r8---sn-n3cgv5qc5oq-bh2sz.googlevideo.com/mm/31%2C26/mn/sn-n3cgv5qc5oq-bh2sz%2Csn-i3beln7k/ms/au%2Conr/mv/m/pl/19/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1567500/mt/1559856469/fvip/5/ip/210.94.110.79/ipbits/0/expire/1559878158/sparams/ip%2Cipbits%2Cexpire%2Crequiressl%2Csource%2Cid%2Citag%2Cei%2Cplayback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Chfr%2Cas%2Cinitcwndbps/signature/6EECC20A1C420BF2F4F842EF1272184A7450FDA1.467C2FF2214C0D69D79493C6BE37181030EBEF9F/key/yt8
Resolution: 1080p
Codec: avc1.64001e / None
Abr: None
Subtype: mp4
FPS: 0

downloader_v3 fail... p[1 / 2]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 200

downloader_v3 fail... p[0 / 2]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 200

valid=False 1

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by listandtag** [comment]
안 되네요.

Invalid : [youtube] https://www.youtube.com / watch?v=2bm4fqf9cqU

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=2bm4fqf9cqU
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=2bm4fqf9cqU
valid: False
done: False
range: None
range_p: None
single: True
time: 1559908940.57 (Jun 7)
tags: []
goodbyedpi: False
lock: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user

stop
Traceback (most recent call last):
File "utils", line 529, in start
File "utils", line 573, in start_
File "youtube_downloader", line 164, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 55, in __init__
File "FUCK(3)\YoutubeDL", line 819, in extract_info
File "youtube_dl_test", line 13, in report_error
DownloadError: ERROR: This video has been removed by the user


Fail: youtube

done : https://www.youtube.com/watch?v=2bm4fqf9cqU

**Comment by KurtBestor** [comment]
사이트에서 직접 보는 건 되나요?

**Comment by listandtag** [comment]
네. 크롬으로 보다가 다운 받아놓고 나중에 챙겨볼라고 하니까 다운이 안 되네요. 다른 장편 영상은 다 다운 잘되는데...저것만 걍 특이 케이스인 듯

**Comment by KurtBestor** [comment]
지워진 것 같은데 다시 확인해 줄 수 있나요?

**Comment by listandtag** [comment]
OMG WTF....업로더가 영상을 삭제한 거 같네요ㅠㅠㅠㅠㅠ
