### ISSUE TITLE
유튜브 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by eternalgrow** [KurtBestor/Hitomi-Downloader-issues#927]
잘 되다가 4개 정도 받고 다음 거 받으려니깐 연속으로 이러네요.
비슷한 음악 영상 또 받으려니깐 여기도 안 됩니다.

Invalid : [youtube] https://www.youtube.com / watch?v=cott-MKdHWA

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=cott-MKdHWA
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=cott-MKdHWA
valid: False
done: False
range: None
range_p: None
single: True
time: 1560351838.35 (Jun 13)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[144p][0fps][None] webm None ─ 278 - 256x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][0fps][None] webm None ─ 242 - 426x240 (240p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][0fps][None] webm None ─ 243 - 640x360 (360p)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] webm None ─ 244 - 854x480 (480p)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

# stream_final <youtube_dl_test.Video object at 0x240C38D0> 22 - 1280x720 (hd720) 720p mp4 mp4a.40.2 0fps
stream is not valid
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[144p][0fps][None] webm None ─ 278 - 256x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][0fps][None] webm None ─ 242 - 426x240 (240p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][0fps][None] webm None ─ 243 - 640x360 (360p)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] webm None ─ 244 - 854x480 (480p)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

# stream_final <youtube_dl_test.Video object at 0x0736BCF0> 22 - 1280x720 (hd720) 720p mp4 mp4a.40.2 0fps
stream is not valid
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 413, in get_videos
Exception: No videos

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "youtube_downloader", line 168, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 413, in get_videos
Exception: No videos

Fail: youtube

done : https://www.youtube.com/watch?v=cott-MKdHWA

Invalid : [youtube] https://www.youtube.com / watch?v=PvwAqrU6g3g

version: 2.6c
platform: Windows-7-6.1.7601-SP1
gal_num: https://www.youtube.com/watch?v=PvwAqrU6g3g
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=PvwAqrU6g3g
valid: False
done: False
range: None
range_p: None
single: True
time: 1560352483.45 (Jun 13)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[144p][0fps][None] webm None ─ 278 - 256x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[240p][0fps][None] webm None ─ 242 - 426x240 (240p)
[360p][0fps][None] webm None ─ 243 - 640x360 (360p)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] webm None ─ 244 - 854x480 (480p)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

# stream_final <youtube_dl_test.Video object at 0x2409B990> 22 - 1280x720 (hd720) 720p mp4 mp4a.40.2 0fps
stream is not valid
[None][0fps][50kbps] webm opus ─ 249 - audio only (DASH audio)
[None][0fps][70kbps] webm opus ─ 250 - audio only (DASH audio)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[None][0fps][128kbps] webm vorbis ─ 171 - audio only (DASH audio)
[None][0fps][160kbps] webm opus ─ 251 - audio only (DASH audio)
[144p][0fps][None] webm None ─ 278 - 256x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[240p][0fps][None] webm None ─ 242 - 426x240 (240p)
[360p][0fps][None] webm None ─ 243 - 640x360 (360p)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] webm None ─ 244 - 854x480 (480p)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

# stream_final <youtube_dl_test.Video object at 0x2501F3D0> 22 - 1280x720 (hd720) 720p mp4 mp4a.40.2 0fps
stream is not valid
fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 413, in get_videos
Exception: No videos

stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "youtube_downloader", line 168, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 413, in get_videos
Exception: No videos

Fail: youtube

done : https://www.youtube.com/watch?v=PvwAqrU6g3g

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by eternalgrow** [comment]
감사합니다. 잘 됩니다.^^
