### ISSUE TITLE
유튜브 다운로드가 되지 않습니다 ㅠㅠ

### ISSUE THREAD

**Issue by ixkatan** [KurtBestor/Hitomi-Downloader-issues#930]
방금 다운로드한 최신버전 테크니컬 프리뷰 버전인데도 정상적으로 다운로드가 되지 않습니다

Invalid : [youtube] https://www.youtube.com / watch?v=GxYtY-oG4P0

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://www.youtube.com/watch?v=GxYtY-oG4P0
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=GxYtY-oG4P0
valid: False
done: False
range: None
range_p: None
single: True
time: 1560427070.19 (Jun 13)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

### youtube retry...
Traceback (most recent call last):
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

stop
Traceback (most recent call last):
File "utils", line 529, in start
File "utils", line 573, in start_
File "youtube_downloader", line 168, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 599, in wrapper
File "youtube_downloader", line 317, in get_videos
File "youtube_dl_test", line 58, in __init__
File "youtube_dl_test", line 29, in __init__
AttributeError: 'NoneType' object has no attribute 'lower'

Fail: youtube

done : https://www.youtube.com/watch?v=GxYtY-oG4P0

이런식으로 메세지가 뜨네요

도와주세요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ixkatan** [comment]
정상적으로 잘됩니다! 정말 감사합니다.

**Comment by ixkatan** [comment]
게시물 삭제 부탁드립니다.
