### ISSUE TITLE
산카쿠 다운로드 불가현상에 대해..

### ISSUE THREAD

**Issue by starfrut** [KurtBestor/Hitomi-Downloader-issues#937]
invalid 뜨면서 다운이 안됩니다..

[Messages]
login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 0
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 2
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 3
Failed to login Traceback (most recent call last):
File "sankaku_login", line 66, in login_
Exception: https://chan.sankakucomplex.com/user/login

stop
Traceback (most recent call last):
File "utils", line 412, in __init__
File "sankaku_downloader", line 56, in init
File "sankaku_login", line 42, in login
Exception: Failed to login

Fail: sankaku

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by starfrut** [comment]
지금은 또 정상적으로 작동하네요.. 왜 이러지
