### ISSUE TITLE
히토미 기본 데이터 다운로드 갱신이 안됩니다.

### ISSUE THREAD

**Issue by RedRabbit7777** [KurtBestor/Hitomi-Downloader-issues#957]
안녕하세요
덕분에 좋은 프로그램을 알아 편하게 씁니다

저는 매일 신작이 있는지 체크 하는 유저 입니다.
오늘도 신작이 나왔나 체크하기 위해 
기본 데이터 다운을 하니 오류가 발생했습니다

오류 메세지는 아래와 같습니다.

Traceback (most recent call last):
  File "hitomi_searcher", line 214, in download_json
  File "hitomi_searcher", line 375, in download_json_
ValueError: Expected object or value

아 그리고 간혹 1000건 정도 찾다가 목록 지우기를 하더라도
메모리가 바로 삭제되지 않는지 찾기가 점점 느려지더군요

**Comment by RedRabbit7777** [comment]
오늘 다시 시도 해봤는데 됩니다
아마 서버 문제였던것 같습니다.
