### ISSUE TITLE
Gelbooru 랑 Pornhub 둘다 작동이 안되네요.

### ISSUE THREAD

**Issue by e50gun** [KurtBestor/Hitomi-Downloader-issues#969]
**한 3일된거같아요 이 현상...

DPI 우회 켜놨구요.

로그 첨부해 봅니다.**

Invalid : [gelbooru] https://gelbooru.com / index.php?page=post&s=list&tags=254

version: 2.6c
platform: Windows-10-10.0.17134
gal_num: https://gelbooru.com/index.php?page=post&s=list&tags=254
dir: 
zip: 
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=254
valid: False
done: False
range: None
range_p: None
single: False
time: 1561955205.45 (Jul 1)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=254&pid=0&limit=100
stop
Traceback (most recent call last):
File "utils", line 522, in start
File "utils", line 566, in start_
File "gelbooru_downloader", line 64, in read
File "gelbooru_downloader", line 120, in get_imgs
File "downloader", line 272, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2138B430>: Failed to establish a new connection: [Errno 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나,

Fail: gelbooru

done : https://gelbooru.com/index.php?page=post&s=list&tags=254

**Comment by KurtBestor** [comment]
사이트에 직접 접속은 되나요?

**Comment by e50gun** [comment]
@KurtBestor 막힌지 꽤 돼서 크롬으로 접속할때는 Touch VPN 써야 들어갈 수 있어요. 해결 가능할까요?
