### ISSUE TITLE
검색기 기본데이터 다운로드 에러발생

### ISSUE THREAD

**Issue by KurtCobane** [KurtBestor/Hitomi-Downloader-issues#978]
기본데이터 다운로드를 시작하면 응답없음이 뜨거나 아래 오류가 발생합니다.
Technical Preview 버전도 동일한 증상이 발생합니다.
태스크매니저를보면 CPU는 0% 메모리는 130mb정도 점유하고있습니다.

---------------------------
Traceback (most recent call last):
  File "hitomi_searcher", line 215, in download_json
  File "hitomi_searcher", line 378, in download_json_
  File "downloader", line 276, in read_html
  File "urllib3\poolmanager", line 326, in urlopen
  File "urllib3\connectionpool", line 641, in urlopen
  File "urllib3\util\retry", line 344, in increment
  File "urllib3\connectionpool", line 603, in urlopen
  File "urllib3\connectionpool", line 344, in _make_request
  File "urllib3\connectionpool", line 843, in _validate_conn
  File "urllib3\connection", line 305, in connect
  File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x23377AD0>: Failed to establish a new connection: [Errno 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나,
--------------------------------------------

![캡처](https://user-images.githubusercontent.com/52577414/60734052-8f98c300-9f89-11e9-8078-383bbe7b2ea5.JPG)

hitomi_data jason파일은  11번까지만 생성됩니다.
20번까지 생성되야 되는거 아닌가요?

방화벽 예외파일로 등록해뒀습니다.

*/ ini 파일
[Searcher]
normal = 1
forbidden = 0
preview = 1
tags = 1
webtoon = 1
kor = 0
simple = 
title = 
artist = 
group = 
type_all = 1
type_gamecg = 1
type_manga = 1
type_doujinshi = 1
type_artistcg = 1
type_anime = 1
series = 
character = 
tag = 
language = Korean
advanced_search = 1
rem_dup = 0
split = 0
filter = 
zoom = 1.25
fav_artist = []
fav_group = []
fav_series = []
fav_character = []
fav_tag = []
fav_simple = []
bmksort = date
viewmode = list
searchreversed = 0

[Preference]
number of pages = 1
server_auto = 1
server = 4
hitomifilenametypenumber = 0
txtcheck = 1
proxy = 
proxy_idpass = 0
proxy_id = 
zip_ext = 1
zip_rm = 1
zip_ext_nhentai = 0
zip_rm_nhentai = 0
zip_ext_manamoa = 0
zip_rm_manamoa = 0
zip_ext_pixiv = 0
zip_rm_pixiv = 0
zip_ext_twitter = 0
zip_rm_twitter = 0
zip_ext_insta = 0
zip_rm_insta = 0
zip_ext_tumblr = 0
zip_rm_tumblr = 0
zip_ext_deviant = 0
zip_rm_deviant = 0
zip_ext_artstation = 0
zip_rm_artstation = 0
zip_ext_etc = 0
zip_rm_etc = 0
incompletetime = 0
ugoira_gif = 2
ugoira_dither = 1
ugoira_quality = 90
viewer = 0
completer = 1
incomplete = 1
youtube_type = 0
nico_id = 
nico_pw = ±ª‚ƒa–·†T°£
pixiv_id = 
pixiv_pw = ±ª‚ƒa–·†T°£
language = 0
resize = 0
resize_combo = 0
resize_width = 1920
resize_height = 1920
dns = 0
pixiv_tag = 0
hitomi_tag = 1
pixiv_tags = []
hitomi_tags = ["female:loli", "male:males only"]
preview_size = 1
custom_color = 0
color = 4285036170
autosave = 0
autosave_t = 4
dirs = {}
tag_name = {"blue": "Blue", "gray": "Gray", "purple": "Purple", "yellow": "Yellow", "green": "Green", "orange": "Orange", "red": "Red"}
exfile = 0
exfileimg = 0.0
exfilegif = 0.0
exfilevideo = 0.0
youtubeformat = title
showdate = 0.0
checkautodel = 0.0
youtubecombo_res = 1
youtubecombo_abr = 1
hidecheck = 0.0
hideedit = 
box_convert = 0
convertcombo = 0
convertquality = 75
pdfcheck = 0.0
subtitle = 0.0
subtitlecombo = 0
zipprogramedit = 
zipprogrambox = 0
dpicheck = 1.0
startup = 0.0
speedcheck = 0.0
speedbox = 1.0
albumart = 1.0
nicobox = 1
minimizetotray = 0.0
closetotray = 0.0
showtraymessage = 1.0

[Downloader]
always on top = 0
alpha = 100
clipboard = 0
delete without warning = 0
trash = 1
number of threads = 64
dirformat = [artist] title (id)
filter = 
play = 1.0
edit = 
pixivformat = id_ppage
download directory = hitomi_downloaded

[Saved]

**Comment by KurtCobane** [comment]
재시도 해본것들
- Avast free antivirus 삭제후 재시도 동일증상
- Window Defender 종료후 재시도 동일증상
- 방화벽 예외항목 등록후 재시도 동일증상
- C드라이브 SSD에서 실행 동일증상
- 외장하드에서 실행 동일증상
- USB에서 실행 동일증상
- 파이썬 삭제후 재시도 동일증상

노트북에서는 정상작동함을 확인하였습니다..
왜 데스크탑에서만 안될까요

**Comment by KurtCobane** [comment]
해결
cmd 에서 MTU 값을 확인해보니 500으로 나옴
1500으로 바꾼후 재시도 하니 응답없음증상이 사라졌음.
패킷이 너무 작아서 프로그램이 오류난거같음.
