### ISSUE TITLE
Pornhub 다운로드 무한대기

### ISSUE THREAD

**Issue by nadesion** [KurtBestor/Hitomi-Downloader-issues#982]
여러개의 주소를 목록에 올려놓고 받다 보면 점점 0%에서 기다리고 있는 파일 숫자가 늘어나서
최종적으로 모든 대기열이 0%에서 멈추는 현상이 있습니다. 

저장 후 종료하고 다시 시작하기 전에는 멈춘 파일을 삭제하여도 다른 파일을 다운로드 하는 것이 시작되지 않습니다. 

log 파일에는 다음과 같은 로그가 찍힙니다. 

Traceback (most recent call last):
  File "hitomi_downloader.pyo", line 382, in run
  File "constants.pyo", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
  File "constants", line 599, in wrapper
  File "downloader_v3", line 201, in download
Exception: timeout

Traceback (most recent call last):
  File "hitomi_downloader.pyo", line 382, in run
  File "constants.pyo", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
  File "constants", line 599, in wrapper
  File "downloader_v3", line 201, in download
Exception: timeout

Traceback (most recent call last):
  File "hitomi_downloader.pyo", line 382, in run
  File "constants.pyo", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
  File "constants", line 599, in wrapper
  File "downloader_v3", line 201, in download
Exception: timeout

Traceback (most recent call last):
  File "hitomi_downloader.pyo", line 382, in run
  File "constants.pyo", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
  File "constants", line 599, in wrapper
  File "downloader_v3", line 201, in download
Exception: timeout

Traceback (most recent call last):
  File "hitomi_downloader.pyo", line 382, in run
  File "constants.pyo", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
  File "constants", line 599, in wrapper
  File "downloader_v3", line 201, in download
Exception: timeout

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 1264, in run
  File "utils.pyo", line 224, in pop
  File "utils.pyo", line 214, in clean
RuntimeError: Set changed size during iteration
Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 1264, in run
  File "utils.pyo", line 224, in pop
  File "utils.pyo", line 214, in clean
RuntimeError: Set changed size during iteration
Traceback (most recent call last):
  File "hitomi_downloader.pyo", line 382, in run
  File "constants.pyo", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
  File "constants", line 599, in wrapper
  File "downloader_v3", line 201, in download
Exception: timeout

Traceback (most recent call last):
  File "hitomi_downloader.pyo", line 382, in run
  File "constants.pyo", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
  File "constants", line 599, in wrapper
  File "downloader_v3", line 201, in download
Exception: timeout

멈춰 있는 작업중 하나의 정보는 다음과 같이 표시됩니다. 

Please cum in my mouth! Bunny loves sucking my cock in the shower

version: 2.6c
platform: Windows-10-10.0.18362
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5a567db3e3888&pkey=87551651
dir: hitomi_downloaded_pornhub
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5a567db3e3888&pkey=87551651
valid: True
done: False
range: None
range_p: None
single: True
time: 1562505824.5 (Jul 7)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_pornhub\Please cum in my mouth! Bunny loves sucking my cock in the shower.mp4

[URLs]
[0001] https://cv.phncdn.com/videos/201801/10/149513352/720P_1500K_149513352.mp4?vt47BRmPis8EltaZlLnz6fIjNFFha-aQFvYTp2eXA-t67TrM2ISrP-S952X33j7t1cc7YZaR0WW79vBP26jzBQ_BZwgE_VBbFfxDcviwIPPV-rlLO-EUz55f4CKlVubdNBccq28P3O46XB4vTlDL32idMrn2YNvsuV3Q1_fOJwVRdTQf3whm7KXNvj95dpeDSt-o6eQdg3I

[Messages]
Video
[1080p] 
[720p] https://cv.phncdn.com/videos/201801/10/149513352/720P_1500K_149513352.mp4?vt47BRmPis8EltaZlLnz6fIjNFFha-aQFvYTp2eXA-t67TrM2ISrP-S952X33j7t1cc7YZaR0WW79vBP26jzBQ_BZwgE_VBbFfxDcviwIPPV-rlLO-EUz55f4CKlVubdNBccq28P3O46XB4vTlDL32idMrn2YNvsuV3Q1_fOJwVRdTQf3whm7KXNvj95dpeDSt-o6eQdg3I

**Comment by nadesion** [comment]
이런... 글을 올리고 나서 계속 테스트중인데 갑자기 같은 상황이 반복되지 않네요... 네트워크 문제였던건지..

**Comment by KurtBestor** [comment]
지금도 그러나요?

**Comment by nadesion** [comment]
위 글을 올린 다음 2시간 정도 뒤에는 현상이 없어졌다가 지금 현재는 또 현상이 발생하고 있습니ㅏㄷ.
