### ISSUE TITLE
Youtube 다운로드 오류

### ISSUE THREAD

**Issue by meloncafe** [KurtBestor/Hitomi-Downloader-issues#999]
확인 부탁드립니다
감사합니다

발생 주소
----
[https://youtu.be/XCu61Ax68yc](https://youtu.be/XCu61Ax68yc)

오류 발생시 로그
----
【９万人記念！】２人で協力してクリアまで終わらないっ！【Minecraft / アスタルテ】

version: 2.6c
platform: Windows-10-10.0.17763
gal_num: https://youtu.be/XCu61Ax68yc
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: 笹木咲 / Sasaki Saku
url: https://youtu.be/XCu61Ax68yc
valid: False
done: True
range: None
range_p: None
single: True
time: 1563012029.94 (Jul 13)
tags: []
goodbyedpi: True
lock: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\【９万人記念！】２人で協力してクリアまで終わらないっ！【Minecraft／アスタルテ】.mp4

[URLs]
[0001] https://r4---sn-3u-u5xl.googlevideo.com/videoplayback?expire=1563033632&ei=wKspXZeDIobaqAG_3oawCA&ip=183.106.16.249&id=o-AG8BbMOfvxGKsjmPNT93fI7e8Lm8FS3UJVSo481UbA5I&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-3u-u5xl%2Csn-3u-bh2le&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=2080000&mime=video%2Fmp4&ratebypass=yes&dur=14102.221&lmt=1550218621002476&mt=1563011979&fvip=4&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgX7u5ZypxnjN_1bQnD3VrnPLliBUrp3zI_P5D0e47A9UCIQC8F_uYZ6cWjPrHuAtV4FsTPOMT2IN4ZnOeO6IXlYi0_A%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAJHQiwSbpkkDUeA5QJXuuUaHSmeWVhV44qBbaLHC3wltAiApaa816j77emcPbBQ5pPHsgoeHw7f3jenoyvVUA-1d6A%3D%3D

[Messages]
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (DASH audio)
[144p][0fps][None] mp4 None ─ 394 - 256x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][0fps][None] mp4 None ─ 395 - 426x240 (240p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][0fps][None] mp4 None ─ 396 - 640x360 (360p)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] mp4 None ─ 397 - 854x480 (480p)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] mp4 None ─ 398 - 1280x720 (720p)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (medium)
[360p][0fps][128kbps] webm vorbis ─ 43 - 640x360 (medium)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (hd720)

stream_final <youtube_dl_test.Video object at 0x25192870> 398 - 1280x720 (720p) 720p mp4 None 0fps
stream_final <youtube_dl_test.Video object at 0x25192E50> 22 - 1280x720 (hd720) 720p mp4 mp4a.40.2 0fps
Resolution: 720p
Codec: avc1.64001F / mp4a.40.2
Abr: 192kbps
Subtype: mp4
FPS: 0

downloader_v3 fail... p[6 / 1564]
Traceback (most recent call last):
File "downloader_v3", line 60, in run
Exception: size mismatch: 491520 / 1048576

downloader_v3 fail... p[7 / 1564]
Traceback (most recent call last):
File "downloader_v3", line 57, in run
Exception: Not partial content: 404

valid=False 1
done : https://youtu.be/XCu61Ax68yc

**Comment by KurtBestor** [comment]
[youtube-dl](https://github.com/ytdl-org/youtube-dl) 을 써서 비디오를 추출하는데 직접 `youtube-dl` 을 써도 다운로드 되지 않네요.

**Comment by meloncafe** [comment]
확인 감사합니다.
